### ISSUE TITLE
fatal error: opencv2/core.hpp: No such file or directory  #include <opencv2/core.hpp>

### ISSUE THREAD

**Issue by niushaoda** [cfzd/Ultra-Fast-Lane-Detection#1]
fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>

Hello, could you provide a Dockerfile

**Comment by cfzd** [comment]
@niushaoda 
Hi, if you have installed OpenCV C++ correctly, it is a bug of OpenCV default include path. You can try
```
ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2
```

This should fix the problem. The default installed include path of OpenCV is `/usr/local/include/opencv4/opencv2`. However in the code of OpenCV, the default include path is `/usr/local/include/opencv2`. Adding a soft link would solve this problem.

As for docker support, we would discuss it internally. If the installation is too complicated to conduct, we will support docker installation.

**Comment by niushaoda** [comment]
Thank you very much！
