### ISSUE TITLE
May i try this project on pc without Nvida GPU card?

### ISSUE THREAD

**Issue by kindow** [cfzd/Ultra-Fast-Lane-Detection#10]
thanks for sharing this project, i'm curious how will it perform on enviroment without GPU support? Is it possible to run it under CPU power?

**Comment by cfzd** [comment]
@kindow 
Hi , please refer to this [issue](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/3#issuecomment-644518825).

> If you want to test with CPU, it is possible. You can remove the `.cuda()` call and it should be executed in CPU. Here are locations you should remove `.cuda()` call:
> [net](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/test.py#L8)
> [data](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/evaluation/eval_wrapper.py#L56)
> Last, comment out this line: [cudnn](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/test.py#L8)
> The above modification is used for CULane, it is similar for Tusimple. Remove the `.cuda()` call in [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/evaluation/eval_wrapper.py#L90).
> 
> I didn't test the above modifications, but I think it should work since the only difference between CPU inference and GPU inference is the `.cuda()` call and other settings related to this part.

**Comment by kindow** [comment]
@cfzd  really appreciate your help
