### ISSUE TITLE
Questions about Inference 

### ISSUE THREAD

**Issue by messier202** [cfzd/Ultra-Fast-Lane-Detection#100]
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/evaluation/eval_wrapper.py#L24
` out_j = out_j + 1`
为什么此处加1？后面计算位置时用了 `out_j[k, i] * col_sample_w * 1640 / 800) - 1`，个人理解加1是对应格子的右端，加0.5是否更为合理？

**Comment by cfzd** [comment]
@messier202 
Yeah, `0.5` might be more reasonable.
