### ISSUE TITLE
Culane's evaluation tools failed to compile on the server

### ISSUE THREAD

**Issue by luocmin** [cfzd/Ultra-Fast-Lane-Detection#102]
in win10
![image](https://user-images.githubusercontent.com/57932842/95810686-22efa500-0d44-11eb-8099-ea084caffaef.png)

in sever(ubuntu 16.4)
![image](https://user-images.githubusercontent.com/57932842/95810994-e1abc500-0d44-11eb-9f87-ddf2ee1fcf5e.png)

in sever(docker)
![image](https://user-images.githubusercontent.com/57932842/95810750-4dd9f900-0d44-11eb-9bfc-e4a4200832df.png)

**Comment by cfzd** [comment]
@luocmin 
Have you installed OpenCV C++? Or can you please try the vanilla make?
```
ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2
cd evaluation/culane
make
```

**Comment by luocmin** [comment]
@cfzd 
Excuse me in which environment is this command run

**Comment by cfzd** [comment]
you can try in your ubuntu 16.4 sever

**Comment by luocmin** [comment]
@cfzd  Permission denied
![image](https://user-images.githubusercontent.com/57932842/96066471-3ed18300-0ecb-11eb-8986-66c82b64d6f8.png)

**Comment by cfzd** [comment]
@luocmin 
Then I think you can try docker.

**Comment by luocmin** [comment]
![image](https://user-images.githubusercontent.com/57932842/96070506-eb633300-0ed2-11eb-9e56-9f5cc7d2645e.png)

**Comment by luocmin** [comment]
![image](https://user-images.githubusercontent.com/57932842/96070548-046be400-0ed3-11eb-8f1a-54a135c802b3.png)

**Comment by cfzd** [comment]
@luocmin 
Can you try this and rebuild?
```
sudo ldconfig -v
```

**Comment by luocmin** [comment]
bash: sudo: command not found
I am not an administrator  Permission denied

**Comment by cfzd** [comment]
@luocmin 
how about directly run ldconfig -v in docker?

**Comment by luocmin** [comment]
The following command appears
bash: sudo: command not found

**Comment by cfzd** [comment]
@luocmin 
only run ldconfig -v, without sudo

**Comment by luocmin** [comment]
not successful
![image](https://user-images.githubusercontent.com/57932842/96078911-1acf6b00-0ee6-11eb-9b47-34863eb1b2a4.png)

**Comment by cfzd** [comment]
Then I think it's because the OpenCV c++ is not correctly installed. Please do some google search and find your way. By the way, I noticed that a message also hints that your Cuda version is not exactly matched in your docker, just for your information.

**Comment by luocmin** [comment]
I can't install opencv c++

**Comment by cfzd** [comment]
@luocmin 
Unfortunately, the official CULane evaluation tool is based on OpenCV C++. If you can't install it, then you can't evaluate your results on CULane. We can't change this because we are not the official developer. But you can still train the network and visualize the results because these tools don't require the CULane evaluation tool.
