### ISSUE TITLE
some mistakes in CUlane evaluation tool

### ISSUE THREAD

**Issue by Kaimingfan** [cfzd/Ultra-Fast-Lane-Detection#104]
/usr/bin/ld: warning: libzstd.so.1, needed by //usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5, not found (try using -rpath or -rpath-link)
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_initCStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_freeCStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_maxCLevel’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_createCStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_isError’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_getErrorName’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_endStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_createDStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_initDStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_freeDStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_compressStream’未定义的引用
//usr/local/miniconda3/envs/lane-det/lib/libtiff.so.5：对‘ZSTD_decompressStream’未定义的引用
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_test_core.dir/build.make:1298: recipe for target 'bin/opencv_test_core' failed
make[2]: *** [bin/opencv_test_core] Error 1
CMakeFiles/Makefile2:1376: recipe for target 'modules/core/CMakeFiles/opencv_test_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Some mistakes happened when  I install opencv C++.

**Comment by cfzd** [comment]
@Kaimingfan 
So, is it a problem with OpenCV C++? I think you could remove the paths of anaconda from the environment variable `PATH` and rebuild OpenCV C++.
