### ISSUE TITLE
support different number lanes？

### ISSUE THREAD

**Issue by cvchanghao** [cfzd/Ultra-Fast-Lane-Detection#105]
Thanks for your open source！
I noticed that you update files that ‘support different number lanes’. How does it work?
best regards

**Comment by cfzd** [comment]
The core change lies in these commits:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/commit/7666b176ac61427d9c3c6570b0f7dffd945f168a
https://github.com/cfzd/Ultra-Fast-Lane-Detection/commit/e6b4913910ff7744f90ed42d2c721742a1c4daed
https://github.com/cfzd/Ultra-Fast-Lane-Detection/commit/fa552c99bf01d3be3770ea6284fd6847547786c2
https://github.com/cfzd/Ultra-Fast-Lane-Detection/commit/7a3b9ac4297339049122012fecf8af948fe5833d
