### ISSUE TITLE
How to run your own video data？

### ISSUE THREAD

**Issue by sudonghao** [cfzd/Ultra-Fast-Lane-Detection#106]
Hello, I want to detect lane lines in my video data. How do I do that?Please advise, thank you!

**Comment by cfzd** [comment]
@sudonghao 
You can see `demo.py` for detecting lanes on your video. 

Disclaimer: since the model is not trained on your data, the performance is not guaranteed.

**Comment by sudonghao** [comment]
> @sudonghao
> You can see `demo.py` for detecting lanes on your video.
> 
> Disclaimer: since the model is not trained on your data, the performance is not guaranteed.

How do I build my own data set and train fixed parameters to get the model?And then how do you make it run with your own model?

**Comment by cfzd** [comment]
@sudonghao 
If you want to train on your data, the simplest way is to make it in the CULane or Tusimple format. Our code natively supports datasets like CULane and Tusimple.

If your dataset is not in the format of CULane or Tusimple, you might need some conversion code. You need to generate two kinds of files:
- semantic segmentation annotations (each kind of lanes are a separate class)
- a `txt` file containing the pair of (image path, segmentation path)
Then you could train your data.

If you have the trained models, see `speed_real.py` for more information. It could support both video camera input. For visualization of lane lines, see `demo.py` for more information.
