### ISSUE TITLE
culane checkpoint size

### ISSUE THREAD

**Issue by emtsrlee** [cfzd/Ultra-Fast-Lane-Detection#108]
Hi,

I trained origin model with default param and got checkpoint size(ep029.pth) as 365 MB 
batch_size : 32, optim : SGD, learning_rate : 0.1, backbone : 18, distributed : 4 GPU

Your trained checkpoint(culane_18.pth) is only 174 MB.

Before you release the checkpoint, did you do something like quantization?

Thank you.

**Comment by cfzd** [comment]
@emtsrlee 
No, I just leave out the weights of the auxiliary segmentation branch. Also, the trained models might contain the states for the optimizer, so the size could be bigger.
