### ISSUE TITLE
CUlane 数据是如何进行训练的？

### ISSUE THREAD

**Issue by xiaozi-ML** [cfzd/Ultra-Fast-Lane-Detection#109]
大佬，看文章CUlane 划分为18 * 150，请问是将划分后的小块输入到网络进行训练和分类吗？

**Comment by cfzd** [comment]
我们的方法不是粗粒度分割方法，所以其实没有这样的划分过程。对于行，我们会预先定义一些行，称之为行锚。然后在这些行锚上进行横线的分类，分类的类别直接对应车道线坐标。比如图像宽100，我们就定义100类，如果分类是第34类，那么这一行的坐标就是34.
