### ISSUE TITLE
69.9 on the CULane but misalignment with GT in some scene

### ISSUE THREAD

**Issue by wohaiyo** [cfzd/Ultra-Fast-Lane-Detection#11]
Hello, I got a 69.9 on the CULane dataset using a single GPU card with your default settings. I visualized the lane detection results and found that the model performed well in some ideal scene. But the predicted results seriously deviate from the GT when it comes to occlusion, Vehicle lane changing, ambiguous appearance. 
Do you have the same phenomenon? Is this a limitation of the method? backbone? or something else?

**Comment by cfzd** [comment]
@wohaiyo 
 Hi, I'm not sure what's the problem you are talking about. The [youtube demo](https://www.youtube.com/watch?feature=player_embedded&v=lnFbAG3GBN4) shows our results on CULane. 

Can you show these results?
