### ISSUE TITLE
Capturing only adjacent lanes using demo.py

### ISSUE THREAD

**Issue by tharkne** [cfzd/Ultra-Fast-Lane-Detection#110]
I'm running the lane detection in demo.py on my own dataset and would like to only output markings on the lanes directly adjacent to the left and right of the vehicle. I've attempted to change the value of num_lanes in certain functions from 4 to 2, but no adjustments I have made so far have produced the desired result. Is there a reliable way to do this?

**Comment by cfzd** [comment]
@tharkne 
The `out_j` here
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/bb673eb816e5c5356dcab02d72feb937fbb445b6/demo.py#L81
is a `n x 4` matrix, and the 4 means four lanes. You can simply leave out the first and the last column.
```
out_j = out_j[:,2:4]
```
Then the ego lane is preserved.
