### ISSUE TITLE
How to build my own data set and modify network settings then train it

### ISSUE THREAD

**Issue by CNSTJiatongLee** [cfzd/Ultra-Fast-Lane-Detection#112]
I want to label my own data, but I don’t know the supported label format requirements. At the same time, I want to know how to modify the settings to fit my own data set. My expectation is that the model can extract the center trajectory of each lane.
![img](https://user-images.githubusercontent.com/49759256/97145559-56e5b400-17a1-11eb-9b99-6569e2787245.png)
![label](https://user-images.githubusercontent.com/49759256/97145565-5a793b00-17a1-11eb-829d-28c67ea8b305.png)
![label_viz](https://user-images.githubusercontent.com/49759256/97145573-5cdb9500-17a1-11eb-85db-7b4f3b47cc76.png)

**Comment by cfzd** [comment]
@CNSTJiatongLee 
Basically, our method supports the CULane dataset, so if your dataset fits the format of CULane, you can directly use our code to train on your data.

The requirements of CULane:
- lanes should be continuous line segmentation map
- each lane is a separate class
- CULane defines  one background class and 4 valid classes (i.e. four kinds of lanes), which are leftmost, left, right, rightmost
- The total range of label is [0-5], 0 represents the background, [1-4] represents the four kinds of lanes

**Comment by CNSTJiatongLee** [comment]
> @CNSTJiatongLee
> Basically, our method supports the CULane dataset, so if your dataset fits the format of CULane, you can directly use our code to train on your data.
> 
> The requirements of CULane:
> 
> * lanes should be continuous line segmentation map
> * each lane is a separate class
> * CULane defines  one background class and 4 valid classes (i.e. four kinds of lanes), which are leftmost, left, right, rightmost
> * The total range of label is [0-5], 0 represents the background, [1-4] represents the four kinds of lanes

Does it support the Tusimple data set format? I am using the labelme tool for point labeling

**Comment by CNSTJiatongLee** [comment]
> @CNSTJiatongLee
> Basically, our method supports the CULane dataset, so if your dataset fits the format of CULane, you can directly use our code to train on your data.
> 
> The requirements of CULane:
> 
> * lanes should be continuous line segmentation map
> * each lane is a separate class
> * CULane defines  one background class and 4 valid classes (i.e. four kinds of lanes), which are leftmost, left, right, rightmost
> * The total range of label is [0-5], 0 represents the background, [1-4] represents the four kinds of lanes

Does it support the Tusimple data set format? I am using the labelme tool for point labeling

**Comment by cfzd** [comment]
@CNSTJiatongLee 
Yes, we also support Tusimple format. We provide a tool `scripts/convert_tusimple.py` that could convert the Tusimple format to the trainable CULane format.
