### ISSUE TITLE
culane evaluator

### ISSUE THREAD

**Issue by luocmin** [cfzd/Ultra-Fast-Lane-Detection#113]
@cfzd      What's the version of OpencV？

**Comment by cfzd** [comment]
@luocmin 
Opencv4 should be fine.

**Comment by luocmin** [comment]
@cfzd  我在服务器docker里安装 opencv4.3.0   Cmake没有出现错误,但make出现错误
![image](https://user-images.githubusercontent.com/57932842/97271271-51ed3700-186b-11eb-9bf2-5ea5e36b5f93.png)
直接make会出现以下问题：
![image](https://user-images.githubusercontent.com/57932842/97271417-7cd78b00-186b-11eb-9e6c-aa8d87facad8.png)

**Comment by cfzd** [comment]
@luocmin 
它说找不到头文件，你可能需要执行下这个
```
ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2
```

**Comment by cfzd** [comment]
@luocmin 
你先检查一下你的opencv是不是安装到了`/usr/local/include/opencv4/opencv2`，然后用一个软连接链接过去。
说白了，不管怎么样，`/usr/local/include/opencv2`里必须是opencv的头文件所在的地方

**Comment by luocmin** [comment]
我查看了一下，您所说的那个文件里没有opencv
![image](https://user-images.githubusercontent.com/57932842/97281923-0a6da780-1879-11eb-83a1-63acc373f4c5.png)
![Uploading image.png…]()

**Comment by luocmin** [comment]
请问一下这是什么意思呢
![image](https://user-images.githubusercontent.com/57932842/97285622-69352000-187d-11eb-8961-29f3d75d1c7f.png)

**Comment by cfzd** [comment]
@luocmin 
如果没有的话，说明你没有安装好opencv或者把opencv装到别的地方去了。你能找到你opencv装到那儿了吗？
