### ISSUE TITLE
Focal Loss

### ISSUE THREAD

**Issue by messier202** [cfzd/Ultra-Fast-Lane-Detection#114]
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/bb673eb816e5c5356dcab02d72feb937fbb445b6/utils/loss.py#L34
为什么使用 focal loss 替换论文中的CE loss，是为了缓解每条车道线x坐标分布不均衡的问题吗？

**Comment by cfzd** [comment]
@messier202 
期初是有这样的想法，focal loss可能用来缓解分布不均衡问题。但是我们后来试了一下，其实focal loss和CE在最终性能上可以认为没有区别。

**Comment by messier202** [comment]
想再请教一下，之前看到您提到网络在变道时表现不好的问题 #72 
是因为标签类别转换的关系，我尝试对标签重新排序，从原本的0 1 2 3 从左至右的顺序改为 中至左:0 1 2 中至右： 3 4 5
并在个人数据集中增加了一些变道的数据，重新训练后还是没有解决变道问题(训练集上能收敛)，如下：(0 黑 3 绿)
![image](https://user-images.githubusercontent.com/30891465/97521996-b7f7cc80-19d9-11eb-8db1-6767d82c9863.png)
个人分析如下:变道时，网络难以判定中间一条车道线是应该分配标签0 还是 3，导致了所有车道线的标签种类引入了歧义。
如果在后处理时改用argmax，会发现车道线0的点在车道线1 和中间车道线间来回跳跃，车道线3的点在中间车道线 和3间来回跳。
而最左和最右的两条线没有受到影响，预测出了正确的位置。
从目前的网络结构和loss计算方式来看，对每条车道线的预测是相互独立的，无法学习出车道线间的拓扑关系。（此处提一下，车道线是较宽的白块时，会预测出两条靠的很近的线）
而网络之所以能按标签顺序预测出每条线，是因为在训练过程中形成了归纳偏好，会在特定的区域内寻找对应标签的车道线。因为对于某个标签的车道线，分布的区域是会限制在一定范围内的。
以我的标签分配方式为例，0 1 2会倾向于在图像左侧搜索车道线， 3 4 5 倾向于右侧。所以车道线在图像中间区域时，会预测的不太好。
请问下，我的思路对不对，有没有什么好的改进方法？

**Comment by cfzd** [comment]
@messier202 
是的，就是归纳偏好导致每个类别会有喜好，但是换道时中间的线其实没有任何一个类是和他相似的，就导致这种乱跳的情况。我之前也做过一个实验，用分割做的。假设有4条车道线，使用（4+背景类）总共5类的分割模型去做车道线检测，遇到换道就会不好。但是如果，把车道线那4类的特征图加起来，再和背景类的特征图做softmax（等价于做了一个二分类分割模型，一类是所有车道线，一类是背景类），可以看到其实它是能很好的分割出车道线的（二分类），即使在换道情况下。这就说明网络有能把车道线找出来，但是没有很强的能力把这些线很好地输出出来。我觉得你可以在这个方向尝试一下，怎么把线给输出出来。

**Comment by messier202** [comment]
@cfzd 
感谢，有思路了。

**Comment by lucky-xu-1994** [comment]
> 
> 
> @cfzd
> 感谢，有思路了。

您好，请问解决了车道变道导致检测效果不好的问题了么？

**Comment by llxClover** [comment]
> 但是如果，把车道线那4类的特征图加起来，再和背景类的特征图做softmax（等价于做了一个二分类分割模型，一类是所有车道线，一类是背景类），可以看到其实它是能很好的分割出车道线的（二分类）

作者你好，非常感谢你的开源贡献。你上面说的 4类车道线特征图相加，再和背景类softmax。指的是结果后处理？还是网络的一个模块，需要训练呢？
