### ISSUE TITLE
problem about grid GT

### ISSUE THREAD

**Issue by hitczr** [cfzd/Ultra-Fast-Lane-Detection#116]
作者你好：
    关于dataset.py中GT的生成我有一个疑问:
    在data/dataset.py的line102:  `col_sample = np.linspace(0, w - 1, num_cols)`
    是用于生成grid，然后根据x坐标计算GT对应索引的。但是np.linspace中有一个endpoint参数，默认为True。
    因此，如果按照上述写法，实际一个anchor只生成了grid_num-1个grid，而非grid_num个。而网络的输出的对应维度是grid_num+1。
    由于网络输出是回归到grid索引上的，所以在evaluation/eval_wrapper.py的line81中`lane = [int(round((loc + 0.5) * 1280.0 / (griding_num - 1))) if loc != griding_num else -2 for loc in out_i]`，只需要保证计算x坐标时也是用grid_num-1，与GT对应，就不有太大偏差。
     但是，这种情况下，输出的前grid_num列中的最后一列的概率就永远不会参与loss的计算，并且GT和ouput对应的grid区域实际是有一点横向偏移的。并且GT为grid_num-1列，而输出是grid_num+1列，这与论文的逻辑是不相符的。
     如有错误，欢迎指正。

谢谢

**Comment by cfzd** [comment]
@hitczr 
感谢指出问题！这段代码好像是有问题，我简单试了一下，会有少了一类的情况。

不过由于整个过程，不论是正向网格化，还是反向从网格化变为坐标，都是线性的过程，误差还算可控，而且这个误差会被平摊到其他所有网格上，所以可视化似乎看不出来存在问题。我会在下一次提交修复这个bug。
