### ISSUE TITLE
FileNotFoundErrorFileNotFoundError:     [Errno 2] No such file or directory: '/data2/***/Tusimple/train_gt.txt': with open(list_path, 'r') as f:[Errno 2] No such file or directory: '/data2/xiezixi/Tusimple/train_gt.txt'

### ISSUE THREAD

**Issue by XieZixiUSTC** [cfzd/Ultra-Fast-Lane-Detection#118]
FileNotFoundErrorFileNotFoundError:     [Errno 2] No such file or directory: '/data2/xiezixi/Tusimple/train_gt.txt': with open(list_path, 'r') as f:[Errno 2] No such file or directory: '/data2/xiezixi/Tusimple/train_gt.txt'
  The error shows above ,i can not find the train_gt.txt in the whole master.zip ,could you help me ,thanks!

**Comment by cfzd** [comment]
@XieZixiUSTC 
Please see `install.MD`

python scripts/convert_tusimple.py --root $TUSIMPLEROOT

**Comment by XieZixiUSTC** [comment]
thank you , i solved this problem,by the way, section 4 Data preparation in tusimple data in README , the subdir clips  do include clips in test set and train set, or only in train set

**Comment by cfzd** [comment]
@XieZixiUSTC 
It should contain both training set and testing set.
