### ISSUE TITLE
i got the wrong video with tusimple datasets, so i have a question, thanks for your help.

### ISSUE THREAD

**Issue by XYHYX5** [cfzd/Ultra-Fast-Lane-Detection#121]
I run the demo.py with tusimple datasets,but the video i got is wrong, it can't open, then i saw that you said the visualized video might look bad with tusimple datasets and you do not recommend doing this,so if i use culane datasets, could i get the wright video with lane markings like the vis.jpg in your project?

**Comment by cfzd** [comment]
@XYHYX5 
I think there might be a problem. If you run it correctly, you should be able to open the video. The video should just look **discontinuous**, but the video should be good. 

What's the size of your generated video?

**Comment by XYHYX5** [comment]
> @XYHYX5
> I think there might be a problem. If you run it correctly, you should be able to open the video. The video should just look **discontinuous**, but the video should be good.
> 
> What's the size of your generated video?

with tusimple datasets,I generated only 14 kb of video, there weren't any errors occurs during running of the code, but i dont know where the problem is,

**Comment by cfzd** [comment]
@XYHYX5 
Can you check the size of `vis` in this line?
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/bb673eb816e5c5356dcab02d72feb937fbb445b6/demo.py#L84

Is it  `(720, 1280, 3)`?

**Comment by XYHYX5** [comment]
oh god,i find the error,i forgot to alter the data root when i run the demo.py, the wright data root is test_set, thank you so much, you said the vis's size which reminded me to check the data root, thanks again
