### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Kaimingfan** [cfzd/Ultra-Fast-Lane-Detection#123]
作者你好，如果我想把输出的视频中的圆连成线，你有什么好的方法吗？如果仅仅是连接两个圆的话，在拐弯的地方效果不是很好。

**Comment by cfzd** [comment]
这个你把cv2.circle换成cv2.line不就好了吗。。。

**Comment by Kaimingfan** [comment]
这样在拐弯的时候和一些没有光照等特殊场景的时候效果不是很好，你有没有推荐的根据点拟合成曲线的方法来拟合这些点。

**Comment by Kaimingfan** [comment]
或者一些别的方法来使得效果更好。

**Comment by cfzd** [comment]
np.polyfit

**Comment by cfzd** [comment]
或者你为了展示效果的话，你可以试着做一些对车道线的跟踪、稳定。比如卡尔曼滤波之类的

**Comment by PengfeiMa** [comment]
使用bezier.Curve函数，将原来每组预测的点再多生成一些点再链接就会平滑很多，如果点数够多看起来就是线了

**Comment by Kaimingfan** [comment]
可以让我看一下你的代码吗？

> 使用bezier.Curve函数，将原来每组预测的点再多生成一些点再链接就会平滑很多，如果点数够多看起来就是线了

**Comment by PengfeiMa** [comment]
`
def plot_line(points):    

    points = np.array(points,dtype=int).T

    curve = bezier.Curve(points, degree=points.shape[1]-1)

    s_vals = np.linspace(0.0, 1.0, 100)   # 100 is the num of pionts

    data = curve.evaluate_multi(s_vals)

    data = tuple(data.T)

    return data
`
![image](https://user-images.githubusercontent.com/20807385/98337063-fe38d580-2042-11eb-823b-602739e69edf.png)

输入就是代码中的每组点，结合demo.py的调用，按楼上作者说的最后可以用cv2.circle换成cv2.line

**Comment by Kaimingfan** [comment]
十分感谢！

> `
> def plot_line(points):
> 
> ```
> points = np.array(points,dtype=int).T
> 
> curve = bezier.Curve(points, degree=points.shape[1]-1)
> 
> s_vals = np.linspace(0.0, 1.0, 100)   # 100 is the num of pionts
> 
> data = curve.evaluate_multi(s_vals)
> 
> data = tuple(data.T)
> 
> return data
> ```
> 
> `
> ![image](https://user-images.githubusercontent.com/20807385/98337063-fe38d580-2042-11eb-823b-602739e69edf.png)
> 
> 输入就是代码中的每组点，结合demo.py的调用，按楼上作者说的最后可以用cv2.circle换成cv2.line
