### ISSUE TITLE
Focal Loss isn't decreasing

### ISSUE THREAD

**Issue by damithkawshan** [cfzd/Ultra-Fast-Lane-Detection#125]
When I train your model using cuLane dataset, focal loss is oscillating around 2.5? what could be the reason for that? I used the orignal config file you provided in this repo with following changes:

sim_loss_w = 1
shp_loss_w  = 1
weight_decay = 4e-4

**Comment by cfzd** [comment]
@damithkawshan 
Can you first try with sim_loss_w=0 and shp_loss_w=0 to see if it decreases?

**Comment by damithkawshan** [comment]
Its work in that way. But that means for CULane you are not using the loss functions you introduced right? only thee focal loss is there.
