### ISSUE TITLE
The results of  table 3 in paper

### ISSUE THREAD

**Issue by fornote** [cfzd/Ultra-Fast-Lane-Detection#129]
Hello, thanks for your outstanding work. Could you have open the evaluation metrics code of **REG** and **REG Norm** in table 3 of paper.

**Comment by cfzd** [comment]
@fornote 
Basically, the methods of REG and REG Norm are not in the scope of our work. They are just used to verify the effectiveness of our method. So, I would not provide the source code of these experiments. But I can tell you how we implemented these methods.

The big idea is very simple: converting a classification network to a regression network.

So you have to:
- modify the dimension of the network:
  https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/model/model.py#L63
  make the `total_dim` equal to `num_cls_per_lane x num_of_lanes`, `num_gridding` is no longer needed.
- modify the data pipeline
  The original data pipeline is for classification, you need to modify it for regression. So, remove this line:
  https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L81
  Return the lane coordinate from `lane_pts` directly.
- modify the loss
  modify the losses in this function:
  https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/utils/factory.py#L28
  make the classification loss to regression loss like the L1 loss.

Then, you can train the regression network. But if you want to test the trained regression network, you might also need to:
- modify the evaluation pipeline.
  modify the functions:
  https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/evaluation/eval_wrapper.py#L64
  and
  https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/evaluation/eval_wrapper.py#L9

**Comment by Tianwei-She** [comment]
@cfzd Thanks for the detailed explanation! Just to confirm, the regression loss you used in REG and REG Norm experiments is L1 loss, right?

**Comment by fornote** [comment]
Thank you very much. I have another question that if you evaluated the REG method with the same way of CLS?

**Comment by cfzd** [comment]
@Tianwei-She 
Yes, I tried both L1 and L2 loss. The L1 loss is more stable. I think smoothL1 loss could also work.
@fornote 
Yes, they are evaluated in the same way. The only difference is the method itself, the evaluation is the same.

**Comment by hitczr** [comment]
hello,
   
    I have a question about Ultra-Fast Regression: how to express x_coordinate when lane don't exist?
    and which activation function did you choose?
    In my attempt, I express x = -1 when lane do not exist and choose Sigmoid function. And I got acc =92.98 on Tusimple Dataset. 

BR,
Max

**Comment by hitczr** [comment]
@cfzd 
Thanks for your reply. 
As you said, when use sigmoid, x can not be equal to -1, it would just close to 0 when inference. I also tried activate function such as tanh that range in [-1, 1].
I agree with you that classification-based method is more effective.
