### ISSUE TITLE
I changed the size to train your model, but the output is wired.

### ISSUE THREAD

**Issue by jajajajaja121** [cfzd/Ultra-Fast-Lane-Detection#130]
I changed the input size to 256*256 and change anchor to [108, 116, 125, 133, 142, 151, 160, 168, 177, 186, 195, 203, 212, 220, 229, 237, 246, 255], but when I test my model, the lane that predict by my model is really close to center like this:
![image](https://user-images.githubusercontent.com/34438597/99250140-2a740380-2846-11eb-9e28-9d22b617481b.png)
I change my hyper parameter according to this issue:https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/124

**Comment by cfzd** [comment]
@jajajajaja121 
The whole results seem correct, while they are shifted. Did you change the resolution here?
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/demo.py#L89

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> The whole results seem correct, while they are shifted. Did you change the resolution here?
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/demo.py#L89

yes, I have changed 800 and 200 to 256, by the way, should I change the griding_num? The lane seems to too short.

**Comment by cfzd** [comment]
@jajajajaja121 
I feel that the lane is shifted downwardly. Can you lift the lane by adding some constant? for example, 
```
ppp = (int(out_j[k, i] * col_sample_w * img_w / 800) - 1, int(img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1 ) - constant
```

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> I feel that the lane is shifted downwardly. Can you lift the lane by adding some constant? for example,
> 
> ```
> ppp = (int(out_j[k, i] * col_sample_w * img_w / 800) - 1, int(img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1 - constant ) 
> ```
> 
> By subtracting a `constant` in ` img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1`, the lane can be shifted upwardly.

Thanks, I will try.

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> I feel that the lane is shifted downwardly. Can you lift the lane by adding some constant? for example,
> 
> ```
> ppp = (int(out_j[k, i] * col_sample_w * img_w / 800) - 1, int(img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1 - constant ) 
> ```
> 
> By subtracting a `constant` in ` img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1`, the lane can be shifted upwardly.

Yes, your advise is useful, thanks a lot, but why the y value will tool small? Maybe my anchors are incorrect?

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> I feel that the lane is shifted downwardly. Can you lift the lane by adding some constant? for example,
> 
> ```
> ppp = (int(out_j[k, i] * col_sample_w * img_w / 800) - 1, int(img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1 - constant ) 
> ```
> 
> By subtracting a `constant` in ` img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1`, the lane can be shifted upwardly.

And I find if I just change the y axis, the lane may be little inclined, maybe some parameters are wrong?

**Comment by cfzd** [comment]
@jajajajaja121 
I think the problem is that the anchors you used in training and testing are not identical. So the results might mismatch.

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> I think the problem is that the anchors you used in training and testing are not identical. So the results might mismatch.

I have tried different anchor, but the result is also incorrect,

**Comment by cfzd** [comment]
@jajajajaja121 
It might be the problem here:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L115-L117
You can just remove this part and test.

**Comment by cfzd** [comment]
This method is a temporary fix. I will make a refactor soon to solve this problem.

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> It might be the problem here:
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L115-L117
> 
> 
> You can just remove this part and test.

You mean Just let sample_tmp=self.row_anchor? I have tried but it seems nothing have change.

**Comment by jajajajaja121** [comment]
> This method is a temporary fix. I will make a refactor soon to solve this problem.

OK, thanks a lot.

**Comment by cfzd** [comment]
@jajajajaja121 
Yes, `sample_tmp=self.row_anchor` and retrain you model. Then the test should work.

**Comment by jajajajaja121** [comment]
> @jajajajaja121
> Yes, `sample_tmp=self.row_anchor` and retrain you model. Then the test should work.

Ok, I will try, thanks

**Comment by aungriah** [comment]
> @jajajajaja121
> It might be the problem here:
> 
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L115-L117
> 
> 
> You can just remove this part and test.

Hello, I was wondering why there could be an error in the block of code above. As long as during training self.row_anchor is the same as the one provided in your code, it is correct, right? 

Otherwise, @jajajajaja121 did you train with sample_tmp=self.row_anchor (self.row_anchorr with the values adapted to your size) and obtained good test results?
