### ISSUE TITLE
When the car changes lane, the detection effect is not very good，

### ISSUE THREAD

**Issue by zhangchubing** [cfzd/Ultra-Fast-Lane-Detection#132]
When the car changes the lane, the detection effect is not very good, after the change of lane  is completed, it returns to normal. What should be the problem? 
![xx](https://user-images.githubusercontent.com/46444239/99615756-eefc5380-2a56-11eb-8a64-e4af7f813b28.png)

**Comment by cfzd** [comment]
@zhangchubing 
Please refer to #72 and #114.
