### ISSUE TITLE
python train.py configs/path_to_your_config

### ISSUE THREAD

**Issue by nolehuan** [cfzd/Ultra-Fast-Lane-Detection#134]
python train.py configs/path_to_your_config
训练的时候报错请问如何解决？
numpy.linalg.LinAlgError: Caught LinAlgError in DataLoader worker process 0.

data dataset.py
p = np.polyfit(valid_idx_half[:,0], valid_idx_half[:,1], deg = 1)
报错
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

**Comment by cfzd** [comment]
@nolehuan 
好像有两种可能，第一种是输入包含nan或者inf时，会报这个错。但我觉得这种不太可能，我没有遇到过这样的问题，其他人也没有提过类似的issue，你可以使用来验证：
```
isf = np.isfinite(valid_idx_half)
if not np.all(isf):
    print("nan or inf")
```
第二种好像是内存不足也会发生这样的问题。
