### ISSUE TITLE
怎样去训练自己的数据集

### ISSUE THREAD

**Issue by Ymec** [cfzd/Ultra-Fast-Lane-Detection#135]
大佬你好，我想训练自己的数据集，issue中已经有人说出来这个问题，我尝试了一下并没有成功，能具体说一下嘛，超级感谢！！

**Comment by cfzd** [comment]
@Ymec 
最简单的方法就是把你的数据集定义成一个和CULane一样标准的分割数据集，然后直接训练。或者如果你们标注的时候标的是点集形式的车道线的话，也可以按照Tusimple数据集那种格式，把车道点集全部写到一个json文件中。这种情况我们也提供了一个转换工具，可以直接转成可训练的模式。
