### ISSUE TITLE
I have run test.py (python test.py configs/culane.py --test_model path_to_culane_18.pth --test_work_dir ./tmp) .its showing this error

### ISSUE THREAD

**Issue by Amitkathayat** [cfzd/Ultra-Fast-Lane-Detection#137]
`File "test.py", line 48, in <module>     eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)   File "D:\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 138, in eval_lane     res = call_culane_eval(data_root, 'culane_eval_tmp', work_dir)   File "D:\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 229, in call_culane_eval     res_all['res_normal'] = read_helper(out0)   File "D:\Ultra-Fast-Lane-Detection\evaluation\eval_wrapper.py", line 167, in read_helper     lines = open(path, 'r').readlines()[1:] FileNotFoundError: [Errno 2] No such file or directory: './tmp\\txt\\out0_normal.txt'`

**Comment by cfzd** [comment]
@Amitkathayat 
Did you make the CUlane evaluator?

**Comment by Amitkathayat** [comment]
I did'nt make CUlane evaluator.

**Comment by cfzd** [comment]
@Amitkathayat 
As said in the `INSTALL.md`, you have to make it so you can evaluate on CULane.

**Comment by Amitkathayat** [comment]
ok I'll try. Thanks a lot.

**Comment by Amitkathayat** [comment]
Do I have to download visual studio to evaluate CUlane on windows?

**Comment by cfzd** [comment]
@Amitkathayat 
Not necessarily. You can make the evaluator using Cmake.
