### ISSUE TITLE
Scaling and large rotation as data preprocessing

### ISSUE THREAD

**Issue by aungriah** [cfzd/Ultra-Fast-Lane-Detection#140]
Hello, 

First of all, thank you very much for this repository, it is fantastic. I would really appreciate if you could help me with two things:

- I was wondering if you had trained the network with Scaling as an augmentation as well, since the default dataloader does not use it. (Is it not included because the performance was worse?)
- Additionally, when training on images that are rotated by absolute degrees higher than 6 (default case), the quality of the inference on my own dataset is reduced. Did you try with larger rotation angles that still resulted in good results?

Thank you!

**Comment by cfzd** [comment]
@aungriah 
I didn't try scaling for a simple reason: the sizes of images in Tusimple or CULane are all the same. I think there is no need for scaling. But I think if you add the Scaling, it still works. 

For the problem of degree, I manually increase the number of the degree from 0 and visualize the results. By 6, the images become too rotated for me. So I choose the degree of 6 as the max range limit. If the angle is too large, it might cause ambiguous results. For example, a **left-direction lane** might be rotated and becomes the **right-direction lane** using large rotation angles, but the label of this lane is still **left-direction lane**.
