### ISSUE TITLE
模型能不能输入一张图片来测试

### ISSUE THREAD

**Issue by MasterKID223** [cfzd/Ultra-Fast-Lane-Detection#142]
在test.py和demo.py中怎么只用一张图片进行测试？
python test.py configs/culane.py --test_model culane_18.pth --test_work_dir ./output
上面的命令是否可以指定一张图片

**Comment by cfzd** [comment]
test是用来评估结果的，如果你要测试一张图像的话，使用demo.py。把其中的数据集式的读取改成一张一张图片读就行了。

**Comment by MasterKID223** [comment]
> test是用来评估结果的，如果你要测试一张图像的话，使用demo.py。把其中的数据集式的读取改成一张一张图片读就行了。
好的，问题已经解决了，谢谢！
