### ISSUE TITLE
Question related to ego lane detection

### ISSUE THREAD

**Issue by xmba15** [cfzd/Ultra-Fast-Lane-Detection#144]
Hi @cfzd,
Is it OK to use the current network as it is to train detection of ego lane, in the scenes where lanes - other than ego lane, also exist?
Thank you very much.

**Comment by cfzd** [comment]
@xmba15 
You have two ways: 
- you can discard the output of the non-ego lanes
- you can make your dataset only contains the annotations of the ego lanes

**Comment by xmba15** [comment]
@cfzd thank you for the suggestion.
for the second idea, besides setting num_lanes to 2 as also mentioned in https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/141, is there anything else I need to take into consideration?

**Comment by cfzd** [comment]
@xmba15 
For the second method, besides setting `num_lanes` to 2, you also need to modify this line:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L122
For the CULane dataset, `num_lanes` is 4. The `lane_idx` in here is [1,2,3,4], which corresponds to the annotations of four lanes in CULane. If you want to make it only contains ego lanes, you need to modify the range of  `lane_idx`.

For example, on CULane, the ego lanes' indexes are 2 and 3, so you can make it like:
```
for lane_idx in [2,3]:
```
Then the ego lanes are preserved, and other lanes are discarded.

**Comment by xmba15** [comment]
@cfzd Thanks for the detailed instruction. I will give it a try.

**Comment by xmba15** [comment]
@cfzd To make the issue threads clean, I will close this topic for now. Thanks again for the help.
