### ISSUE TITLE
python speed_simple.py

### ISSUE THREAD

**Issue by cucula** [cfzd/Ultra-Fast-Lane-Detection#145]
Why are the results so different every time after “python speed_simple.py”? 
The fps index in the paper refers to “average fps”？
How do you measure the speed? 
Thank you for your answer.

**Comment by cfzd** [comment]
@cucula 

> Why are the results so different every time after “python speed_simple.py”?

As you can see in `speed_simple.py`, it is a program without any random input, so it should have the same behavior for different runnings. If your results are volatile, it might be some other problems, like PyTorch Conv method optimization, hardware quality, etc.

> The fps index in the paper refers to “average fps”？
How do you measure the speed?

I use the average fps as the program outputs.

**Comment by cucula** [comment]
thank you for your answer.
