### ISSUE TITLE
trained on other backbone

### ISSUE THREAD

**Issue by lucky-xu-1994** [cfzd/Ultra-Fast-Lane-Detection#148]
thank you for your great work! 
and there are few different backbones,like res18,res34,res50,res101......
have you trained on these backbones expect res18 and res34?
will the performance be better with deeper backbone?
thanks!

**Comment by cfzd** [comment]
@lucky-xu-1994 
I only tried res50, it would have better performance, but the speed is much slower, and the training costs much. So I didn't try other larger models.

**Comment by lucky-xu-1994** [comment]
> @lucky-xu-1994
> I only tried res50, it would have better performance, but the speed is much slower, and the training costs much. So I didn't try other larger models.

thanks a lot.
