### ISSUE TITLE
FcaNet: Frequency Channel Attention Networks

### ISSUE THREAD

**Issue by JiayiLy** [cfzd/Ultra-Fast-Lane-Detection#149]
Hi, I have read your new paper FcaNet (https://arxiv.org/pdf/2012.11879.pdf). And I'm trying to add it into ultra-fast-lane-detection project. I have a doubt that how to determine the args of get_dct_weights(). The code in your paper is as following:
![Screenshot from 2020-12-23 15-27-22](https://user-images.githubusercontent.com/16137282/102971007-86136a00-4533-11eb-8844-d2e7aec40f74.png)
Looking forward for your reply. Thank you.

**Comment by cfzd** [comment]
@JiayiLy 
Thanks for your comment. All the code and models of FcaNet will be released soon since the work is currently under review : )

If you want to try it by yourself, you can consider the code in Sec. 6.4 (Appendix) and the results in Fig. 4 of our paper. The FcaNet is easy to implement.

**Comment by JiayiLy** [comment]
@cfzd 
Hi, I have succeeded in adding the Frequency Channel Attention into my project. The performance gain is amazing. Thanks for your nice work again.

**Comment by zhy788** [comment]
> @cfzd
> Hi, I have succeeded in adding the Frequency Channel Attention into my project. The performance gain is amazing. Thanks for your nice work again. But I still have a question.
> The first three args of get_dct_weights function is width, height and channel of an input feature map. On the other hand, the get_dct_weights function is only for the initialization. So I could only add one fca layer in a specific position of cnn. How to add a few of fca layers in different positions at the same time?

Can you tell me how to inital the parment of '**fidx_u**' and '**fidx_v**'? Thank you.

**Comment by cfzd** [comment]
@zhy788
**fidx_u** and **fidx_v** are the indices of selected frequency components. According to Fig. 4 of our paper, we choose the Top-16 frequency components. In this way, **fidx_u** and **fidx_v** are the indices of the Top-16 frequency components.

**Comment by zhy788** [comment]
> @zhy788
> **fidx_u** and **fidx_v** are the indices of selected frequency components. According to Fig. 4 of our paper, we choose the Top-16 frequency components. In this way, **fidx_u** and **fidx_v** are the indices of the Top-16 frequency components.

so ,it can be set as **[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]**?I am sorry that I did  not read you paper  carefully,so I set as **Top-8**.
Hope I can get a better reslut of my semantic segmentaiton work  tomorrow. Thank you very much.

**Comment by cfzd** [comment]
@zhy788 
you can set it as fidx_u = [0,0,0,0,0,0,0,1,1,1,2,3,3,4,5,6] and fidx_v = [0,1,2,3,4,5,6,7,0,2,6,2,5,0,0,0].

**Comment by cucula** [comment]
hi。 @JiayiLy 。Can you share your method with us? How to  add the Frequency Channel Attention into this project?

**Comment by JiayiLy** [comment]
> > @cfzd
> > Hi, I have succeeded in adding the Frequency Channel Attention into my project. The performance gain is amazing. Thanks for your nice work again. But I still have a question.
> > The first three args of get_dct_weights function is width, height and channel of an input feature map. On the other hand, the get_dct_weights function is only for the initialization. So I could only add one fca layer in a specific position of cnn. How to add a few of fca layers in different positions at the same time?
> 
> Can you tell me how to inital the parameter of '**fidx_u**' and '**fidx_v**'? Thank you.

Sorry to be so late. I made a mistake. When I added fca to the network, I also made some other modifications. The performance gain was not only the fca's effect. And I made another contrast environment, the performance of fca is better than cbam in my task. But not too much.
