### ISSUE TITLE
 Does this method predicts lane category?

### ISSUE THREAD

**Issue by Epiphqny** [cfzd/Ultra-Fast-Lane-Detection#15]
Thanks for your method, I want to ask if this network predicts lane categories such as white dot, yellow and so on? Or the classification branch only predicts the lane id number from left to right?

**Comment by cfzd** [comment]
@Epiphqny 
Hi, for now, the method only predicts the location of lanes, but it is very easy to predict lane categories. You can attach a category classification branch for each lane. I think simple FC layers could work well.

**Comment by Epiphqny** [comment]
@cfzd Thanks for your reply, I will try it.

**Comment by cfzd** [comment]
@Epiphqny 
You can just treat the lane category prediction as a multi-task branch. In our work, the auxiliary segmentation is also treated as multi-task branch. So you can make another category classification branch as we do [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/2046b151db625c924bd3851303416fa66b3dbc64/model/model.py#L76-L83).

**Comment by Epiphqny** [comment]
@cfzd Ok, that's very useful!
