### ISSUE TITLE
模型能否转换成pt格式在c++中使用

### ISSUE THREAD

**Issue by vajDog** [cfzd/Ultra-Fast-Lane-Detection#151]

**Comment by 18576502363** [comment]
请问一下，我把该模型转换成了pt格式，打算在c++中使用，但是转换完之后并没有办法载入，这是为什么呢？

**Comment by 18576502363** [comment]
这个是转换成.pt格式的代码
![1608978081(1)](https://user-images.githubusercontent.com/48467791/103149734-3dfc7d80-47a7-11eb-91f0-6ec75f5149cf.jpg)
这个是在c++上调用的结果，
![281837a37e0793bc68c364447b0220c](https://user-images.githubusercontent.com/48467791/103149745-51a7e400-47a7-11eb-9ccd-e371c8e9d31d.png)

**Comment by 18576502363** [comment]
这个是转换成.pt格式的代码
![1608978081(1)](https://user-images.githubusercontent.com/48467791/103149781-b400e480-47a7-11eb-8b4e-acad7019c21e.jpg)
这个是在c++上调用的结果
![281837a37e0793bc68c364447b0220c](https://user-images.githubusercontent.com/48467791/103149789-caa73b80-47a7-11eb-988e-8b6ecf80be8a.png)

**Comment by cfzd** [comment]
@vajDog 
这个由于我没有转过，确实不知道是什么问题
