### ISSUE TITLE
finetune之后做evaluate，报错:lane size must be greater or equal to 2

### ISSUE THREAD

**Issue by Shirley-bht** [cfzd/Ultra-Fast-Lane-Detection#153]
#### lane_compare.cpp
```python
double LaneCompare::get_lane_similarity(const vector<Point2f> &lane1, const vector<Point2f> &lane2)
{
	if(lane1.size()<2 || lane2.size()<2)
	{
		cerr<<"lane size must be greater or equal to 2"<<endl;
		return 0;
	}
	Mat im1 = Mat::zeros(im_height, im_width, CV_8UC1);
	Mat im2 = Mat::zeros(im_height, im_width, CV_8UC1);
	// draw lines on im1 and im2
	vector<Point2f> p_interp1;
	vector<Point2f> p_interp2;
	if(lane1.size() == 2)
	{
		p_interp1 = lane1;
	}
	else
	{
		p_interp1 = splineSolver.splineInterpTimes(lane1, 50);
	}
```
这里的lane.size()是指什么?怎么解决这个问题？希望作者有时间可以帮忙看一下，万分感激!!!

**Comment by cfzd** [comment]
@Shirley-bht 
CULane 的评估工具的lane.size()的意思是一条线有几个点，因为两点构成一条直线，所以小于2的时候就会输出错误返回0的相似度，不过出现这个应该不会影响评估。我之前遇到这个问题一般有两种情况：
- 你是不是修改了`./evaluation/eval_wrapper.py`的代码，CULane的评估工具对于格式要求比较严格，格式不对有可能会这样。
- 第二种是预测结果非常差的情况下，也可能会出现这个问题

**Comment by Shirley-bht** [comment]
@cfzd 
首先非常感谢您的答复
* 是的，我有修改`./evaluation/eval_wrapper.py`的代码，因为我需要在我的数据集上做评估
* 应该不是预测结果差的问题，我把预测结果直接换成了真实标签，仍然出现这个问题
另外，lane.size()<2不是导致程序终止的最终原因，最终是因为`tp==0`,所以precision和recall均为0,导致无法计算Fmeasure.
##### 程序输出如下:
```
tp: 0 fp: 6 fn: 7
finished process file
precision: 0
recall: 0
Fmeasure: -nan
----------------------------------
test_res 0
Traceback (most recent call last):
  File "/tmp/pycharm_project_863/UFLD/test.py", line 56, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/tmp/pycharm_project_863/UFLD/evaluation/eval_wrapper.py", line 148, in eval_lane
    F = 2*P*R/(P + R)
ZeroDivisionError: float division by zero
Process finished with exit code 1
```
但是我不知道是不是因为lane.size()这里出错,所以导致`tp==0`.

**Comment by Shirley-bht** [comment]
@cfzd 
非常感谢您的回复，我仔细检查了以后发现确实是数据格式还有问题。于是重新处理了数据，解决了lane.size()的问题。
我还做了以下三个实验，并存在一个问题
* 当我用自己finetune后的模型去评估原始CULane的测试集时候，得到的结果非常差。但是用culane_18.pth去评估原始CULane测试集效果很好。
* 用finetune后的模型和culane_18.pth分别去评估了自己的测试集，得到的tp均为0。我的分辨率是1920*1200，在评估的时候我有将您的分辨率都替换成我的分辨率.
* 用finetune后的模型，在我的测试集上运行了demo.py，得到的可视化结果看起来还不错
#### 问题:不知道为什么在自己的测试集上评估不了?明明可视化结果还不错,可是评估的时候tp=0

**Comment by Shirley-bht** [comment]
问题已解决，好像是编译出了问题,谢谢作者的分享.

**Comment by zrr1991** [comment]
@Shirley-bht 您好，请问您如何用自己的数据微调了模型呢，只训练了后几层吗
