### ISSUE TITLE
使用cpu和cuda跑的fps都只有2-3hz

### ISSUE THREAD

**Issue by Hanyouyu** [cfzd/Ultra-Fast-Lane-Detection#156]
您好，我用的demo.py中的设置，将设置从cpu改到cuda上对检测速率上并没有提升，都只有2-3Hz，是有什么地方需要额外设置吗？
显卡是Geforce1650
我查看网络输出的张量都是在cuda中了

**Comment by Hanyouyu** [comment]
我把加载网络的代码写进了循环，每一次调用都加载了一次网络😀，问题已经解决了

**Comment by RoyZhDec** [comment]
> 我把加载网络的代码写进了循环，每一次调用都加载了一次网络😀，问题已经解决了

我改了demo文件，dataloader用来读入我自己的图片，3080的卡，fps也只有6-7左右。。。用cpu和用gpu速度都一样，而且我查看显存应该是占用了1.8G左右的显存的。。。而且我应该没有改他load网络的结构。。找不到原因。

**Comment by RoyZhDec** [comment]
如果只测out = net(imgs)这一句代码的话，确实是300+FPS。。。应该是可视化和写出图片（我没有写出视频，而是每帧图片写出到本地）比较耗时。
