### ISSUE TITLE
复现

### ISSUE THREAD

**Issue by luna9806** [cfzd/Ultra-Fast-Lane-Detection#157]
我这有一段行车记录仪记录的视频，想复现你demo中演示的那样，请问一下该怎么做。
我用您给的python demo.py configs/tusimple.py --test_model path_to_tusimple_18.pth的到底一个test.avi视频和您给的demo视频不一样。我想用我手里的视频复现出您demo的效果，不知该怎么做，希望能够得到您的回复。

**Comment by cfzd** [comment]
因为demo视频里的是CULane数据集可视化，你要复现demo视频你把config和模型都换成culane上的就行了。

至于测试你自己的视频，你可以参考`speed_real.py`中使用OpenCV从视频文件或者摄像头读取的代码，并将`demo.py`中从数据集读取的部分改成使用OpenCV读取即可。

PS 因为你的行车记录仪数据没有经过训练，因此直接使用其他数据集训练的模型进行预测可能效果会很差

**Comment by suyali** [comment]
@cfzd can you tell why the results maybe bad when use culane model to detect other dataset?

**Comment by cfzd** [comment]
@suyali This is a common problem (that's why we need study domain adaption) in the deep learning community. The CULane dataset might have different resolution, camera, and data distribution with your data, so the results might be bad.
