### ISSUE TITLE
run the test.py occur an error

### ISSUE THREAD

**Issue by illiad-tigerdhl** [cfzd/Ultra-Fast-Lane-Detection#158]
I run the test.py file and use the culane like this on windows, get the error, how can I fix it？
E:\project\gitProject\lanelinePrj\Ultra-Fast-Lane-Detection\Ultra-Fast-Lane-Detection>python test.py configs/culane.py --test_model .\weights\culane_18.pth --data_root E:\data\laneline\laneseg_label_w16  --test_work_dir E:\data\laneline\tmp
merge  data_root  config
merge  test_model  config
merge  test_work_dir  config
start testing...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.81s/it]
'.\evaluation\culane\evaluate' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

i just use one picture int the test.txt
![Dingtalk_20210119143837](https://user-images.githubusercontent.com/65475789/104997191-25108080-5a64-11eb-8e13-6baf3580204a.jpg)

**Comment by cfzd** [comment]
@illiad-tigerdhl 
It seems you don't have the evaluator. Please make the evaluator as the `INSTALL.md`
