### ISSUE TITLE
虚实线的检测

### ISSUE THREAD

**Issue by safehumeng** [cfzd/Ultra-Fast-Lane-Detection#159]
大佬您好，能问一下虚实线的区分有什么思路么

**Comment by cfzd** [comment]
@safehumeng 
这个我觉得给每条车道线加入一个分类branch就行了，分类虚实线应该不难。

**Comment by MengFanZe1** [comment]
> 大佬您好，能问一下虚实线的区分有什么思路么

您好，请问区分虚实线您目前有什么进展嘛？我目前也在做，还想和您沟通交流
