### ISSUE TITLE
关于其他类型轨道

### ISSUE THREAD

**Issue by zrr1991** [cfzd/Ultra-Fast-Lane-Detection#161]
作者您好，我的应用场景是列车轨道，我直接加载您的预训练模型所以检测不出来轨道

本人刚开始，水平有限，修改尺寸接口、重新训练等可能需要一个月甚至更长时间，所以想请问如果我最后在自己的火车轨道上训练模型可以检测吗，（算法可以检测任何形式的道路吗）如果可以我再研究如何修改。希望大神可以回复，谢谢

**Comment by cfzd** [comment]
@zrr1991 
这是一个通用算法，只要是线形的物体都可以检测。如果你的轨道是类似于车道线一样的分开的几条线，那肯定是可以的，但如果你的数据集中轨道是很密集，比如一张图中有几十条的话，我个人猜测可能效果不是很好。

**Comment by zrr1991** [comment]
非常感谢您的回复

关于自己的数据集我有两个问题，希望得到您的答复：
1、请问作者如果我标定自己的铁轨数据集有标记工具推荐吗；
2、自己的数据集标定，我必须标记成culane或者tusimple那种格式吗？

**Comment by cfzd** [comment]
@zrr1991 
我推荐你标注成分割类型的数据集，因为其实大部分车道线检测方法本身是基于分割的，还有就是虽然我们方法不是分割的，但是也原生支持分割数据集的读取和训练，做成分割的通用性好一点。

但有个问题需要注意，比如CULane等数据集，它不是二分类分割，而是多分类分割。也就是说每条线实际上是一个类别，而不是所有线是一个类别。而且CULane数据集分割时类别是严格和线条的语义关联的，比如它的第0类是背景，第1类一定是左左车道线，第2类是左车道线，第3类是右车道线，第4类是右右车道线。而且这些类别不会相互混淆（这很重要！），例如一条车道线是左左车道线，但是这张图中恰好没有左车道线，所以虽然看起来这条左左车道线是左边最靠近中心的线，但是它的类别依然是左左（类别是1），而不是左车道线（类别是0）。

**Comment by zrr1991** [comment]
作者您好，谢谢您的回复！不好意思，对于您的解答，我还有一些问题：
如果我直接标注成分割数据集，我是把每条轨道分别标注出来还是把轨道区域分割出来？
希望得到您的回复，谢谢

**Comment by zrr1991** [comment]
作者您好，谢谢您的回复！不好意思，对于您的解答，我还有一些问题：
1、如果我直接标注成分割数据集，我是把每条轨道分别标注出来还是把轨道区域分割出来？
2、或者采用的点集的形式，在铁轨上打点，按照您在  #135 说的方式


希望得到您的回复，谢谢

**Comment by cfzd** [comment]
@zrr1991 
我建议把每条轨道分别标注出来，这样不管用什么方法做，都比较容易。即使最后你的算法不是分割的，你也很容易通过简单的处理把单独标注的轨道处理出来。

**Comment by zrr1991** [comment]
好的，非常感谢
