### ISSUE TITLE
两个loss权重为0 resnet18训练精度达不到87，只有82 ，如果那两个loss权重为1 精度更差

### ISSUE THREAD

**Issue by joe807191330** [cfzd/Ultra-Fast-Lane-Detection#163]
请问是因为商业原因不能公布完整代码的原因，还是因为我训练有问题？

**Comment by cfzd** [comment]
@joe807191330 
我没太明白的意思，87和82是在哪个数据集上的什么指标啊？

**Comment by joe807191330** [comment]
论文里CUlane Normal Res18  87.7 
我复现的只有82 sim_loss_w = 0  shp_loss_w = 0 
sim_loss_w shp_loss_w 需要设置多少才能复现87.7的结果？

**Comment by joe807191330** [comment]
> @joe807191330
> 我没太明白你的意思，87和82是在哪个数据集上的什么指标啊？

论文里CUlane Normal Res18 87.7
我复现的只有82 sim_loss_w = 0 shp_loss_w = 0
sim_loss_w shp_loss_w 需要设置多少才能复现87.7的结果？

**Comment by cfzd** [comment]
@joe807191330 
你只需要把`configs/culane.py`里的`data_root`和`log_path`填好，什么都不用改直接运行`launch_training.sh`就可以了啊。
我提供的69.7的模型就是这样训出来的啊，还有人训出来69.9啊，比如你看这个issue #11

**Comment by joe807191330** [comment]
> @joe807191330
> 你只需要把`configs/culane.py`里的`data_root`和`log_path`填好，什么都不用改直接运行`launch_training.sh`就可以了啊。
> 我提供的69.7的模型就是这样训出来的啊，还有人训出来69.9啊，比如你看这个issue #11

我得到了最高精度了  奇怪为啥单GPU训练效果比多GPU效果好
