### ISSUE TITLE
test error：precision是0，recall是1

### ISSUE THREAD

**Issue by tangxin93** [cfzd/Ultra-Fast-Lane-Detection#164]
我建立了evaluator，并且得到了测试集的预测结果，使用的是culane数据集，但是我测试得到的结果是precision是0，recall是1，我使用demo.py对同样的测试集进行可视化，效果还不错。我看到原始的culane数据集里有lines.txt，这个是测试的时候提供的真实标注线的坐标嘛，我做数据集的时候没有得到这个，precision是0和这个有关吗？

**Comment by cfzd** [comment]
@tangxin93 
是的，那些lines.txt就是测试集上的标注结果，因为你没有这个所以评估结果为0。 CULane其实把他的标注分为了两类，训练集上直接提供分割图，但在测试集上实际上是用这些lines.txt存储的点集。
