### ISSUE TITLE
关于修改resize尺寸后的model.py修改

### ISSUE THREAD

**Issue by MengFanZe1** [cfzd/Ultra-Fast-Lane-Detection#165]
Ultra-Fast-Lane-Detection/model/model.py
 self.cls = torch.nn.Sequential( 
     torch.nn.Linear(1800, 2048), 
     torch.nn.ReLU(), 
     torch.nn.Linear(2048, self.total_dim), 
 ) 
您好，想问一下，我resize到了（360， 640），此处的torch.nn.Linear(1800, 2048)应该怎样修改啊

**Comment by hitczr** [comment]
resnet出来的是原图的1/32， 作者的(288, 800)出来是(9, 25)，作者还做了一次self.pool，出来的c=8。所以1800=9×25×8=h×w×c。你用对应的h×w×c代替1800就可以了，不过你这个360不是32的倍数，可能需要修改下。

**Comment by MengFanZe1** [comment]
谢谢您的回答，理解了
