### ISSUE TITLE
检测出的车道线 点数很少

### ISSUE THREAD

**Issue by lanelanedetect** [cfzd/Ultra-Fast-Lane-Detection#166]
您好，我意图做航拍图像中的车道线检测，很感谢您这篇论文提供的思路与方法。
我目前已经成功训练了自己的culane格式数据集，效果还好，但识别出的点数太少，如下图所示，进一步会影响我拟合车道线的准确度。

![image](https://user-images.githubusercontent.com/78520799/106841414-0a354180-66dd-11eb-9660-0cb91a2a61c3.png)

我尝试了 修改cls_num_per_lane为30，anchor为culane_row_anchor = [4, 14, 24, 33, 43, 53, 63, 72, 82, 92, 102, 111, 121, 131, 141, 150,160, 170, 180, 189, 199, 209, 219, 228, 238, 248, 258, 267, 277, 287]，以及resize后的尺寸为288×512（原图为1920×1080），效果均未有改善，不知问题出在哪里？或是否仍有需改动之处？
望您的答复！

**Comment by lanelanedetect** [comment]
图片见如下链接：[检测效果图](https://blog.csdn.net/mengfanze1/article/details/113634209)

**Comment by cfzd** [comment]
@lanelanedetect 
1. 可以先检查网络的输出大小。网络输出的大小应该是`batch_size x (griding_num+1) x cls_num_per_lane x num_lanes`，确认输出的`cls_num_per_lane `是不是30.
2. 如果输出的`cls_num_per_lane`确实是30，可以查看一下输出是不是包含很多“no lane”的case。如果大多数输出都不是"no lane"，但是你画出来点很少的话那可能就是画图代码有bug，只画出了一部分点。如果大部分确实是“no lane”的case，那就要考虑是不是提供的label有问题。
3. 如果是label有问题，可以调试一下`_get_index`这个函数，看是不是从数据中读取了正确的label
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/dataset.py#L112

**Comment by ycdhqzhiai** [comment]
@lanelanedetect 您好，麻烦问下修改为288×512之后，你推理耗时多少啊

**Comment by lanelanedetect** [comment]
> @lanelanedetect 您好，麻烦问下修改为288×512之后，你推理耗时多少啊

单帧图片0.03-0.04s左右吧

**Comment by ycdhqzhiai** [comment]
> > @lanelanedetect 您好，麻烦问下修改为288×512之后，你推理耗时多少啊
> 
> 单帧图片0.03-0.04s左右吧

是什么平台啊，CUP还是GPU啊

**Comment by lanelanedetect** [comment]
> > > @lanelanedetect 您好，麻烦问下修改为288×512之后，你推理耗时多少啊
> > 
> > 
> > 单帧图片0.03-0.04s左右吧
> 
> 是什么平台啊，CUP还是GPU啊
GPU
