### ISSUE TITLE
在Tusimple数据集上用resnet18和34训练的结果都达不到论文上的实验结果，低约0.15%

### ISSUE THREAD

**Issue by axiaoxiaobai** [cfzd/Ultra-Fast-Lane-Detection#169]

**Comment by cfzd** [comment]
我在readme中提供的那个模型就是使用这个仓库中的代码训练的。运行以下代码应该会得到一样的效果：
```
python train.py configs/tusimple.py
```
注：请不要使用多卡训练，似乎大batch size会导致性能下降

**Comment by axiaoxiaobai** [comment]
> 
> 
> 我在readme中提供的那个模型就是使用这个仓库中的代码训练的。运行以下代码应该会得到一样的效果：
> 
> ```
> python train.py configs/tusimple.py
> ```
> 
> 注：请不要使用多卡训练，似乎大batch size会导致性能下降
您好，我重新训练了一下，环境是pytorch1.7，cuda10.1。用resnet18为主干网络，使用的命令是python train.py configs/tusimple.py，训练100个epoch。我从第81-99训练出来的模型中选择最好的一个，发现最高的指标是95.79%，请问这是在合理范围之内的嘛？
@cfzd

**Comment by cfzd** [comment]
@axiaoxiaobai 
应该是合理的吧，我在readme中提供的那个模型就是这样训出来的，不知道为什么你的会低一点。
