### ISSUE TITLE
关于测试自己的视频

### ISSUE THREAD

**Issue by ylc2580** [cfzd/Ultra-Fast-Lane-Detection#17]
你好，我用您提供的demo.py测试时候出现：
Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 288, 800] instead
请问这可能是什么问题呢，该如何解决呢？比较小白，请指教，谢谢了。代码如下：

`
import torch, os, cv2
from model.model import parsingNet
from utils.common import merge_config
from utils.dist_utils import dist_print
import torch
import scipy.special, tqdm
import numpy as np
import torchvision.transforms as transforms
from data.dataset import LaneTestDataset

if __name__ == "__main__":
    torch.backends.cudnn.benchmark = True
    args, cfg = merge_config()
    dist_print('start testing...')
    assert cfg.backbone in ['18','34','50','101','152','50next','101next','50wide','101wide']

    if cfg.dataset == 'CULane':
        cls_num_per_lane = 18
    elif cfg.dataset == 'Tusimple':
        cls_num_per_lane = 56
    else:
        raise NotImplementedError

    net = parsingNet(pretrained = False, backbone=cfg.backbone,cls_dim = (cfg.griding_num+1,cls_num_per_lane,4),
                    use_aux=False).cuda() # we dont need auxiliary segmentation in testing

    state_dict = torch.load(cfg.test_model, map_location='cpu')['model']
    compatible_state_dict = {}
    for k, v in state_dict.items():
        if 'module.' in k:
            compatible_state_dict[k[7:]] = v
        else:
            compatible_state_dict[k] = v

    net.load_state_dict(compatible_state_dict, strict=False)
    net.eval()

    img_transforms = transforms.Compose([
        transforms.Resize((288, 800)),
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ])

    cap = cv2.VideoCapture("0000.mp4")
    frame = cap.read()
    fourcc = cv2.VideoWriter_fourcc(*'MJPG')
    vout = cv2.VideoWriter(str(111)+'.avi', fourcc , 30.0, (1280,720))
    from PIL import Image
    print('加载cuda是否成功：',torch.cuda.is_available())
    while 1:
        rval,frame = cap.read()
        if rval == False:
            break
        cv2.imwrite("ssss.jpg",frame)
        img_ = Image.open("ssss.jpg")

        imgs = img_transforms(img_)
        imgs = imgs.cuda()
        with torch.no_grad():
            out = net(imgs)

        col_sample = np.linspace(0, 800 - 1, cfg.griding_num)
        col_sample_w = col_sample[1] - col_sample[0]

        out_j = out[0].data.cpu().numpy()
        out_j = out_j[:, ::-1, :]
        prob = scipy.special.softmax(out_j[:-1, :, :], axis=0)
        idx = np.arange(cfg.griding_num) + 1
        idx = idx.reshape(-1, 1, 1)
        loc = np.sum(prob * idx, axis=0)
        out_j = np.argmax(out_j, axis=0)
        loc[out_j == cfg.griding_num] = 0
        out_j = loc

        # import pdb; pdb.set_trace()
        # vis = cv2.imread(os.path.join(cfg.data_root,names[0]))
        for i in range(out_j.shape[1]):
            if np.sum(out_j[:, i] != 0) > 2:
                for k in range(out_j.shape[0]):
                    if out_j[k, i] > 0:
                        ppp = (int(out_j[k, i] * col_sample_w * 1280 / 800) - 1, int(720 - k * 20) - 1)
                        cv2.circle(img_,ppp,5,(0,255,0),-1)
        vout.write(img_)
        
    vout.release()
`

**Comment by cfzd** [comment]
@ylc2580 
Hi, if you want to test on your own video, you have to do three things.
1. Prepare your data
2. Prepare the network
3. Visualize the results

Step 2 and 3 are already done in the `demo.py`. You can find step 2 in [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/e270afaab92358e6b4e4cdd1157eecb318494029/demo.py#L26-L38) and step 3 in [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/e270afaab92358e6b4e4cdd1157eecb318494029/demo.py#L59-L80). 

The only thing you need to do is to prepare the data for your own video and it is also simple.
- Read data
- Normalize data
- Send it to the network
For reading data, you can use OpenCV or other tools to read the video frame by frame. Then transform the data type of the frame to the PIL Image object, and normalize it with the [transforms](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/e270afaab92358e6b4e4cdd1157eecb318494029/demo.py#L40). You will get a torch tensor after the normalization, you can call `.cuda()` and send it to the network.

**Comment by ylc2580** [comment]
> @ylc2580
> Hi, if you want to test on your own video, you have to do three things.
> 
> 1. Prepare your data
> 2. Prepare the network
> 3. Visualize the results
> 
> Step 2 and 3 are already done in the `demo.py`. You can find step 2 in [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/e270afaab92358e6b4e4cdd1157eecb318494029/demo.py#L26-L38) and step 3 in [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/e270afaab92358e6b4e4cdd1157eecb318494029/demo.py#L59-L80).
> 
> The only thing you need to do is to prepare the data for your own video and it is also simple.
> 
> * Read data
> * Normalize data
> * Send it to the network
>   For reading data, you can use OpenCV or other tools to read the video frame by frame. Then transform the data type of the frame to the PIL Image object, and normalize it with the [transforms](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/e270afaab92358e6b4e4cdd1157eecb318494029/demo.py#L40). You will get a torch tensor after the normalization, you can call `.cuda()` and send it to the network.

你好，可能没刷新，没看到您的回复，我刚才重新更新了提问，您能看下吗？不太清楚为什么会报维度不匹配，麻烦了

**Comment by cfzd** [comment]
@ylc2580
The default input format for a network is **batched**, i.e. if you have an image with a size of `channels x height x width`, it should be reshaped to `1 x channels x height x width`. In your case, you can achieve this by:
```
imgs = img_transforms(img_)
imgs = imgs.view(1, *imgs.shape)
imgs = imgs.cuda()
```

Also, I noted the way you transform an OpenCV image to PIL image is:
```
cv2.imwrite("ssss.jpg",frame)
img_ = Image.open("ssss.jpg")
```
It is very slow due to disk IO, you can try 
```
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_ = Image.fromarray(img)
```

Last, I want to remind you that the model is trained on the CULane dataset. It might perform poorly on your own video if the domain gap between your video and CULane is too large.

**Comment by ylc2580** [comment]
非常感谢您的回复，以下图片是我用您的提示后的脚本进行测试的结果，感觉这个视角和您在YouTube上的演示demo视角是接近的（我的测试视频分辨率为1080p和720p），所以我的理解，模型在新的数据上效果会有下降，但实际的效果感觉很差，是否是我在这边测试的代码里面相关参数设置错误呢？还是其他什么问题呢？望指教。


我的代码如下：


import&nbsp;torch,&nbsp;os,&nbsp;cv2
from&nbsp;model.model&nbsp;import&nbsp;parsingNet
from&nbsp;utils.common&nbsp;import&nbsp;merge_config
from&nbsp;utils.dist_utils&nbsp;import&nbsp;dist_print
import&nbsp;torch
import&nbsp;scipy.special,&nbsp;tqdm
import&nbsp;numpy&nbsp;as&nbsp;np
import&nbsp;torchvision.transforms&nbsp;as&nbsp;transforms
from&nbsp;data.dataset&nbsp;import&nbsp;LaneTestDataset



if&nbsp;__name__&nbsp;==&nbsp;"__main__":
&nbsp;&nbsp;&nbsp;&nbsp;torch.backends.cudnn.benchmark&nbsp;=&nbsp;True
&nbsp;&nbsp;&nbsp;&nbsp;args,&nbsp;cfg&nbsp;=&nbsp;merge_config()
&nbsp;&nbsp;&nbsp;&nbsp;dist_print('start&nbsp;testing...')
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;cfg.backbone&nbsp;in&nbsp;['18','34','50','101','152','50next','101next','50wide','101wide']

&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;cfg.dataset&nbsp;==&nbsp;'CULane':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls_num_per_lane&nbsp;=&nbsp;18
&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;cfg.dataset&nbsp;==&nbsp;'Tusimple':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls_num_per_lane&nbsp;=&nbsp;56
&nbsp;&nbsp;&nbsp;&nbsp;else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;NotImplementedError

&nbsp;&nbsp;&nbsp;&nbsp;net&nbsp;=&nbsp;parsingNet(pretrained&nbsp;=&nbsp;False,&nbsp;backbone=cfg.backbone,cls_dim&nbsp;=&nbsp;(cfg.griding_num+1,cls_num_per_lane,4),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;use_aux=False).cuda()&nbsp;#&nbsp;we&nbsp;dont&nbsp;need&nbsp;auxiliary&nbsp;segmentation&nbsp;in&nbsp;testing

&nbsp;&nbsp;&nbsp;&nbsp;state_dict&nbsp;=&nbsp;torch.load(cfg.test_model,&nbsp;map_location='cpu')['model']
&nbsp;&nbsp;&nbsp;&nbsp;compatible_state_dict&nbsp;=&nbsp;{}
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;k,&nbsp;v&nbsp;in&nbsp;state_dict.items():
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;'module.'&nbsp;in&nbsp;k:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compatible_state_dict[k[7:]]&nbsp;=&nbsp;v
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compatible_state_dict[k]&nbsp;=&nbsp;v

&nbsp;&nbsp;&nbsp;&nbsp;net.load_state_dict(compatible_state_dict,&nbsp;strict=False)
&nbsp;&nbsp;&nbsp;&nbsp;net.eval()

&nbsp;&nbsp;&nbsp;&nbsp;img_transforms&nbsp;=&nbsp;transforms.Compose([
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transforms.Resize((288,&nbsp;800)),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transforms.ToTensor(),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transforms.Normalize((0.485,&nbsp;0.456,&nbsp;0.406),&nbsp;(0.229,&nbsp;0.224,&nbsp;0.225)),
&nbsp;&nbsp;&nbsp;&nbsp;])

&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;cap&nbsp;=&nbsp;cv2.VideoCapture("0028.mp4")
&nbsp;&nbsp;&nbsp;&nbsp;fourcc&nbsp;=&nbsp;cv2.VideoWriter_fourcc(*'MJPG')
&nbsp;&nbsp;&nbsp;&nbsp;vout&nbsp;=&nbsp;cv2.VideoWriter(str(111)+'.avi',&nbsp;fourcc&nbsp;,&nbsp;30.0,&nbsp;(int(cap.get(3)),int(cap.get(4))))

&nbsp;&nbsp;&nbsp;&nbsp;print("w&nbsp;=&nbsp;{},h&nbsp;=&nbsp;{}".format(cap.get(3),cap.get(4)))

&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;PIL&nbsp;import&nbsp;Image




&nbsp;&nbsp;&nbsp;&nbsp;print('加载cuda是否成功：',torch.cuda.is_available())
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;1:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rval,frame&nbsp;=&nbsp;cap.read()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;rval&nbsp;==&nbsp;False:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;cv2.imwrite("ssss.jpg",frame)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;img_&nbsp;=&nbsp;Image.open("ssss.jpg")

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img&nbsp;&nbsp;=&nbsp;cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img_&nbsp;=&nbsp;Image.fromarray(img)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imgs&nbsp;=&nbsp;img_transforms(img_)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imgs&nbsp;=&nbsp;imgs.unsqueeze(0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imgs&nbsp;=&nbsp;imgs.cuda()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with&nbsp;torch.no_grad():
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out&nbsp;=&nbsp;net(imgs)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;col_sample&nbsp;=&nbsp;np.linspace(0,&nbsp;800&nbsp;-&nbsp;1,&nbsp;cfg.griding_num)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;col_sample_w&nbsp;=&nbsp;col_sample[1]&nbsp;-&nbsp;col_sample[0]


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out_j&nbsp;=&nbsp;out[0].data.cpu().numpy()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out_j&nbsp;=&nbsp;out_j[:,&nbsp;::-1,&nbsp;:]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prob&nbsp;=&nbsp;scipy.special.softmax(out_j[:-1,&nbsp;:,&nbsp;:],&nbsp;axis=0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;idx&nbsp;=&nbsp;np.arange(cfg.griding_num)&nbsp;+&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;idx&nbsp;=&nbsp;idx.reshape(-1,&nbsp;1,&nbsp;1)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loc&nbsp;=&nbsp;np.sum(prob&nbsp;*&nbsp;idx,&nbsp;axis=0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out_j&nbsp;=&nbsp;np.argmax(out_j,&nbsp;axis=0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loc[out_j&nbsp;==&nbsp;cfg.griding_num]&nbsp;=&nbsp;0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out_j&nbsp;=&nbsp;loc

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;import&nbsp;pdb;&nbsp;pdb.set_trace()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;vis&nbsp;=&nbsp;cv2.imread(os.path.join(cfg.data_root,names[0]))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(out_j.shape[1]):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;np.sum(out_j[:,&nbsp;i]&nbsp;!=&nbsp;0)&nbsp;&gt;&nbsp;2:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;k&nbsp;in&nbsp;range(out_j.shape[0]):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;out_j[k,&nbsp;i]&nbsp;&gt;&nbsp;0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ppp&nbsp;=&nbsp;(int(out_j[k,&nbsp;i]&nbsp;*&nbsp;col_sample_w&nbsp;*&nbsp;cap.get(3)&nbsp;/&nbsp;800)&nbsp;-&nbsp;1,&nbsp;int(cap.get(4)&nbsp;-&nbsp;k&nbsp;*&nbsp;20)&nbsp;-&nbsp;1)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cv2.circle(frame,ppp,5,(0,255,0),-1)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vout.write(frame)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;vout.release()


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cfzd"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午3:52
收件人:&nbsp;"cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;;
抄送:&nbsp;"403658190"<403658190@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cfzd/Ultra-Fast-Lane-Detection] 关于测试自己的视频 (#17)





 
@ylc2580
 The default input format for a network is batched, i.e. if you have an image with a size of channels x height x width, it should be reshaped to 1 x channels x height x width. In your case, you can achieve this by:
 imgs = img_transforms(img_) imgs = imgs.view(1, *imgs.shape) imgs = imgs.cuda()  
Also, I noted the way you transform an OpenCV image to PIL image is:
 cv2.imwrite("ssss.jpg",frame) img_ = Image.open("ssss.jpg")  
It is very slow due to disk IO, you can try
 img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) img_ = Image.fromarray(img)  
Last, I want to remind you that the model is trained on the CULane dataset. It might perform poorly on your own video if the domain gap between your video and CULane is too large.

**Comment by cfzd** [comment]
@ylc2580 
As mentioned above, the performance might be poor due to the domain gap. The domain gap comes from many aspects, not only the viewpoint of the camera. It's a common problem in deep learning methods. 

There two ways of solving the problem. The first way is style transfer. The second way is to fine-tune the model on your data. For style transfer, you can refer to [this paper](https://arxiv.org/abs/1905.04354).

**Comment by ylc2580** [comment]
好的，了解了，非常感谢回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cfzd"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午4:40
收件人:&nbsp;"cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;;
抄送:&nbsp;"403658190"<403658190@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cfzd/Ultra-Fast-Lane-Detection] 关于测试自己的视频 (#17)





 
@ylc2580
 As mentioned above, the performance might be poor due to the domain gap. The domain gap comes from many aspects, not only the viewpoint of the camera. It's a common problem in deep learning methods.
 
There two ways of solving the problem. The first way is style transfer. The second way is to fine-tune the model on your data. For style transfer, you can refer to this paper.

**Comment by whyygug** [comment]
@ylc2580 
你好，你有没有试过先把1080p的图像剪裁成culane的分辨率再输入网络？（不是resize）剪裁的时候让道路的消失点坐标与culane中道路消失点的位置大致相同，输出的结果也在剪裁后的图像上显示，也许效果会好一些？

**Comment by ylc2580** [comment]
> @ylc2580
> 你好，你有没有试过先把1080p的图像剪裁成culane的分辨率再输入网络？（不是resize）剪裁的时候让道路的消失点坐标与culane中道路消失点的位置大致相同，输出的结果也在剪裁后的图像上显示，也许效果会好一些？

你好，
（1）请问你这边有过尝试吗？效果怎么样呢？
（2）论文还没细看，不清楚有没有关系，我觉得可以试一下，后面会将测试效果写出来
-.-

**Comment by whyygug** [comment]
> @ylc2580
> 你好，你有没有试过先把1080p的图像剪裁成culane的分辨率再输入网络？（不是resize）剪裁的时候让道路的消失点坐标与culane中道路消失点的位置大致相同，输出的结果也在剪裁后的图像上显示，也许效果会好一些？
> 
> 你好，
> （1）请问你这边有过尝试吗？效果怎么样呢？
> （2）论文还没细看，不清楚有没有关系，我觉得可以试一下，后面会将测试效果写出来
> -.-
@ylc2580 
你好，我暂时没有试过，但是我感觉这样应该有改善，因为culane的分辨率是1640×590的，假如输入是1920×1080的话，结果肯定会有偏差。

**Comment by ylc2580** [comment]
嗯嗯，有道理，虽然视角一样，但是分辨率不同，输入到作者的模型分辨率，图像的压缩导致的变形也是不一样的，作者的里面涉及的一些方法就不能适用了。
现有的方法要么zai作者的模型上训一个自己的，要么你说的那种方式尝试一下，到这种方式很难保证两种数据一致，只能看可以改善到什么情况了。
👀

---原始邮件---
发件人: "whyygug"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 晚上6:11
收件人: "cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ylc2580"<403658190@qq.com&gt;;
主题: Re: [cfzd/Ultra-Fast-Lane-Detection] 关于测试自己的视频 (#17)




  
@ylc2580
 你好，你有没有试过先把1080p的图像剪裁成culane的分辨率再输入网络？（不是resize）剪裁的时候让道路的消失点坐标与culane中道路消失点的位置大致相同，输出的结果也在剪裁后的图像上显示，也许效果会好一些？
 
你好，
 （1）请问你这边有过尝试吗？效果怎么样呢？
 （2）论文还没细看，不清楚有没有关系，我觉得可以试一下，后面会将测试效果写出来
 -.-
 @ylc2580
 你好，我暂时没有试过，但是我感觉这样应该有改善，因为culane的分辨率是1640×590的，假如输入是1920×1080的话，结果肯定会有偏差。

**Comment by ylc2580** [comment]
> > @ylc2580
> > 你好，你有没有试过先把1080p的图像剪裁成culane的分辨率再输入网络？（不是resize）剪裁的时候让道路的消失点坐标与culane中道路消失点的位置大致相同，输出的结果也在剪裁后的图像上显示，也许效果会好一些？
> > 你好，
> > （1）请问你这边有过尝试吗？效果怎么样呢？
> > （2）论文还没细看，不清楚有没有关系，我觉得可以试一下，后面会将测试效果写出来
> > -.-
> > @ylc2580
> > 你好，我暂时没有试过，但是我感觉这样应该有改善，因为culane的分辨率是1640×590的，假如输入是1920×1080的话，结果肯定会有偏差。

测试了，如果将1080p的图像按照frame = frame[490:1080,0:1640,:]进行裁剪，效果基本可以使用。
但按照1080p图像和1640x590的比例，1080p的图像与其同尺度应该为1920x923，然后进行裁剪，效果不行。
所以应该是：完全相同尺度的裁剪可用，裁剪为同比例的不能使用。可能因为里面的车道线拟合函数吧。具体看一下论文了

**Comment by longzeyilang** [comment]
@ylc2580 我把culane数据集进行中间裁剪，裁剪成1280*590，然后进行模型训练，效果很差。那个损失relation_loss一直降不下来
