### ISSUE TITLE
about the pretrained model

### ISSUE THREAD

**Issue by YZY-stack** [cfzd/Ultra-Fast-Lane-Detection#170]
thank u for doing a really amazing job and it helps me a lot, but i have a question about the model.

after training my own dataset by using resnet18, i try to run the demo, but there is  a error: 

size mismatch for cls.2.weight: copying a param with shape torch.Size([11312, 2048]) from checkpoint, the shape in current model is torch.Size([22624, 2048]).
        size mismatch for cls.2.bias: copying a param with shape torch.Size([11312]) from checkpoint, the shape in current model is torch.Size([22624]).

any suggestion will help me, thank u so much!!

**Comment by cfzd** [comment]
@YZY-stack 
Does it seem the input size is not the same?

**Comment by Etshhh** [comment]
HI @YZY-stack I'm facing the same issue, if you did solve it please share how you did.
