### ISSUE TITLE
如何测试自己的图片数据？

### ISSUE THREAD

**Issue by zsffuture** [cfzd/Ultra-Fast-Lane-Detection#174]
把您的代码跑起来了，目前只跑了Tusimple数据集，
Accuracy 0.9581707233576312
FP 0.19051042415528396
FN 0.03918044572250176
还是正常，但是现在我想测试自己的数据，如何测试呢？

**Comment by cfzd** [comment]
@zsffuture 
你的数据集是分割形式的吗？如果是和CULane类似的分割数据集，只要仿照CULane数据集生产一个list文件，里面包含数据集中所有图像和标注就可以了。如果只是测试的话，只要包含图像的list就可以了。

**Comment by zsffuture** [comment]
嗯嗯，谢谢，已经解决了，我发现最新的车道线检测的文章是LSTR: Lane Shape Prediction with Transformers，本来打算使用这个的，但是研究发现，他的方法针对复杂场景的适应性不好，而且官方没给出CULane数据集的测试，我只是进行了Tusimple数据集的测试，这个数据集的测试的结果和 您的差不多，您的方法对复杂性场景更好点，因此打算深入研究你的方法。但是如果输入新的数据集，例如电子警察拍摄的车道线其识别效果很差，我先研究源码，然后尝试修改一下看看
