### ISSUE TITLE
在哪里可以关闭 CUDA 呢？

### ISSUE THREAD

**Issue by Sino-Snack** [cfzd/Ultra-Fast-Lane-Detection#177]
我想在 Mac 上跑一下效果，Mac 不支持 CUDA，请问要在哪里关闭 CUDA 呢？

**Comment by cfzd** [comment]
@Sino-Snack 
只需要把所有的`.cuda()`函数调用删掉就行了，比如在
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/test.py#L30
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/train.py#L20
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/train.py#L25
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/train.py#L116
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/evaluation/eval_wrapper.py#L57
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/evaluation/eval_wrapper.py#L91

除此之外，一些cuda初始化代码也可以删掉，比如：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/train.py#L106-L108

**Comment by Sino-Snack** [comment]
好的，谢谢。
