### ISSUE TITLE
KeyError: 'Fmeasure'

### ISSUE THREAD

**Issue by ypqhappy** [cfzd/Ultra-Fast-Lane-Detection#178]
你好，在执行test.py 的过程中出现“KeyError: 'Fmeasure'”这个报错，demo.py已经跑通，这个问题是OpenCV的问题或者是其他哪里的问题呢？

![image](https://user-images.githubusercontent.com/49770521/109900702-c2510c80-7cd2-11eb-83c4-f40441e23f37.png)

**Comment by ypqhappy** [comment]
这个问题还是出在evaluate.exe这里，一定要成功并且中途不报小错误的情况下生成，否则即使生成了，那也是无法运行的。我的问题是出在OpenCV的环境配置上面。供大家参考。

**Comment by zhwqwerf** [comment]
> 你好，在执行test.py 的过程中出现“KeyError: 'Fmeasure'”这个报错，demo.py已经跑通，这个问题是OpenCV的问题或者是其他哪里的问题呢？
> 
> ![image](https://user-images.githubusercontent.com/49770521/109900702-c2510c80-7cd2-11eb-83c4-f40441e23f37.png)

你好 这个问题您最终是怎么解决的呢
