### ISSUE TITLE
如何测试模型运行速度

### ISSUE THREAD

**Issue by NeilKuo** [cfzd/Ultra-Fast-Lane-Detection#179]
你好
训练完模型后该如何测试模型的fps？
另外在调整模型的参数训练后得到了以下结果

res_normal 0.888906
res_crowd 0.673952
res_night 0.644375
res_noline 0.399136
res_shadow 0.591758
res_arrow 0.842241
res_hlight 0.560075
res_curve 0.564745
res_cross 0.0
0.6964698552995975

可以看到在normal,crowd,night,arrow类别中精度有提升
但在其他类别略有降低
且在cross类别中无法测试出精度
请问是什么原因导致？

**Comment by cfzd** [comment]
@NeilKuo 
测试fps的话，可以参考`speed_simple.py`和`speed_real.py`这些代码。

Cross这个类别是斑马线，CULane的数据集评估的时候认为如果有斑马线的话就不需要检测出车道线了，如果检测出车道线一律认为是误检，所以cross这一类的F1永远都会是0（因为没有正样本，fp永远为0）。因此，CULane数据集评估cross这一类的话只看false positive，并且fp越小越好，这个你可以在评估代码的输出中找到。或者在你的`test_work_dir`目录下的`txt`文件夹中有每个类别的评估结果。

**Comment by NeilKuo** [comment]
@cfzd 
感谢回复
在运行`speed_real.py`代码有以下的错误

`[ WARN:0] global /tmp/pip-req-build-7m_g9lbm/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "speed_real.py", line 150, in <module>
    test_practical_without_readtime()
  File "speed_real.py", line 28, in test_practical_without_readtime
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-7m_g9lbm/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

**Comment by cfzd** [comment]
@NeilKuo 
如报错所说：`can't open camera by index`. 你应该是没有摄像头或者摄像头序号不对。

**Comment by NeilKuo** [comment]
谢谢您的回覆，已可正常运行。
