### ISSUE TITLE
loss coefficients in paper does not match configs in codes

### ISSUE THREAD

**Issue by yvanwy** [cfzd/Ultra-Fast-Lane-Detection#18]
Hi,
I found loss coefficients in paper all set to 1, but in codes, both in culane.py and tusimple.py, why shp_loss_w all set to 0?

**Comment by cfzd** [comment]
@yvanwy 
Hi, please refer to [this issue](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/8)  : )

**Comment by yvanwy** [comment]
Thanks!
