### ISSUE TITLE
区分虚实线

### ISSUE THREAD

**Issue by MengFanZe1** [cfzd/Ultra-Fast-Lane-Detection#181]
您好，您提到想要区分虚实线，给每条车道线加入一个分类branch就可以。具体应该怎么操作还是不太清楚，可否有进一步的指导。初步接触，还望您的答复

**Comment by cfzd** [comment]
@MengFanZe1 
我们的分类模型是：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/model/model.py#L60-L64
你可以简单的这样实现：
```
self.solid_dash_cls = torch.nn.Linear(1800, 4)
```
然后使用bceloss就可以训练了。

**Comment by ycdhqzhiai** [comment]
@cfzd 如果每条车道线有多个类别(虚实、白黄等组合)、一张图上多条车道线，那这种情况分类模型最后怎么写呢？
