### ISSUE TITLE
怎样得到的这个anchor

### ISSUE THREAD

**Issue by ycdhqzhiai** [cfzd/Ultra-Fast-Lane-Detection#183]
@cfzd 您好，请教下constant.py里面的anchor是怎么得到的，如果CULane检测18个点，不是每个点间隔10个像素吗？为什么有的间隔10个像素，有的间隔9个像素
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/data/constant.py#L11

**Comment by cfzd** [comment]
@ycdhqzhiai 
在CULane的作者的评估代码中，他们是这样定义anchor的：

https://github.com/XingangPan/SCNN/blob/fc09fa5435e6818da4e9ba7c4b4881ab26093c8c/tools/prob2lines/main.m#L73

他们的y坐标，也就是`uint16(590-(m-1)*20)-1`算出来是`[589, 569, 549, 529, 509, 489, 469, 449, 429, 409, 389, 369, 349, 329, 309, 289, 269, 249]`, 把这些anchor resize到288的图像高，再做取整操作得到这个`culane_row_anchor `了。

**Comment by ycdhqzhiai** [comment]
@cfzd 谢谢！！！
