### ISSUE TITLE
Do not know"python scripts/convert_tusimple.py --root $TUSIMPLEROOT     # this will generate segmentations and two list files: train_gt.txt and test.txt"

### ISSUE THREAD

**Issue by litingjiejie** [cfzd/Ultra-Fast-Lane-Detection#185]
FileNotFoundError: [Errno 2] No such file or directory: 'TUSIMPLEROOT\\label_data_0601.json'

**Comment by cfzd** [comment]
@litingjiejie 
TUSIMPLEROOT means the path of your tusimple dataset. Do not simply copy it, replace it with your dataset path.

**Comment by 5wmy5** [comment]
> FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'TUSIMPLEROOT\label_data_0601.请问你解决了吗
