### ISSUE TITLE
what is the reason when the line is abnormal bending

### ISSUE THREAD

**Issue by suyali** [cfzd/Ultra-Fast-Lane-Detection#186]
![image](https://user-images.githubusercontent.com/33011961/111098779-24392e00-857f-11eb-9fbe-5d3bc4286f98.png)

**Comment by cfzd** [comment]
@suyali 
Please provide more information about this picture. What's the data you used for this picture? Which model do you use? How do you visualize this picture?

**Comment by suyali** [comment]
I trained your model with mobilenet backbone, using culane data. The picture is from my car's  dvr . the picture's  shape is 1920*1080, and I cut it with shape 1640*590--center cut (Is it useful when the img shape is not consistant with training data?)

**Comment by cfzd** [comment]
@suyali 
I think it should be a problem of cross dataset testing. If the testing domain is not the same as the training domain, the performance is not guaranteed.
