### ISSUE TITLE
How to solve this problem about test?

### ISSUE THREAD

**Issue by EungGo** [cfzd/Ultra-Fast-Lane-Detection#187]
I read Install.md, but I don't solve the problem about installing CULane evalutaion tools.

When I run 'make', errors occured!

In file included from src/spline.cpp:3:0:
include/spline.hpp:6:10: fatal error: opencv2/core.hpp: 그런 파일이나 디렉터리가 없습니다
 #include <opencv2/core.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:39: recipe for target 'build/src/spline.o' failed
make: *** [build/src/spline.o] Error 1

Thank you for reading my issue, and I want to run test.py with my weigth files.

**Comment by cfzd** [comment]
@EungGo 
It says the `opencv2/core.hpp` file is not found. where do you install the OpenCV? Can you find the `core.hpp` file in your machine?

**Comment by EungGo** [comment]
![스크린샷, 2021-03-19 16-25-18](https://user-images.githubusercontent.com/80038814/111745305-c0409d80-88cf-11eb-9ea9-a6f3babd3e6c.png)
I find the core.hpp file.

**Comment by EungGo** [comment]
I solved this problem. Thank you

**Comment by dongdong2061** [comment]
@EungGo Hello, I also encountered this problem, how did you solve this problem?
