### ISSUE TITLE
如何增多 最大可检测车道线数目

### ISSUE THREAD

**Issue by MengFanZe1** [cfzd/Ultra-Fast-Lane-Detection#188]
您好！目前可以最多检测4条车道线，由于我做的是无人机场景下的车道线检测，我还想请教一下，如何改变代码中的相关参数，可以检测到比如5条车道线。

**Comment by cfzd** [comment]
@MengFanZe1 
修改`config`文件中的`num_lanes`即可。

**Comment by hwang12345** [comment]
@cfzd 使用场景如果只检测一条车道线，使用自己标注的数据集进行训练，应该对程序怎么调整？求教
