### ISSUE TITLE
如何实时读取摄像头的视频？如何修改demo.py中的代码？希望可以得到您的解答，多谢

### ISSUE THREAD

**Issue by luna9806** [cfzd/Ultra-Fast-Lane-Detection#189]

**Comment by cfzd** [comment]
@luna9806 
如果要读取摄像头的视频的话，推荐你参考`speed_real.py`中的代码，这个支持读摄像头或者直接读取视频。但是这个代码中没有可视化的部分，可以结合`demo.py`中的代码。
