### ISSUE TITLE
Culane dataset testing errors

### ISSUE THREAD

**Issue by zwyzwy** [cfzd/Ultra-Fast-Lane-Detection#19]
when I test the culane datasets, the errors occurs as below:

python test.py configs/culane.py --test_model ./checkpoint/culane_18.pth --test_work_dir ./tmp                                                          
merge  test_model  config                                                                             
merge  test_work_dir  config                                                                          
start testing...                                                                                      
100%|█████████████████████████████████████████████████████████████| 4335/4335 [04:43<00:00, 15.29it/s]
./evaluate -a /home/zwy/data/culane/ -d ./tmp/culane_eval_tmp/ -i /home/zwy/data/culane/ -l /home/zwy/data/culane/list/test_split/test0_normal.txt -w 30 -t 0.5 -c 1640 -r 590 -f 1 -o ./tmp/txt/out0_normal.txt                                                                                                  
sh: 1: ./evaluation/culane/evaluate: not found                                                        
./evaluate -a /home/zwy/data/culane/ -d ./tmp/culane_eval_tmp/ -i /home/zwy/data/culane/ -l /home/zwy/data/culane/list/test_split/test1_crowd.txt -w 30 -t 0.5 -c 1640 -r 590 -f 1 -o ./tmp/txt/out1_crowd.txt                                                                                                    
sh: 1: ./evaluation/culane/evaluate: not found                                                        
./evaluate -a /home/zwy/data/culane/ -d ./tmp/culane_eval_tmp/ -i /home/zwy/data/culane/ -l /home/zwy/
data/culane/list/test_split/test2_hlight.txt -w 30 -t 0.5 -c 1640 -r 590 -f 1 -o ./tmp/txt/out2_hlight.txt                                                                                                  
sh: 1: ./evaluation/culane/evaluate: not found                                                        
sh: 1: ./evaluation/culane/evaluate: not found                                                        
sh: 1: ./evaluation/culane/evaluate: not found                                                        
sh: 1: ./evaluation/culane/evaluate: not found                                                        
sh: 1: ./evaluation/culane/evaluate: not found                                                        
sh: 1: ./evaluation/culane/evaluate: not found                                                        
sh: 1: ./evaluation/culane/evaluate: not found                                                        
Traceback (most recent call last):                                                                    
  File "test.py", line 45, in <module>                                                                
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/home/zwy/codes/ultra_lane/evaluation/eval_wrapper.py", line 137, in eval_lane                
    res = call_culane_eval(data_root, 'culane_eval_tmp', work_dir)                                    
  File "/home/zwy/codes/ultra_lane/evaluation/eval_wrapper.py", line 225, in call_culane_eval         
    res_all['res_normal'] = read_helper(out0)                                                         
  File "/home/zwy/codes/ultra_lane/evaluation/eval_wrapper.py", line 166, in read_helper              
    lines = open(path, 'r').readlines()[1:]                                                           
FileNotFoundError: [Errno 2] No such file or directory: './tmp/txt/out0_normal.txt'

**Comment by zwyzwy** [comment]
Do I need to compile the code in ./evaluation/culane/ ? but it seems unable to compile this code. How to deal this problem?

**Comment by cfzd** [comment]
@zwyzwy 
Hi, you need to first compile the evaluation code to test on CULane. You can follow the installation steps in README,  `install` section.
