### ISSUE TITLE
A question about the fps and runtimes.

### ISSUE THREAD

**Issue by cedricgsh** [cfzd/Ultra-Fast-Lane-Detection#190]
Thanks for your great code.  But I have a question about your paper.  Did you use `speed_simple.py` to test the fps and runtime in your paper, or `speed_real.py` ?
@cfzd

**Comment by cfzd** [comment]
@cedricgsh 
I use `speed_simple.py`. In fact, the results of these two codes are the same.

**Comment by cedricgsh** [comment]
Thank you.
