### ISSUE TITLE
Why is my test image this result?  What is the minimum number of images required to train my dataset?

### ISSUE THREAD

**Issue by bodhi-tree01** [cfzd/Ultra-Fast-Lane-Detection#191]
Why is my test image this result?  What is the minimum number of images required to train my dataset?
![00240_predict](https://user-images.githubusercontent.com/62365914/112270455-abd81880-8cb4-11eb-8203-03c0645086a1.jpg)

**Comment by cfzd** [comment]
@bodhi-tree01 
Since your test image is not in the domain that our model was trained in, the bad detection results make sense. If you want to train a model based on your images, I think 1000+ images should work. Of course, the more, the better.

**Comment by bodhi-tree01** [comment]
> @bodhi-tree01
> Since your test image is not in the domain that our model was trained in, the bad detection results make sense. If you want to train a model based on your images, I think 1000+ images should work. Of course, the more, the better.

Thanks

**Comment by bodhi-tree01** [comment]
> @bodhi-tree01
> Since your test image is not in the domain that our model was trained in, the bad detection results make sense. If you want to train a model based on your images, I think 1000+ images should work. Of course, the more, the better.

Thank you for your reply. Thank you very much.
If the marked data are rails, can the algorithm detect tracks in the image?
After reading your paper, I think it should be OK.But I still hope to get your answer.

**Comment by cfzd** [comment]
@bodhi-tree01 
Of course, it could detect. I don't think there are differences between detecting rails and lanes.
