### ISSUE TITLE
训练灰度图

### ISSUE THREAD

**Issue by dsadfe** [cfzd/Ultra-Fast-Lane-Detection#192]
请问可以训练灰度图吗，可以的话具体需要改哪些模块的代码，期待您的答复，谢谢！！

**Comment by cfzd** [comment]
@dsadfe 
可以的，只需要改resnet的conv1就行了，从3通道输入改为1通道。或者你直接把你的灰度图重复3次，组成一个3通道的图就不需要该模型了。
