### ISSUE TITLE
Which dataset should I download?

### ISSUE THREAD

**Issue by SiyangXie** [cfzd/Ultra-Fast-Lane-Detection#195]
Hello, 

I'm not sure which dataset to download as the install.md did not specify. Please advise.
![screenshot](https://user-images.githubusercontent.com/13971749/114371894-8bb0c080-9bb3-11eb-99f2-4f3efb2d02ac.png)

Thanks,
Siyang

**Comment by cfzd** [comment]
@SiyangXie 
All the files should be downloaded and unzipped to the same folder.

**Comment by SiyangXie** [comment]
> @SiyangXie
> All the files should be downloaded and unzipped to the same folder.

Looks like annotations_new.tar.gz has the same unzipped files as driver_23_30frame.tar.gz, driver_161_90frame.tar.gz and driver_182_30frame.tar.gz?

**Comment by cfzd** [comment]
@SiyangXie 
As the download page says:
> Note: The raw annotations (not segmentation labels) for training&val set are not correct before April 16th 2018. To update to the right version, you could either download "annotations_new.tar.gz" and cover the original annotation files or download the training&val set again.

I think you can just ignore it.
