### ISSUE TITLE
Developing ROS Wrapper

### ISSUE THREAD

**Issue by Etshhh** [cfzd/Ultra-Fast-Lane-Detection#197]
Hi, I'm trying to develop a ROS wrapper for lane. My problem is with there are a lot of files and I'm not sure what to take. Can you guide me as in where to get started?
Thanks for your time and patience and for sharing this great work!

**Comment by Etshhh** [comment]
This was maybe too specific. Responding with how I can test this on photos of my own is enough. Which functions exactly should I run to evaluate my own photos. Again, thank you.

**Comment by cfzd** [comment]
If you want to test one image, I think you can see `demo.py` and `speed_real.py`.  `demo.py` generates the video from a dataset, while `speed_real.py` provides the input and preprocessing code from camera or video(Very similar to the image if you use OpenCV). You can combine these functions to predict from one single image.

**Comment by Etshhh** [comment]
That's very helpful. But should I remove all the CULane/Tusimple parts from the demo.py since I'm using my own image or should I apply one of them?

**Comment by bruce-almon** [comment]
What I did is to convert the model to an ONNX file
Then follow the demo.py to write the img callback, inference etc.
