### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Huangdebo** [cfzd/Ultra-Fast-Lane-Detection#198]
你好：
        参考您论文中的超参数（adam; cos decay; lr=0.0004; λ,α,β=1, epochs=50, bs=32）来训练 culane 数据，效果始终达不到论文中的效果，而且车道线的预测都是偏直线，在车道线弯曲部分也预测成直线。请问这是什么原因呢？
        在ParsingRelationDis loss 中，“for i in range(0,num_rows // 2)” 限制了车道线上部分（可能为弯道）为直线，不应该是限制下部分（“for i in range(num_rows // 2， num_rows)”）为直线才对吗？

**Comment by cfzd** [comment]
@Huangdebo 
因为开源的代码是换了实现方式重构过的，所以参数会有不一样的情况。使用我们目前代码中给的默认参数应该是可以训出来的。

关于这个loss的话，确实是想把下半部分约束的越直越好。这个可能是一个bug，我们会再检查一下这个的实现有没有问题。

**Comment by Huangdebo** [comment]
> @Huangdebo
> 因为开源的代码是换了实现方式重构过的，所以参数会有不一样的情况。使用我们目前代码中给的默认参数应该是可以训出来的。
> 
> 关于这个loss的话，确实是想把下半部分约束的越直越好。这个可能是一个bug，我们会再检查一下这个的实现有没有问题。

（1）使用了代码默认的超参数之后，的确可以正常收敛
（2）ParsingRelationDis loss 我改成 “for i in range(num_rows // 2， num_rows-1)” 来限制下半部分为直线，权重设成0.2-1.0之间；ParsingRelationLoss 的权重设成 0，训练效果也好，弯曲车道线的预测也是偏直线。目前也没找到原因
