### ISSUE TITLE
训练top1 top2的疑问

### ISSUE THREAD

**Issue by MengFanZe1** [cfzd/Ultra-Fast-Lane-Detection#199]
想请问，训练时候的top1、top2、top3表示什么含义?

**Comment by cfzd** [comment]
@MengFanZe1 
以一个n分类问题为例，假如标注结果为x，那么top就计算预测结果恰好等于x的准确率，也就是一般意义上的accuracy。
top2的话就是如果预测为x-1, x, x+1这三者的任意一个，也算对。
top3就是在[x-2,x+2]这个范围内算对的情况下的准确率。
不过上述计算top2或者top3的时候，是不计入"no lane"这种情况的，也就是说"no lane"永远计算top1。
