### ISSUE TITLE
测试精度问题

### ISSUE THREAD

**Issue by casialixiaodong** [cfzd/Ultra-Fast-Lane-Detection#200]
您好，我将您的模型和代码应用在了自己的数据集上，已经将格式改成了CULane的格式，但是想通过evaluation来评估一下test的精度。请问是不是不能直接用culane evaluation，因为这个工具是只针对culane数据集中的数据是吗？谢谢

**Comment by casialixiaodong** [comment]
我应该把自己生成的test_gt放在数据文件夹的哪个地方呢？谢谢

**Comment by cfzd** [comment]
@casialixiaodong 
CULane数据集其实是有两套数据格式的，一套就是我们熟知的分割图。但是它的test集不是以分割图存储的，test集是直接存储的车道线点集，也就是你可以在数据集中看到的各种`xxxxx.lines.txt`文件。如果你的数据也有这种类似的信息，那就可以直接使用CULane的evaluation来评估。

**Comment by casialixiaodong** [comment]
所以如果没有这样的点图的话就需要自己写test来评估分割对应的精度是吗？

**Comment by cfzd** [comment]
@casialixiaodong 
因为你已经有了分割标注，我觉得把分割图转换为`lines.txt`也不是很困难，只需要找到所有行anchor上的坐标，然后存到txt里就好了。

**Comment by casialixiaodong** [comment]
非常感谢您的及时回复和耐心解答，我现在已经配置好了evaluation工具，但是我作为gt的对应txt应该放在哪个文件夹下呢？CULANEROOT/list/test_split/testx_xxx.txt中仅有图片的路径，您可以和我说一下坐标的txt路径可以在哪里找到吗？

**Comment by cfzd** [comment]
@casialixiaodong 
CULane默认会把和图片对应的`lines.txt`放在一起，所以你可以通过这样的方式得到、设置标注的路径：
```
img_path = 'xxxxxxx.jpg'
label_path = img_path.replace('jpg','lines.txt') # xxxxxxx.jpg --> xxxxxxx.lines.txt
```
