### ISSUE TITLE
error about testing model

### ISSUE THREAD

**Issue by YZY-stack** [cfzd/Ultra-Fast-Lane-Detection#201]
I want to test the acc of the model I've trained. And what I do is as follow:

"mkdir ../tmp"
" python3 test.py configs/tusimple.py --test_work_dir ../tmp/ --test_model tusimple_18.pth"

but there is the problem: 
start testing...
100%|████████████████████████████████████████████████████████████████| 348/348 [02:09<00:00,  2.69it/s]
Accuracy 0.0
FP 0.0
FN 1.0

you can see here the "Acc" and "FP" got zero, I don't know why.

**Comment by YZY-stack** [comment]
Besides, the content of test_set is basically like that:  clips, label_data_0601.json,  readme.md,  test.txt.

**Comment by cfzd** [comment]
@YZY-stack 
I think you can first check the `tusimple_eval_tmp.txt` in your `test_work_dir`. If this file looks good, I think you might need to debug this function:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/evaluation/tusimple/lane.py#L56-L90

**Comment by YZY-stack** [comment]
Thank u so much!
