### ISSUE TITLE
Is it possible to train on customized dataset?

### ISSUE THREAD

**Issue by SiyangXie** [cfzd/Ultra-Fast-Lane-Detection#202]
Hi, I'm thinking of using this project on a railway tracks detection task. Not sure how it would perform, but I'd say it's pretty similar to lane detection right...? Is there any tutorial for customized training? 

Thanks

**Comment by cfzd** [comment]
@SiyangXie 
I think it would work on the railway dataset as well. For training on the customized dataset, I think the most simple way is to convert the customized dataset into the CULane format. Otherwise, a customized data loader for the dataset is needed.
