### ISSUE TITLE
Accuracy Top K

### ISSUE THREAD

**Issue by SHsix** [cfzd/Ultra-Fast-Lane-Detection#204]
Hello,  First of all, thank you for sharing the good code.
I have a question. I wonder about following code.
![스크린샷 2021-04-29 오후 6 30 04](https://user-images.githubusercontent.com/59632846/116530591-2bdb4900-a919-11eb-8c76-8cf982556023.png)

If we regard background_clss = 200, predict = 200, target =198, k = 3.
background_idx = (predict == self.background_classes) + (target == self.background_classes)  will be True because predict is 200

The difference of predict and target is 2 which is less than k. 
So I think it should increase the number of top5_correct. But doesn't because It is 'False' after logical_not.

So I suggest that substitute & for + on this code "background_idx = (predict == self.background_classes) + (target == self.background_classes) "

If it is wrong, please let me know.
Thank you again for your hard work!

**Comment by cfzd** [comment]
@SHsix 
Thanks for your comments on this subtle problem! I think your point is correct, and I will make an improvement on this.
