### ISSUE TITLE
请问一下，为什么pytorch模型，每次同样的输入，输出结果会不一样

### ISSUE THREAD

**Issue by hungrybreadyosoro** [cfzd/Ultra-Fast-Lane-Detection#205]
准备验证pytorch模型和我自己转的onnx模型结果时，发现同样输入尺寸为（1，3，288，800）的元素全为1的矩阵时，pytorch的结果并不固定，想请问一下是什么原因？

import os.path as osp

import numpy as np
import onnx
import onnxruntime as ort
import torch
import torchvision
from model.model import parsingNet
import cv2

test_arr = np.ones((3, 288, 800)).astype(np.float32)
test_arr = torch.from_numpy(test_arr).float().unsqueeze(0)
print(test_arr.size())

MODELPATH = "F:\\github\\Ultra-Fast-Lane-Detection\\Ultra-Fast-Lane-Detection\\model\\culane_18.pth"
model = parsingNet(pretrained = False, backbone='18', cls_dim = (201, 18, 4), use_aux=False).cuda()
state_dict = torch.load(MODELPATH, map_location='cpu')['model']

model = model.eval()
print('pytorch result:', model(test_arr.cuda()))

**Comment by cfzd** [comment]
@hungrybreadyosoro 
似乎这一段代码中只是把`state_dict`从文件中读取出来了，但是并没有把参数更新到网络中。应该是少了这一句:
```
model.load_state_dict(state_dict, strict=False)
```

**Comment by cfzd** [comment]
@hungrybreadyosoro 
上述的代码还是有问题，还需要考虑pytorch多卡训练会自动给model加上“module”这个前缀，正确的载入参数的代码可以参考这一段：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/test.py#L32-L40

**Comment by hungrybreadyosoro** [comment]
是这样的，感谢您的回答！
