### ISSUE TITLE
关于anchor疑问

### ISSUE THREAD

**Issue by NeilKuo** [cfzd/Ultra-Fast-Lane-Detection#206]
看了#183 后有个疑问
anchor数量是否可增加或减少?
例如CULane检测18个点，可否增加为两倍?
可能检测准确率会增加?

**Comment by cfzd** [comment]
@NeilKuo 
Anchor数目是可以修改的。至于增加或者减少后准确率会不会增加这个我不太清楚，我唯一做过一次实验在更密的anchor上结果似乎没有大的变化。

**Comment by NeilKuo** [comment]
@cfzd 
感谢回复，关于您在＃183中提到：
`他们的y坐标，也就是uint16(590-(m-1)*20)-1算出来是[589, 569, 549, 529, 509, 489, 469, 449, 429, 409, 389, 369, 349, 329, 309, 289, 269, 249], 把这些anchor resize到288的图像高，再做取整操作得到这个culane_row_anchor 了。

请问`uint16（590-（m-1）* 20）-1`中的m是指什么？

**Comment by cfzd** [comment]
@NeilKuo 
m就是一个循环变量：
```
>>> [590-(m-1)* 20-1 for m in range(1,19)]
[589, 569, 549, 529, 509, 489, 469, 449, 429, 409, 389, 369, 349, 329, 309, 289, 269, 249]
```

**Comment by NeilKuo** [comment]
@cfzd 
感谢解惑，受益良多。

**Comment by cfzd** [comment]
@NeilKuo 
这个是因为python是0-based的索引，所以高度为288时，要索引最后一行的话index是287.

**Comment by NeilKuo** [comment]
您好，请问在tusimple中anchor也是利用
`uint16（590-（m-1）* 20）-1`
得到的吗?

**Comment by cfzd** [comment]
@NeilKuo 
图森上的anchor不是这样的得到的，图森在定义测试方法的时候就已经定义了一套anchor，就是它数据集中的那些json文件里面的`h_samples`

**Comment by NeilKuo** [comment]
@cfzd 
谢谢您的回覆
