### ISSUE TITLE
想要对culane_18这个模型做微调的话，请问应该修改哪些代码？

### ISSUE THREAD

**Issue by hungrybreadyosoro** [cfzd/Ultra-Fast-Lane-Detection#207]
我现在想在culane_18.pth的基础上做一点微调，已经标注好了一批数据，请问除了将culane.py中的finetune那一行改为自己的模型路径以外，还应该做哪些修改？谢谢！

**Comment by hungrybreadyosoro** [comment]
谢谢你的回答！另外还有个疑问，我标注的图像尺寸是1920*1080的尺寸，所以标注的坐标点有的会超过原culane数据集的尺寸（即1640*590），在进行训练的时候需要如何处理尺寸问题呢？还望赐教！

**Comment by cfzd** [comment]
@hungrybreadyosoro 
如果在训练的时候保持288x800的默认尺寸的话，应该没有别的需要修改的地方了。但是做eval的时候需要改一下输出坐标的缩放：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/evaluation/eval_wrapper.py#L43-L44
需要把这个地方的1640和590换成1920及1080.

**Comment by hungrybreadyosoro** [comment]
`
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.use_aux)
  File "train.py", line 67, in train
    loss = calc_loss(loss_dict, results, logger, global_step)
  File "train.py", line 46, in calc_loss
    loss_cur = loss_dict['op'][i](*datas)
  File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\github\Ultra-Fast-Lane-Detection\Ultra-Fast-Lane-Detection\utils\loss.py", line 37, in forward
    loss = self.nll(log_score, labels)
  File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\modules\loss.py", line 211, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss2d_forward
`
这个报错提到target数据类型错误，请教一下导致这个的原因会是什么呢？

**Comment by hungrybreadyosoro** [comment]
> 
> 
> Traceback (most recent call last):
> File "train.py", line 151, in
> train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.use_aux)
> File "train.py", line 67, in train
> loss = calc_loss(loss_dict, results, logger, global_step)
> File "train.py", line 46, in calc_loss
> loss_cur = loss_dict['op'][i](*datas)
> File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "F:\github\Ultra-Fast-Lane-Detection\Ultra-Fast-Lane-Detection\utils\loss.py", line 37, in forward
> loss = self.nll(log_score, labels)
> File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\modules\loss.py", line 211, in forward
> return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
> File "D:\miniconda3\envs\lane-det\lib\site-packages\torch\nn\functional.py", line 2220, in nll_loss
> ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss2d_forward
> 
> 这个报错提到target数据类型错误，请教一下导致这个的原因会是什么呢？

参阅之前的issue后，这个问题已经解决了，但报出了这个错误：
RuntimeError: CUDA error: device-side assert triggered
检查了一下，发现我的cls_label是全都是200，这种情况可以做些什么改动呢？

**Comment by hungrybreadyosoro** [comment]
发现自己debug时加的语句不太对，对于culane的griding num应该是200，加入的debug语句应该是：
assert torch.all(results['cls_label'] <201), results['cls_label'][  results['cls_label'] >= 201  ]  
assert torch.all(results['seg_label'] <5), results['seg_label'][  results['seg_label'] >= 5]
由此得出的错误报告如下，依然是有超过label的标注：
Traceback (most recent call last):
  File "train.py", line 152, in <module>
    train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.use_aux)
  File "train.py", line 68, in train
    loss = calc_loss(loss_dict, results, logger, global_step)
  File "train.py", line 40, in calc_loss
    assert torch.all(results['seg_label'] <5), results['seg_label'][  results['seg_label'] >= 5]    
AssertionError: tensor([255, 255, 234,  ..., 255, 255, 255], device='cuda:0')
这意思是标注的车道线数目超过了最大数目吗？想知道这种问题可以做何修改？

**Comment by cfzd** [comment]
@hungrybreadyosoro 
抱歉没有及时回复。因为`results['seg_label']`里面包含的是分割图的标注，那一般的车道线数据集都是标4条线，再加上一个背景类，也就是说最多是5个类别在分割里。所以一般来说这个标注的值会是[0,1,2,3,4]这个范围内，但是似乎报错的地方提示有255,234这样的类别，这个应该是不太对的，因为一般分割任务都很难有200多个类吧，更不要说车道线分割。
