### ISSUE TITLE
关于训练自己的数据的问题

### ISSUE THREAD

**Issue by KKKarlW** [cfzd/Ultra-Fast-Lane-Detection#209]
您好！感谢你的工作！
我使用labelme标注了自己的图片并按照相关教程做成tusimple格式，想拿来进行训练，会报出以下错误：
`RuntimeError: CUDA error: device-side assert triggered`
不知道是什么原因，烦请大佬看看。
是不是我的数据存放形式不对的原因，不太明白您代码中的dataloader.py中数据加载的流程。

**Comment by cfzd** [comment]
@KKKarlW 
这个报错是由于标注中存在大于类别数的label。比如对于一个1000维的分类网络，label应该在[0,999]这个范围内，出现了1000及以上的label就会报这个错

**Comment by wo-ai-xue-xi** [comment]
> @KKKarlW
> 这个报错是由于标注中存在大于类别数的label。比如对于一个1000维的分类网络，label应该在[0,999]这个范围内，出现了1000及以上的label就会报这个错

老哥我想问一下如果是训练自己数据集的话，怎么按照tusimple格式存放，因为我之前去用了那个lanenet，他的存放格式和tusimple官方格式有出入。不知道我能否这样分别存放，gt_binary_image，gt_instance_image，image，train.txt，val.txt

**Comment by HaolinBlack** [comment]
你好，请问这个问题你解决了吗

**Comment by Chenfy13** [comment]
你好，请问这个问题你解决了吗
