### ISSUE TITLE
配置环境时在evaluation/culane中执行make指令错误的问题

### ISSUE THREAD

**Issue by ymzis69** [cfzd/Ultra-Fast-Lane-Detection#21]
作者您好，我在配置环境时，已经安装好opencv C++，然后执行：

cd evaluation/culane
make

的时候，发生了以下错误：

CXX src/evaluate.cpp
CXX src/counter.cpp
CXX src/spline.cpp
CXX src/lane_compare.cpp
CXX/LD evaluate
/usr/bin/ld: //usr/local/lib/libopencv_core.a(opencl_core.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: 无法添加符号: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'evaluate' failed
make: *** [evaluate] Error 1

请问这是为什么呢？

**Comment by ymzis69** [comment]
作者您好，我在opencv解压的文件夹下新建的文件夹原来不是命名为build，make失败了。然后在另一台电脑将文件夹命名为build，然后make成功了，请问是不是文件夹命名的问题呢？

**Comment by cfzd** [comment]
@ymzis69 
If it is the first dynamic link library problem, you can try
```
sudo ldconfig -v 
```
and remake the CULane evaluation code.

If it is the build problem of OpenCV, I think you have to build it in the `build` folder.

**Comment by ymzis69** [comment]
谢谢您的回复，创建的文件夹的名字的确需要为build

**Comment by foxkw** [comment]
> 谢谢您的回复，创建的文件夹的名字的确需要为build

您好，请问使用的opencv和g++版本是什么呢， 我不知道该装哪个版本

**Comment by ymzis69** [comment]
不好意思额，我当时是按照他的教程装的，具体版本我忘记了。



---原始邮件---
发件人: "foxkw"<notifications@github.com&gt;
发送时间: 2020年12月25日(周五) 中午11:44
收件人: "cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"ymzis69"<1750950070@qq.com&gt;;
主题: Re: [cfzd/Ultra-Fast-Lane-Detection] 配置环境时在evaluation/culane中执行make指令错误的问题 (#21)




  
谢谢您的回复，创建的文件夹的名字的确需要为build
  
您好，请问使用的opencv和g++版本是什么呢， 我不知道该装哪个版本

**Comment by foxkw** [comment]
> 不好意思额，我当时是按照他的教程装的，具体版本我忘记了。
> […](#)
> ---原始邮件--- 发件人: "foxkw"<notifications@github.com&gt; 发送时间: 2020年12月25日(周五) 中午11:44 收件人: "cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"ymzis69"<1750950070@qq.com&gt;; 主题: Re: [cfzd/Ultra-Fast-Lane-Detection] 配置环境时在evaluation/culane中执行make指令错误的问题 (#21) 谢谢您的回复，创建的文件夹的名字的确需要为build 您好，请问使用的opencv和g++版本是什么呢， 我不知道该装哪个版本 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2      请问为啥这里有cv4又有cv2, 不明白
