### ISSUE TITLE
关于推断结果后处理

### ISSUE THREAD

**Issue by AmazingYi** [cfzd/Ultra-Fast-Lane-Detection#211]
大佬你好，
        我在尝试将您的demo.py改单张图片测试的情况，使用的是Culane 数据集里面的单张图片进行测试，后处理过程似乎有些复杂。当然，我复制了demo.py 里面的后处理过程，发现得出的结果，绘制在图片上的点和 车道线不重合。但是车道线的形状绘制正确。我尝试上下左右翻转图像，均不重合。直到我观察了所有点的与实际车道的关系。发现其居然关于H 坐标417左右的直线轴对称。将其据此轴翻转后正好与实际车道重合。
      我拜读了大佬的论文，想请教大佬在设置车道检测 的cells 方块区域 是关于图像H 像素417 对称的吗？还有就是请教一下设计这些后处理步骤的奥妙所在？

**Comment by cfzd** [comment]
@AmazingYi 
后处理的逻辑是这样的：网络的输出是一个`batch_size x num_gridding+1 x num_cls_per_lane x num_lane`大小的tensor，可以看到大致就是包含了每个batch、每条车道线、每条车道线的所有行上的坐标分类结果。但是这个有个问题就是这个tensor只包含车道线的x横坐标位置，纵坐标位置实际上是存储在`constant.py`的row_anchor中的。所以后处理就是：
- 通过求位置期望的方式得到一个`batch_size x num_cls_per_lane x num_lane`的tensor，这个tensor包含x坐标
- 把row_anchor中的y坐标得到
- 讲上述x,y坐标做缩放，使得其符合输入图像大小
- 在分类时还有一个特殊的类别，表示没有线，最后一步处理就是把没有线的情况去掉

这样就得到了检测的结果。我觉得你说的关于某个位置对称的情况，应该是row_anchor没有正确处理导致的。
