### ISSUE TITLE
关于训练其他数据集的问题

### ISSUE THREAD

**Issue by cxhmikegithub** [cfzd/Ultra-Fast-Lane-Detection#216]
硬件：台式机TX2080，工控机TITAN
数据集：CurveLanes
batch size:16

问题：执行 python train.py configs/curlane.py 后，电脑重启，在工控机和台式机上都会重启

**Comment by cxhmikegithub** [comment]
准备训练的时候，CPU利用率100%

**Comment by cfzd** [comment]
@cxhmikegithub 
我从来没有遇到过这类问题，你可以试着单步调试一下吗？从train.py的入口开始一步一步调试，看到哪一步会发生重启？

**Comment by cxhmikegithub** [comment]
你好，我用resnet18训练了50个epoch，请问您提供的culane_18.pth和tusimple_18.pth只有一二百兆，为什么我训练出来的权重800多M？

**Comment by cfzd** [comment]
@cxhmikegithub 
这个是因为训练出来的模型包含了优化器的状态，同时还有分割branch的权重。

**Comment by cxhmikegithub** [comment]
> @cxhmikegithub
> 这个是因为训练出来的模型包含了优化器的状态，同时还有分割branch的权重。

请问怎么让模型只保留推理的branch，让它小点？

**Comment by cfzd** [comment]
@cxhmikegithub 
根据存储的代码可知：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/utils/common.py#L66-L73
如果你要删除optimizer的状态，可以只把`state['model']`读取出来然后再存。如果还想进一步删除`state['model']`中的分割branch，可以照样把`state['model']`读取出来，然后对`state['model']`的`.keys()`进行过滤，滤掉所有包含`aux`的键值对（因为分割的branch包含aux_header2,aux_header3,aux_header4,aux_combine），然后重新组成一个字典存储起来即可。
