### ISSUE TITLE
一个训练问题

### ISSUE THREAD

**Issue by sveinnsveinn** [cfzd/Ultra-Fast-Lane-Detection#217]
我在训练的时候按照论文，将sim loss weight和shp loss weight的权重都设置成1，使用Adam优化器，然后训练的时候loss一直降不下去，我检测的精度也是0，，后来我换成了SGD优化器，还是不行，麻烦作者帮我看看是什么问题

**Comment by sveinnsveinn** [comment]
![image](https://user-images.githubusercontent.com/77672079/120145476-26be3200-c216-11eb-8a27-bf080128456b.png)
我就是这么配置的，这样改了之后loss就一直降不下去

**Comment by cfzd** [comment]
@sveinnsveinn 
其实你不需要修改，就使用原来config中的默认参数就好了

**Comment by sveinnsveinn** [comment]
非常感谢你能在百忙之中回答我的问题，万分感谢

**Comment by sveinnsveinn** [comment]
原代码的默认参数确实好用，我用默认参数训练出了很好的模型，但是我在读你的论文，发现了关于这个新增的sim_loss以及shp_loss，我就想试试他的结果，然后就按照你论文的设置，配制了这个参数，但是一直训练失败，尝试了很多次，loss一直降不下去，我实在是找不到原因，才来打扰你的
![image](https://user-images.githubusercontent.com/77672079/120154121-19a74000-c222-11eb-9993-2463f8138d40.png)

**Comment by cfzd** [comment]
@sveinnsveinn 
这个其实是因为我们开源的代码是重新实现的，原来work的一些设置在开源的代码就不work了，这个原因我们也不知道为什么。不过过段时间应该我们会release一个新的版本的方法，会比目前这个版本性能强很多。

**Comment by sveinnsveinn** [comment]
好的，知道了，非常感谢
