### ISSUE TITLE
关于训练自己的数据集的问题

### ISSUE THREAD

**Issue by HaolinBlack** [cfzd/Ultra-Fast-Lane-Detection#219]
您好，我尝试用自己制作的3车道线的数据集进行训练，但是程序会在计算loss的地方报错CUDA error: device-side assert triggered
。应该是训练集标签和输出数据的尺寸不一致出现的问题。
修改config文件的num_lanes也无法解决这一问题，想请问一下应该如何修改程序才能解决呢？

**Comment by cfzd** [comment]
@HaolinBlack 
我觉得可以参考一下这个issue: #215

**Comment by HaolinBlack** [comment]
> @HaolinBlack
> 我觉得可以参考一下这个issue: #215

好的谢谢，再打扰一下，我训练完了自己的数据得到了模型文件，可是运行test.py仍然会报错，想请问一下还需要修改什么程序吗？训练图片是1280*720

**Comment by tigerdhl** [comment]
> 您好，我尝试用自己制作的3车道线的数据集进行训练，但是程序会在计算loss的地方报错CUDA error: device-side assert triggered
> 。应该是训练集标签和输出数据的尺寸不一致出现的问题。
> 修改config文件的num_lanes也无法解决这一问题，想请问一下应该如何修改程序才能解决呢？

请问自己的数据集是什么样的格式呢?
