### ISSUE TITLE
model overfitting over custom dataset

### ISSUE THREAD

**Issue by letdivedeep** [cfzd/Ultra-Fast-Lane-Detection#222]
Hi @cfzd 

On my custom dataset with an image shape of 256 x 512. My model is overfitted before the first epochs itself. 
![Screenshot 2021-06-07 at 9 10 42 PM](https://user-images.githubusercontent.com/74127861/121050657-636dc880-c7d6-11eb-913c-04bb7b3620e2.png)

I have trained the model with CULane default config parameters on the input shape of  288 x 352  as suggested in this [issue](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/124)

even though we are using augmentation as suggested [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/5)

why is the model overfitted?
shall i change the gridding_num or row anchors?

**Comment by cfzd** [comment]
@letdivedeep 
I simply treat the `griding_num` as a hyperparameter, and frankly I don't know specific rules for choosing the `griding_num`. According to my experiments, changing `griding_num` would cause performance change of course, but the difference is marginal.

**Comment by letdivedeep** [comment]
@cfzd  thanks for the help.
