### ISSUE TITLE
关于paper的一些疑问

### ISSUE THREAD

**Issue by NeilKuo** [cfzd/Ultra-Fast-Lane-Detection#223]
您好，有个关于论文内容的疑问
请问Fig. 8.中右侧Prediction&Label图是如何生成的?
谢谢!!

**Comment by cfzd** [comment]
@NeilKuo 
就是在得到检测到的，或者GT的车道线的坐标后，在坐标处打点或者画个小矩形表示此处是车道线即可。

**Comment by NeilKuo** [comment]
所以图像是用代码生成的吗?还是手动注记的?

**Comment by cfzd** [comment]
@NeilKuo 
是代码生成的, 使用cv2.circle 以及 cv2.rectangle 即可。

**Comment by NeilKuo** [comment]
@cfzd 
写个代码读取culane里label的座标再用cv2.circle , cv2.rectangle画出来
这样理解正确吗?

**Comment by cfzd** [comment]
@NeilKuo 
它其实就是把这两个变量给可视化出来了：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/train.py#L27
