### ISSUE TITLE
cls_num_per_lane 请问作者，这个参数是什么意思。

### ISSUE THREAD

**Issue by zjhellofss** [cfzd/Ultra-Fast-Lane-Detection#224]
cls_num_per_lane这个参数，为什么在Tusimple和CULane这两个数据集的设置是不一样的。他代表了什么，希望您能够解答，谢谢！

**Comment by cfzd** [comment]
@zjhellofss 
这个的含义就是row anchor的数目。不一样是因为图森数据集上的测试是自己规定了数目的，CULane上虽然没有规定这个数目是多少，但是我们follow SCNN的做法和他的设置保持一样。cls_num_per_lane可以通俗理解为一条线用多少次分类去表示，也就是说一条线用多少个点表示。越大表示车道线被表示地更加密集，越小越系数。

**Comment by hwang12345** [comment]
@cfzd 如果数据集图像使用1080p图像，h_samples增加了采样值，cls_num_per_lane的值是不是与h_samples的长度保持一致？且程序中所有的cls_num_per_lane变量的致都与h_samples保持一致？
h_samples = [160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360,
             370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570,
             580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
             780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980,
             990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070]
还有在constant.py中tusimple_row_anchor变量应该如何同步更新呢？
tusimple_row_anchor = [ 64,  68,  72,  76,  80,  84,  88,  92,  96, 100, 104, 108, 112,
            116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164,
            168, 172, 176, 180, 184, 188, 192, 196, 200, 204, 208, 212, 216,
            220, 224, 228, 232, 236, 240, 244, 248, 252, 256, 260, 264, 268,
            272, 276, 280, 284]
