### ISSUE TITLE
变道时应该如何标注数据？

### ISSUE THREAD

**Issue by SiyangXie** [cfzd/Ultra-Fast-Lane-Detection#225]
你好，

我在训练自己的数据时常常遇到变道时不知如何标注的问题。在没有岔道口时，如果存在4条轨道，我标注的逻辑是从左到右依次为1，2，3，4；如果只有2条轨道，我标注的逻辑是从左到右依次为2，3；也就是说2，3一定有，1，4不一定有。可是在有岔道口时我不太清楚应该怎样标注，如下图所示。请问有好的建议吗？

![Screenshot from 2021-06-16 14-32-45](https://user-images.githubusercontent.com/13971749/122170458-2a59e600-ceb1-11eb-8990-10cd8fc60beb.png)

**Comment by cfzd** [comment]
@SiyangXie 
我很认同没有岔道时你的标注方法，这个和SCNN那个方法对于车道线的定义的顺序是一致的，网络应该会很好学习。

至于岔道口的问题，这个确实比较棘手，因为一般车道线是不会交叉的。我觉得你可以这样做：
- 标这种岔道口的时候首先分段标，正如你这张图里所标注的
- 在训练时再根据分段标注的数据组合成1,2,3,4这样的形式去学习（因为这样即使一种方法不work，你也不需要重新标数据，只需要改一下组合代码就行了）
- 关于如何组合，我觉得你可以把下半部分的绿色部分（下绿）和上半部分的红色（上红）组合为1，下绿+上黄组合为2，下黄+上绿组合为3，下黄+上蓝组合为4

如果你的数据集中有足够数量的这样的样本的话，我自己觉得网络是可以学到的，但是这个只是我的个人看法。
