### ISSUE TITLE
how is the train data make?

### ISSUE THREAD

**Issue by tigerdhl** [cfzd/Ultra-Fast-Lane-Detection#226]

**Comment by tigerdhl** [comment]
thank u for the project. How can I train on my data? I can label the train data by labeme to tusimple form, but the form is different with the jason file in your project.
my data like:
![Dingtalk_20210617152439](https://user-images.githubusercontent.com/29905731/122350890-33fe4f00-cf80-11eb-8acd-3bf28adee1a5.jpg)

jason file is :
![Dingtalk_20210617152455](https://user-images.githubusercontent.com/29905731/122350943-3e204d80-cf80-11eb-89b5-630c3f1c6393.jpg)

**Comment by cfzd** [comment]
@tigerdhl 
It seems you have the segmentation label (`label.png`) files, can you provide the information of the segmentation label? If it is the same as the segmentation label format of CULane, you can directly train with the data.

The CULane segmentation label is defined as:
- each lane is a class
- there are all four lanes, i.e. four classes
- from left to right, the label of the four lanes are 1,2,3,4
- for the background, 0 is the label

**Comment by tigerdhl** [comment]
> @tigerdhl
> It seems you have the segmentation label (`label.png`) files, can you provide the information of the segmentation label? If it is the same as the segmentation label format of CULane, you can directly train with the data.
> 
> The CULane segmentation label is defined as:
> 
> * each lane is a class
> * there are all four lanes, i.e. four classes
> * from left to right, the label of the four lanes are 1,2,3,4
> * for the background, 0 is the label

my label.png is not the binary file, the files comes from the json file transformed by labelme tool. the detail information are
![Dingtalk_20210618161347](https://user-images.githubusercontent.com/29905731/122530241-ddad1100-d050-11eb-9764-40d3e4c0df37.jpg)
![Dingtalk_20210618161406](https://user-images.githubusercontent.com/29905731/122530251-df76d480-d050-11eb-8d9b-e86de83f16ad.jpg)
![Dingtalk_20210618161429](https://user-images.githubusercontent.com/29905731/122530266-e3a2f200-d050-11eb-906a-585928dabd91.jpg)

**Comment by tigerdhl** [comment]
> @tigerdhl
> It seems you have the segmentation label (`label.png`) files, can you provide the information of the segmentation label? If it is the same as the segmentation label format of CULane, you can directly train with the data.
> 
> The CULane segmentation label is defined as:
> 
> * each lane is a class
> * there are all four lanes, i.e. four classes
> * from left to right, the label of the four lanes are 1,2,3,4
> * for the background, 0 is the label


@cfzd now I can get the binary file label.png, but have not the .txt file,  It means I have to generate the .txt label file , and use the label.png and label.txt files to train?
