### ISSUE TITLE
为什么我的用resnet18在tusimple上训练权重有700多MB?

### ISSUE THREAD

**Issue by Chenfy13** [cfzd/Ultra-Fast-Lane-Detection#228]
您提供的权重才200多MB, 请问这是为什么呢？

**Comment by cfzd** [comment]
@Chenfy13 
主要是因为里面包含了optimizer和辅助的分割branch的参数，所以会大很多，可以参考这个issue： #155

**Comment by Chenfy13** [comment]
> @Chenfy13
> 主要是因为里面包含了optimizer和辅助的分割branch的参数，所以会大很多，可以参考这个issue： #155
