### ISSUE TITLE
在rtx 3090上运行speed_simple.py，平均fps只有200多？

### ISSUE THREAD

**Issue by Chenfy13** [cfzd/Ultra-Fast-Lane-Detection#229]
远远达不到文中320的平均fps，请问这是为什么呢？RTX 3090的算力比1080ti更高，但是结果却不理想。 
![QQ截图20210621184043](https://user-images.githubusercontent.com/63028348/122749951-81e8bf00-d2c0-11eb-8c61-a932e9b185e1.png)
![QQ截图20210621184110](https://user-images.githubusercontent.com/63028348/122749958-83b28280-d2c0-11eb-8329-c966d790f1bc.png)

**Comment by cfzd** [comment]
@Chenfy13 
速度达不到有很多可能原因吧，这个其实本身也挺玄学的。我在3090上跑出来的速度差不多也是300多，快一点的话能到400，其实和1080ti差不多。而且因为运行速度很快（3ms左右），随便来点延迟就会导致结果差很多，比如慢个1ms就会立马掉到250帧。我是见到别人report过更快的速度的，比如这个： #20 （2.7ms, 370帧）。我觉得你可以在机器温度比较低，并且没有其他占用程序的时候测一测。

**Comment by Chenfy13** [comment]
> @Chenfy13
> 速度达不到有很多可能原因吧，这个其实本身也挺玄学的。我在3090上跑出来的速度差不多也是300多，快一点的话能到400，其实和1080ti差不多。而且因为运行速度很快（3ms左右），随便来点延迟就会导致结果差很多，比如慢个1ms就会立马掉到250帧。我是见到别人report过更快的速度的，比如这个： #20 （2.7ms, 370帧）。我觉得你可以在机器温度比较低，并且没有其他占用程序的时候测一测。

好的，谢谢！
