### ISSUE TITLE
请问一下在线数据增强，修改代码的思路

### ISSUE THREAD

**Issue by hungrybreadyosoro** [cfzd/Ultra-Fast-Lane-Detection#230]
我打算在训练时预先对图片做一些裁剪以数据增强，是否在train.py的第177行：

for epoch in range(resume_epoch, cfg.epoch):

之前添加对图像随即裁剪的代码即可达到目的？另外最关键的是裁剪后，标注点的坐标会随之产生变化，是不是读取txt坐标的代码段应该做修改？还望赐教！

**Comment by tigerdhl** [comment]
@hungrybreadyosoro 
谢谢之前提供的demo，生成label文件，请问culane格式的train_gt.txt是如何生成的，有参考链接吗，有找到一个SCNN的culane数据生成工程，但是需要在linux环境下编译。train_gt.txt格式应该是这样
![Dingtalk_20210622095246](https://user-images.githubusercontent.com/29905731/122850386-b5b6f980-d33f-11eb-923d-cb42f0c32691.jpg)

**Comment by tigerdhl** [comment]
@hungrybreadyosoro 自己写了一个，应该可以了，谢啦

**Comment by hungrybreadyosoro** [comment]
> 
> 
> @hungrybreadyosoro
> 谢谢之前提供的demo，生成label文件，请问culane格式的train_gt.txt是如何生成的，有参考链接吗，有找到一个SCNN的culane数据生成工程，但是需要在linux环境下编译。train_gt.txt格式应该是这样
> ![Dingtalk_20210622095246](https://user-images.githubusercontent.com/29905731/122850386-b5b6f980-d33f-11eb-923d-cb42f0c32691.jpg)

这个我也找到了那个需要在linux下编译的生成工程，嫌麻烦我就自己写了个提取代码，也就是把原图的路径和二值图的路径都提取出来写在train_gt.txt里。
至于后面的1 1 1 1，发现检测代码里并没有用到，不过因为我标注的数据量不大，自己就一个一个手动标记了。
还有先前你找我要json提取文本写入txt，抱歉那个代码被我弄丢了……找了老久，如果需要的话你可以找找csdn上其他人做的范例，改一改应该就可以，这里附上一个我之前参考的博客：
https://blog.csdn.net/weixin_39912556/article/details/88973899?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162433024916780261910991%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=162433024916780261910991&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-88973899.pc_search_result_before_js&utm_term=json%E6%8F%90%E5%8F%96txt&spm=1018.2226.3001.4187

**Comment by cfzd** [comment]
@tigerdhl 
如果你希望做在线数据增强的话，我推荐你参考`data/mytransforms.py`里面的实现方式（例如`RandomLROffsetLABEL`这个类的方式），实现一个crop的变换，你只需要同时对输入的图像和分割标注做一样的crop，这样获取到的坐标点也是对应的。然后把你的实现的crop加到这个地方：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/data/dataloader.py#L23-L27

还有一个问题，我记得你之前也提过一个issue，但我没有及时回复。你的那个分割数据是要做一定的处理才能训练的，因为一般的车道线分割结果是一条连续的线，但是你的标注图像里面是很多点的标注，你需要把这些点一一连起来，如下图，然后才能形成适合训练的label。
![image](https://user-images.githubusercontent.com/17758403/122856473-6f669800-d349-11eb-82bb-801695a6be8e.png)

**Comment by tigerdhl** [comment]
> @tigerdhl
> 如果你希望做在线数据增强的话，我推荐你参考`data/mytransforms.py`里面的实现方式（例如`RandomLROffsetLABEL`这个类的方式），实现一个crop的变换，你只需要同时对输入的图像和分割标注做一样的crop，这样获取到的坐标点也是对应的。然后把你的实现的crop加到这个地方：
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/data/dataloader.py#L23-L27
> 
> 还有一个问题，我记得你之前也提过一个issue，但我没有及时回复。你的那个分割数据是要做一定的处理才能训练的，因为一般的车道线分割结果是一条连续的线，但是你的标注图像里面是很多点的标注，你需要把这些点一一连起来，然后才能形成适合训练的label。

@hungrybreadyosoro  你的answer

**Comment by tigerdhl** [comment]
> @tigerdhl
> 如果你希望做在线数据增强的话，我推荐你参考`data/mytransforms.py`里面的实现方式（例如`RandomLROffsetLABEL`这个类的方式），实现一个crop的变换，你只需要同时对输入的图像和分割标注做一样的crop，这样获取到的坐标点也是对应的。然后把你的实现的crop加到这个地方：
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/data/dataloader.py#L23-L27
> 
> 还有一个问题，我记得你之前也提过一个issue，但我没有及时回复。你的那个分割数据是要做一定的处理才能训练的，因为一般的车道线分割结果是一条连续的线，但是你的标注图像里面是很多点的标注，你需要把这些点一一连起来，然后才能形成适合训练的label。

@cfzd 谢了，我现在用CUlane格式了，训练数据可以处理了

**Comment by tigerdhl** [comment]
> > @hungrybreadyosoro
> > 谢谢之前提供的demo，生成label文件，请问culane格式的train_gt.txt是如何生成的，有参考链接吗，有找到一个SCNN的culane数据生成工程，但是需要在linux环境下编译。train_gt.txt格式应该是这样
> > ![Dingtalk_20210622095246](https://user-images.githubusercontent.com/29905731/122850386-b5b6f980-d33f-11eb-923d-cb42f0c32691.jpg)
> 
> 这个我也找到了那个需要在linux下编译的生成工程，嫌麻烦我就自己写了个提取代码，也就是把原图的路径和二值图的路径都提取出来写在train_gt.txt里。
> 至于后面的1 1 1 1，发现检测代码里并没有用到，不过因为我标注的数据量不大，自己就一个一个手动标记了。
> 还有先前你找我要json提取文本写入txt，抱歉那个代码被我弄丢了……找了老久，如果需要的话你可以找找csdn上其他人做的范例，改一改应该就可以，这里附上一个我之前参考的博客：
> https://blog.csdn.net/weixin_39912556/article/details/88973899?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162433024916780261910991%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=162433024916780261910991&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-88973899.pc_search_result_before_js&utm_term=json%E6%8F%90%E5%8F%96txt&spm=1018.2226.3001.4187

谢了，我自己写了一个，可以处理了
