### ISSUE TITLE
关于结果获取问题

### ISSUE THREAD

**Issue by tigerdhl** [cfzd/Ultra-Fast-Lane-Detection#231]
@cfzd 
我使用的是culane数据格式，现在需要获取输出的每个point的坐标。我看可以在demo.py中的out中获取，那走test.py是否也能获取结果？谢谢回复

**Comment by cfzd** [comment]
@tigerdhl 
`demo.py`主要是用来可视化的，`test.py`是用来在CULane上评估性能的。获取到的坐标可以参考以下代码：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/demo.py#L89
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/evaluation/eval_wrapper.py#L44

**Comment by tigerdhl** [comment]
> @tigerdhl
> `demo.py`主要是用来可视化的，`test.py`是用来在CULane上评估性能的。获取到的坐标可以参考以下代码：
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/demo.py#L89
> 
> 
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/evaluation/eval_wrapper.py#L44

明白，谢谢
