### ISSUE TITLE
请问车道线标注时的细节

### ISSUE THREAD

**Issue by tigerdhl** [cfzd/Ultra-Fast-Lane-Detection#232]
@cfzd 
我用线段进行标注，类似下图，如果起点是从前面蓝色开始标到橘红色，和起点从下面橘红色开始标到蓝色，会影响模型效果吗？我的训练数据这两部分方式标的都有，发现模型效果奇怪，对于连续的实线车道线拟合较好，对于虚线车道线很乱，训练数据中一些虚线车道线就是从蓝色开始标到橘红色的。实线车道线的数据都是从橘红色标到蓝色。另外，请问训练50个epoch后如何继续training？
![D5A85DA9-C09D-4d18-B594-4BB5A4C40092](https://user-images.githubusercontent.com/29905731/123192576-c9946400-d4d5-11eb-9032-624cc955fee0.png)

**Comment by cfzd** [comment]
@tigerdhl 
你的意思是说线的方向的问题吗（从上到下和从下到上）？因为CULane是直接把一整条线标成一个完整的分割线，所以线是没有从上到下或者从下到上的区别的。我比较奇怪的是不太清楚你所说的线段是什么意思，不应该一条车道线就是一整个曲线吗？为什么要分段呢？

**Comment by tigerdhl** [comment]
> @tigerdhl
> 你的意思是说线的方向的问题吗（从上到下和从下到上）？因为CULane是直接把一整条线标成一个完整的分割线，所以线是没有从上到下或者从下到上的区别的。我比较奇怪的是不太清楚你所说的线段是什么意思，不应该一条车道线就是一整个曲线吗？为什么要分段呢？

就是一整条线，至少线段连起来。我也觉得应该和方向没关系，但是检测结果有点奇怪。虚线的比较差，实线的很好。我只用同一方向标注的数据训练后，虚线检测就比较正常了。我再测试看看。

**Comment by tigerdhl** [comment]
> @tigerdhl
> 你的意思是说线的方向的问题吗（从上到下和从下到上）？因为CULane是直接把一整条线标成一个完整的分割线，所以线是没有从上到下或者从下到上的区别的。我比较奇怪的是不太清楚你所说的线段是什么意思，不应该一条车道线就是一整个曲线吗？为什么要分段呢？

还有，代码能够在上一次模型后继续训练吗？不用从头开始

**Comment by cfzd** [comment]
@tigerdhl 
可以使用`--resume`或者`--finetune`，具体的代码在这个部分：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/train.py#L122-L138
或许你需要根据你的需求稍微改一下代码

**Comment by tigerdhl** [comment]
> @tigerdhl
> 可以使用`--resume`或者`--finetune`，具体的代码在这个部分：
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/9f7fb331528968a75ef06b28514d6ce0c3f62ff5/train.py#L122-L138
> 
> 
> 或许你需要根据你的需求稍微改一下代码

thank u
