### ISSUE TITLE
关于c++推理效果

### ISSUE THREAD

**Issue by tigerdhl** [cfzd/Ultra-Fast-Lane-Detection#233]
@cfzd 你好，有看到project里有个main.cpp文件是c++推理模块，请问这个版本效果和python比性能和检测效果差异大吗？

**Comment by cfzd** [comment]
@tigerdhl 
这个应该是没有差异，只是C++的实现。不过这个我没有测试过，是第三方贡献的。

**Comment by tigerdhl** [comment]
你好，问个问题。如果要做一个车道线检测产品，一个简单想法是训练好模型，集成入设备，这个设备安装在车上，不管走哪边的路，即不管车道线数据是如何，都能很好的检测出来。但是现在发现很多车道线检测模型的泛化能力并没有这么强，这是什么原因。比如在culane数据上训练的模型，用于检测我自己的数据，效果并不好，是否一定图像数据和训练的数据类似才行？



在 2021-06-28 10:24:48，"cfzd" ***@***.***> 写道：

@tigerdhl
这个应该是没有差异，只是C++的实现。不过这个我没有测试过，是第三方贡献的。
