### ISSUE TITLE
How to set the parameter of 'sim_loss_w' and 'shp_loss_w '  during training??  and the value of cross parameter? 

### ISSUE THREAD

**Issue by qdzwss** [cfzd/Ultra-Fast-Lane-Detection#234]
First of all, I really appreciate your excellent work!!

**Issue1:**
In the culane.py ,these two loss parameters are set to zero.
So what are the values of these two parameters that you set during the training? I want a reference

# LOSS
sim_loss_w = 0.0
shp_loss_w = 0.0

In addition, I have trained 50 rounds myself. The two loss parameters are 0 and EOPC is 50. Resnet18 is adopted, and the training results are basically the same as the weights you provided. Does this mean that the impact of the two losses is small? It's almost negligible, right?

This is my trained reslut:

`Evaluating the results. . .
tp: 13101 fp: 7043 fn: 7929
finished process file
precision: 0.650367
recall: 0.622967
Fmeasure: 0.636372

res_normal 0.893644
res_crowd 0.676583
res_night 0.636372
res_noline 0.407585
res_shadow 0.600035
res_arrow 0.823019
res_hlight 0.582333
res_curve 0.586756
res_cross 0.0
0.6966441594494167
`

**Issue2:**

When I run the test program, one of the cross index results is 0, I see the papers are 1743 (Resnet18), 2037 (Resnet34). How is the value of this parameter calculated?

**Comment by cfzd** [comment]
@qdzwss 
For issue 1:
The loss weights for the two losses are 0 on CULane. On Tusimple, they are 1 and 0. You can also refer to this issue: #8

 For issue 2:
The crossroad case only counts FP. The F1 of the crossroad case is always 0 as you see. To check the results of crossroad, you could:
- check the output in the `test_work_dir`. Suppose the `test_work_dir` is `./tmp`, you can checkout all the results in the `./tmp/txt/out*.txt`
- check the terminal output. You can see something like this:
 ![image](https://user-images.githubusercontent.com/17758403/124536044-cdb37080-de49-11eb-9734-335b1bf87f42.png)
