### ISSUE TITLE
eval_wrapper.py

### ISSUE THREAD

**Issue by joker-wutong** [cfzd/Ultra-Fast-Lane-Detection#239]
when i run `python eval_wrapper.py` ,get the result `Traceback (most recent call last):
  File "eval_wrapper.py", line 2, in <module>
    from data.dataloader import get_test_loader
ModuleNotFoundError: No module named 'data.dataloader'
`
so ,what should I do to solve this problem ？
 Thanks！

**Comment by cfzd** [comment]
@joker-wutong 
If you want to evaluate the model, you can run:
```
mkdir tmp
# This a bad example, you should put the temp files outside the project.

python test.py configs/culane.py --test_model path_to_culane_18.pth --test_work_dir ./tmp
# or
python test.py configs/tusimple.py --test_model path_to_tusimple_18.pth --test_work_dir ./tmp
```

`test.py` will call the functions in `eval_wrapper.py` to finish the evaluation.
