### ISSUE TITLE
合并两个数据集训练时的参数设置问题

### ISSUE THREAD

**Issue by yezhuwa** [cfzd/Ultra-Fast-Lane-Detection#240]
您好！我想将转换后的Tusimple数据集加到Culane数据集里，但是这两单独训练的时候诸如row_anchor之类的参数设定不一样，可否将合并后的数据集按照Culane的设定进行训练？

**Comment by cfzd** [comment]
@yezhuwa 
完全可以的

**Comment by yezhuwa** [comment]
感谢您的回复！还有一个问题，我看见您在其他问题里面说到了自己数据集标注的问题，要遵循Culane的标注规范，起码自己标注的标注顺序要一致。我们现有的数据集标注顺序很乱，这会造成很大的影响吗？谢谢您。

**Comment by yezhuwa** [comment]
> @yezhuwa
> 完全可以的

感谢您的回复！还有一个问题，我看见您在其他问题里面说到了自己数据集标注的问题，要遵循Culane的标注规范，起码自己标注的标注顺序要一致。我们现有的数据集标注顺序很乱，这会造成很大的影响吗？谢谢您。

**Comment by cfzd** [comment]
@yezhuwa 
是的，现在的方法需要车道线是有序的，就像CULane他们规定的那个一样。如果你们的数据集是无序的话，你可以参考一下`scripts/convert_tusimple.py`这个代码。因为Tusimple本身也是无序标注的，所以我写了一个简单的依靠车道线的斜率和截距分析代码用来给车道线定序。

**Comment by yezhuwa** [comment]
@cfzd 
好的，非常感谢您的回复！
