### ISSUE TITLE
train on combined tusimple and culane dataset

### ISSUE THREAD

**Issue by k8280627** [cfzd/Ultra-Fast-Lane-Detection#243]
Hello, first of all, thank you so much for your work!

I noticed that there are two models, one for TuSimple and one for CULane. The two models have different row anchors and gridding numbers. Is it possible to create a model that can train on a combined TuSimple and CULane dataset? If so, what would you suggest to change? Ex: how would you change row anchors and gridding numbers?

Thank you very much!

**Comment by cfzd** [comment]
@k8280627 
If you want to combine the datasets, you need to set unified row anchors and gridding numbers. I think you can simply use the row anchor and gridding number from the CULane.

**Comment by k8280627** [comment]
I see! Thank you very much, will give it a try!
