### ISSUE TITLE
I made UFLD achieve 95.90% acc on TuSimple with one line of code

### ISSUE THREAD

**Issue by juliangebele** [cfzd/Ultra-Fast-Lane-Detection#253]
Hi, thank you for sharing your code! I kindly appreciate your great effort!

In my researches, where I'm using your code together with a Domain Adaptation approach, I found out that I could improve the accuracy of the network e.g. on TuSimple Benchmark from 95.82% acc to 95.90%. 

This is showed in the bottom picture. The first line was executed with your vanilla code, without improvements. The second line is executed with one added line of code, which considers outputscaling of the last outputlayer, which I found out in my researches.

![TuSimple_18_eval](https://user-images.githubusercontent.com/38294281/131990348-93413803-c56d-42ed-9cbe-665456d082f3.png)

For reproducing, go to this line

https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/evaluation/eval_wrapper.py#L93

After this line add the following line: 
`out /= 0.5`

This scales the values of the output layer. This value worked best for me, I tested some other values, which seemed to not have a great impact. 

It would be great if you could confirm that this is really helping the network achieve a higher accuracy or if I might have a bug somewhere :)

**Comment by cfzd** [comment]
@juliangebele 
Interesting points! Since the variable `out` will be passed through the softmax function to get the probability of each location on row anchors, this kind of scaling could indeed change the output. But I want to know the motivation behind the scaling.

**Comment by juliangebele** [comment]
I'm using your Ultra Fast Lane Detection together with [PCS-FUDA](https://github.com/zhengzangw/PCS-FUDA), a Domain Adaptation approach, which I haven't published yet. This approach has an L2-Normalization layer after the feature encoder and a cosine classifier, which uses weights normalization and temperature scaling after the output layer. My initial problem was a proper visualization of the lanes, so I made extensive experiments with the output scaling, which seemed to have a good effect on it.

**Comment by cfzd** [comment]
@juliangebele 
Exciting! Looking forward to your work!

**Comment by juliangebele** [comment]
Alright, thanks! I'm closing this issue if there aren't any questions.
