### ISSUE TITLE
files in TuSimple dataset

### ISSUE THREAD

**Issue by NoBtree** [cfzd/Ultra-Fast-Lane-Detection#256]
It seems that test_label.json includes test_tasks_0627.json, the only difference is that lanes in test_tasks_0627 are empty. right?

**Comment by cfzd** [comment]
@NoBtree 
The `test_label.json` file is the ground truth of the testing set of Tusimple. It should only be used for evaluation.

**Comment by NoBtree** [comment]
> @NoBtree
> The `test_label.json` file is the ground truth of the testing set of Tusimple. It should only be used for evaluation.

thanks
