### ISSUE TITLE
When you build OpenCV, remove the paths of anaconda from PATH or it will be failed.

### ISSUE THREAD

**Issue by xyloww** [cfzd/Ultra-Fast-Lane-Detection#258]
"When you build OpenCV, remove the paths of anaconda from PATH or it will be failed."

May I ask how to remove the paths of anaconda from PATH?

**Comment by cfzd** [comment]
@xyloww 
You can do it as follows:
1. Get the value of PATH:
    ```
    echo $PATH
    ```
    It could looks like: `/usr/local/cuda/bin:/home/user/anaconda3/condabin:/usr/local/bin: ...`
2. You can manually remove the paths related with anaconda like:
    ```
    PATH_DEFAULT=$PATH
    export PATH=/usr/local/cuda/bin:/usr/local/bin: ...
    ```
3. Build your OpenCV
4. Restore your default PATH:
    ```
    export PATH=$PATH_DEFAULT
    ```

**Comment by xyloww** [comment]
Thank you!
