### ISSUE TITLE
Computational cost

### ISSUE THREAD

**Issue by xyloww** [cfzd/Ultra-Fast-Lane-Detection#263]
May I ask why is the computational cost for your formulation: C x h x (w+1), 
and the cost for segmentation: H x W x (C+1)? 
in particular why is it (w+1) for UFLD method and (C+1)for segmentation 

Thank you in advance!

**Comment by cfzd** [comment]
@xyloww 
For segmentation, if you want to segment C lanes, you have to use (C+1) maps with C maps for each lane and one background map.

For our method, we directly learn the position of lanes. For example, suppose the width of the image is 100, the position of the lane is 34. Then I can use a 100-class classification to formulation this problem, and the ground truth is the 34th class. So it is (w+1) for our method, and the one is for "no lane" case.

**Comment by xyloww** [comment]
thank you very much for the clear explanation!
