### ISSUE TITLE
自己的训练集图片分辨率为4096x2160

### ISSUE THREAD

**Issue by dragonhaha** [cfzd/Ultra-Fast-Lane-Detection#268]
作者您好
我想使用4096x2160分辨率的自己的数据集训练网络。我想分别修改以下几个位置

1. https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/data/dataloader.py#L10-L22
    我修改为`mytransforms.FreeScaleMask((2160, 4096)),` `transforms.Resize((2160, 4096)),`
2. https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/train.py#L116
    我增加了size=(2160, 4096)参数
3. https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703//model/model.py#L60-L64
    请问这里的(1800, 2048)该如何修改呢？

还有除了以上几处位置还需要修改哪里呢？非常感谢！！

**Comment by dragonhaha** [comment]
大佬您好。我尝试着不改变任何参数，直接将自己构建的4096x2160的CULane格式数据集拿去训练，训练结束后修改了demo.py的
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/demo.py#L51-L55 
为
        splits = ['test.txt']
        datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]
        img_w, img_h = 4096, 2160
        row_anchor = (np.array(culane_row_anchor) / 288 * img_h).astype('int8').tolist()
然后运行
`python demo.py configs/culane.py --test_model path_to_culane_18.pth` 
提示：
  File "demo.py", line 38, in <module>
    net.load_state_dict(compatible_state_dict, strict=False)
.......
RuntimeError: Error(s) in loading state_dict for parsingNet:
        size mismatch for cls.2.weight: copying a param with shape torch.Size([10854, 2048]) from checkpoint, the shape in current model is torch.Size([14472, 2048]).
        size mismatch for cls.2.bias: copying a param with shape torch.Size([10854]) from checkpoint, the shape in current model is torch.Size([14472]).
这个错误如何解决呢？

**Comment by cfzd** [comment]
@dragonhaha 
如果要修改分辨率的，可能需要修改以下部分：
- 网络结构定义
- 数据读取
- 最终评估及可视化部分
网络结构定义部分主要是最后分类器的维度问题，因为我们是特征拉平后做分类，所以图像大小变了的话分类器的输入维度也要变。修改方法的话以4096x2160为例，你的输入维度就应该是`4096/32*2160/32*8`，这里面32是网络的stride，8是最后一层的channel数目。你上面的报错就是因为分类器维度对不上。

数据读取部分也要修改，因为分辨率变了，所以anchor的定义也要修改和你的输入图片的高度适配。以及数据读取部分有关anchor的部分可能都要检查一下会不会有问题。

最后就是评估及可视化部分，因为你的输入变了，anchor变了，所以相关的坐标获取的部分也要跟着相应的变化。

最后，我不知道为什么需要4096x2160这么大的一个分辨率，这种分辨率估计是跑不起来的，显存会直接溢出的，即使batch size设为1也会out of memory。

**Comment by dragonhaha** [comment]
@cfzd 
多谢大佬的解答，已经解决问题了，我自己的数据集车道线数量3条，而且训练的时候设置的也是3条，把
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/demo.py#L27-L28
的4改成3就没报错了。谢谢~~~
