### ISSUE TITLE
安装evaluate的问题

### ISSUE THREAD

**Issue by lxdo517** [cfzd/Ultra-Fast-Lane-Detection#269]
![image](https://user-images.githubusercontent.com/68673710/143672286-594ca1d2-18a2-4e92-90bf-5ba7b5140021.png)
大佬，我在在Ubuntu系统下编译好evaluate安装到我windows的环境下，这样也是报错的，能这样操作吗？

**Comment by cfzd** [comment]
@lxdo517 
因为我在知乎上看到你已经搞定了这个问题，所以我就关闭这个issue了，如果你有任务问题随时再开
