### ISSUE TITLE
loss 值振荡，不下降

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#27]
你好，感谢你的工作，我在使用culane训练时，观察到的loss值分布如下，请问会是什么原因引起的，期待您的回复
![QQ图片20200709094038](https://user-images.githubusercontent.com/30924021/86987302-514f6880-c1c8-11ea-9d88-b5d18fe30594.png)

**Comment by cfzd** [comment]
@gneworld 
I wonder how long did the log last? If it is just a few epochs, the loss would not decrease a lot. 

Also, I recommend you to use tensorboard to observe the losses and metrics. Our code has supported it.

**Comment by gneworld** [comment]
@cfzd 
 I have trained on culane dataset for about 25 epochs with one 2080ti. As your advice in other issues, I changed the lr from 0.1 to 0.025, this is the latest trainind result
![1594275427(1)](https://user-images.githubusercontent.com/30924021/87003807-e6fdee80-c1ee-11ea-8f49-d16a2f8131fa.png)

I don't know if it is right?

**Comment by cfzd** [comment]
@gneworld 
I think it looks like a good one. The iou is increasing and loss is decreasing. To verify the results, you can run
```
python test.py configs/culane.py --test_model path_to_culane_model.pth --test_work_dir ./tmp
```

**Comment by gneworld** [comment]
hi, cfzd
   After training 50 epochs, I got following test results, 
.......
res_normal 0.895078
res_crowd 0.674346
res_night 0.642249
res_noline 0.401987
res_shadow 0.661217
res_arrow 0.839021
res_hlight 0.603785
res_curve 0.595709
res_cross 0.0
0.6999230162150123

so is it seemed ok?  But when I test the culane model on my own lane video, it works much worse than that in your demo video,  I don't know what factors lead to this inconsistent result, looking forward to your reply

**Comment by longzeyilang** [comment]
@gneworld hi，have you get good result?

**Comment by zhouning1027** [comment]
> 嗨，cfzd 训练 50 个时期后，我得到了以下测试结果，....... res_normal 0.895078 res_crowd 0.674346 res_night 0.642249 res_noline 0.401987 res_shadow 0.661217 res_arrow 0.839021 res_hlight 0.603785 res_curve 0.595709 res_cross 0.6999230162150123
> 
> 那么，看起来没问题吗？但是当我在自己的车道视频上测试 culane 模型时，它的效果比你的演示视频中的要差得多，不知道是什么因素导致了这个不一致的结果，期待你的回复

请问一下你得到这个结果的具体参数是怎么样的呢？
