### ISSUE TITLE
pooling中 channels的设置

### ISSUE THREAD

**Issue by ccblublu** [cfzd/Ultra-Fast-Lane-Detection#271]
作者您好，请问一下在网络中最后的pooling层输出，c = 8，这个是我要根据我的数据进行定义吗，还是网络的固定结构，求指教

**Comment by ccblublu** [comment]
还有一个问题就是您在文章中提到：“It should be noted that we do not count in the background gridding cell and the location index k only ranges from 1 to w, instead of w + 1.”，但是在代码中我看到的是w+1维输入到loss，是我错过了源码中的某些操作和环节吗？还是需要对loss中ignore_lb进行设置？

**Comment by cfzd** [comment]
@ccblublu 
关于8的问题：由于我们要把特征拉平进行分类，直接拉平原来的特征的话维度就太大了，所以用了一个卷积进行降维，把输入维度降下来，这个没有什么具体的准则，我觉得5,6,7,8,9,10,11可能都没有什么区别。

关于w+1的问题，前w维用来定位，最后一维(w+1)维用来判断该行有没有车道线。所以单纯的定位的话是不需要(w+1)维的信息，只不过说有可能通过前w维得到车道线位置了，但是(w+1)维判定没有车道线，那么这个位置就会被丢弃掉。

具体的代码可以参考这一部分：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/evaluation/eval_wrapper.py#L9-L31
上面代码中的griding_num就是(w+1)维，可以看到代码的逻辑是首先直接算出所有的定位部分，然后再根据(w+1)维把无效的位置给过滤掉。

**Comment by ccblublu** [comment]
我还是有一个小疑问。。。这是您在train 的loss里，w+1维是参与loss计算的，由于我是用到自己的数据集，所以针对不同的车道线，不存在车道线的可能会增多，即便是在focal loss下，还是会受到很大的影响，不知道我的理解是否准确：w+1维是会参与train中loss计算的对吗？

**Comment by cfzd** [comment]
@ccblublu 
是的，肯定是会参与loss计算的。如果你不想要这种情况，你可以单独分出来一个存在性分支，做一个单独的二分类就好了

**Comment by ccblublu** [comment]
@cfzd 非常感谢！
