### ISSUE TITLE
你好，请问可以做到不延长车道线的结果吗？

### ISSUE THREAD

**Issue by dragonhaha** [cfzd/Ultra-Fast-Lane-Detection#278]
您好，我的数据需要检测车道线的边缘，我使用UFLD试了一下发现效果还可以，比如这张图
![1](https://user-images.githubusercontent.com/60207179/148489064-09fa6b48-fe7c-4a7b-a5b8-b4884c927bce.png)
但是在面对虚线车道线的时候发现会自动地延长车道线出来，比如这个图
![2](https://user-images.githubusercontent.com/60207179/148489131-dd6208a1-1c2c-4a2a-8fa4-e07167d6ce19.png)
我想请问这是算法中数据增强等操作处理过的结果还是因为训练数据不足出现的结果呢？该如何解决呢？
此外，对弯曲车道边缘的检测末端不够准确，这是否也能通过增大训练数据解决呢？
谢谢！

**Comment by cfzd** [comment]
@dragonhaha 
这个应该是不行的，因为理论上ufld检测的是一整条线，但是你的需求可能是一系列的线段。不过或许你可以通过一些trick来实现，比如结合分割来将ufld输出的一整条线切分成多段线段。

如果你只是想要关闭延长部分的话，只需要注释掉这部分数据增强代码即可：
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/data/dataset.py#L132-L164

**Comment by Willforcv** [comment]
你好, 请问你这个检测效果有修改仓库中的代码吗? 谢谢~

**Comment by Willforcv** [comment]
或者说 这个车道线边缘是你添加了后处理吗

**Comment by dragonhaha** [comment]
> 

没有噢，就单纯标记了边缘然后训练

**Comment by Willforcv** [comment]
> > 
> 
> 没有噢，就单纯标记了边缘然后训练

好的, 谢谢~
