### ISSUE TITLE
dataset.py中关于LaneClsDataset类的_get_index函数的疑问

### ISSUE THREAD

**Issue by Derteanoo** [cfzd/Ultra-Fast-Lane-Detection#28]
Hi，作者大大，在读源码的时候有些疑问，希望您能解答一下。
在dataset.py LaneClsDataset类的_get_index这个函数主要实现了什么功能？我看了代码是取了有标注区域高度的下半部分做直线拟合，再把对应y坐标下的x坐标计算出来。这儿有两点疑问（1）为什么不能直接用原始label的值，做拟合的目的是什么？（2）为什么是取标注高度的一半进行直线拟合？

**Comment by cfzd** [comment]
@Derteanoo 
Hi.
- Why not use the original label directly but fitting it?

    The reason is related to the data augmentation we used. As you may see in the Figure 5 of our paper, after augmentation, there are some blank parts in the image. We want to make the lane continuous in these blank parts, so we use fitting to extend the lane to the blank parts.

- Why only use half part of the annotation for fitting?

    This is in fact a prior knowledge in lane detection. For nearly all lanes, even for curve lanes, the lower part of the lane is still straight. So we use the lower half part of lanes when fitting to avoid the effects of curve lane.

**Comment by Derteanoo** [comment]
I got it！Thanks for your answer!
