### ISSUE TITLE
Training custom dataset

### ISSUE THREAD

**Issue by xyloww** [cfzd/Ultra-Fast-Lane-Detection#280]
I would like to expand the number of training dataset. 

I have converted most of the CULane dataset into night-time. And would like to train your model using datasets from both the night-time version of CULane and original version of CULane. Hence, doubling the number of training dataset. 

May I ask what which files should I be editing in order to do so? 

Thank you for your time!

**Comment by cfzd** [comment]
@xyloww 
Simply add your converted data to the `$CULANEROOT\list\train_gt.txt` list file. The program will read the file and load the data.

**Comment by xyloww** [comment]
In $CULANEROOT\list\  There is also  train.txt, val.txt, val_gt.txt. 
May I check if I should also add the converted data into these files too? 

Thank you once again!

**Comment by cfzd** [comment]
@xyloww 
No, you only need to modify the `train_gt.txt` file. PS, please make a backup of the original `train_gt.txt` file in case you want to restore it.

**Comment by xyloww** [comment]
Thank you!
