### ISSUE TITLE
模型冻结

### ISSUE THREAD

**Issue by zzydzh** [cfzd/Ultra-Fast-Lane-Detection#282]
您好，我自己标注处理了100张图片的数据集，直接使用预训练模型测试效果还可以，不设置finetune直接训练效果差，**设置finetune后再训练自己的数据集300个epoch后效果也差**

因此想到冻结模型，在train.py的finetune中增加了如下两行冻结模型代码，但是报错"RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn"，请问您有什么建议吗？  
 
    if cfg.finetune is not None:
        dist_print('finetune from ', cfg.finetune)
        state_all = torch.load(cfg.finetune)['model']
        state_clip = {}  # only use backbone parameters
        for k,v in state_all.items():
            if 'model' in k:
                state_clip[k] = v
        net.load_state_dict(state_clip, strict=False)
        for param in model.parameters(): 
            param.requires_grad = False

**Comment by cfzd** [comment]
@zzydzh 
可能还需要在optimizer的创建中过滤掉那些冻结的参数，可以参考以下代码：
```
filtered_parameters = filter(lambda p: p.requires_grad, net.parameters())
optimizer = optim.SGD(filtered_parameters , ...)
```

**Comment by zzydzh** [comment]
> @zzydzh 可能还需要在optimizer的创建中过滤掉那些冻结的参数，可以参考以下代码：
> 
> ```
> filtered_parameters = filter(lambda p: p.requires_grad, net.parameters())
> optimizer = optim.SGD(filtered_parameters , ...)
> ```

谢谢您的回复，我最后改成了  
for param in net.model.parameters(): 
        param.requires_grad = False  
最后效果一般，可能是我数据集太小的原因
