### ISSUE TITLE
Resume key error

### ISSUE THREAD

**Issue by zwyzwy** [cfzd/Ultra-Fast-Lane-Detection#29]
when i set the "resume" value in the config file, some key errors occurs as below:

==> Resume model from ./checkpoint/culane_18.pth
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    net.load_state_dict(resume_dict['model'])
  File "/home/zwy/anaconda3/envs/ultra/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for parsingNet:
        Missing key(s) in state_dict: "aux_header2.0.conv.weight", "aux_header2.0.bn.weight", "aux_header2.0.bn.bias", "aux_header2.0.bn.running_mean", "aux_header2.0.bn.running_var", "aux_header2.1.conv.
weight", "aux_header2.1.bn.weight", "aux_header2.1.bn.bias", "aux_header2.1.bn.running_mean", "aux_header2.1.bn.running_var", "aux_header2.2.conv.weight", "aux_header2.2.bn.weight", "aux_header2.2.bn.bias
", "aux_header2.2.bn.running_mean", "aux_header2.2.bn.running_var", "aux_header2.3.conv.weight", "aux_header2.3.bn.weight", "aux_header2.3.bn.bias", "aux_header2.3.bn.running_mean", "aux_header2.3.bn.runn
ing_var", "aux_header3.0.conv.weight", "aux_header3.0.bn.weight", "aux_header3.0.bn.bias", "aux_header3.0.bn.running_mean", "aux_header3.0.bn.running_var", "aux_header3.1.conv.weight", "aux_header3.1.bn.w
eight", "aux_header3.1.bn.bias", "aux_header3.1.bn.running_mean", "aux_header3.1.bn.running_var", "aux_header3.2.conv.weight", "aux_header3.2.bn.weight", "aux_header3.2.bn.bias", "aux_header3.2.bn.running
_mean", "aux_header3.2.bn.running_var", "aux_header4.0.conv.weight", "aux_header4.0.bn.weight", "aux_header4.0.bn.bias", "aux_header4.0.bn.running_mean", "aux_header4.0.bn.running_var", "aux_header4.1.con
v.weight", "aux_header4.1.bn.weight", "aux_header4.1.bn.bias", "aux_header4.1.bn.running_mean", "aux_header4.1.bn.running_var", "aux_combine.0.conv.weight", "aux_combine.0.bn.weight", "aux_combine.0.bn.bi
as", "aux_combine.0.bn.running_mean", "aux_combine.0.bn.running_var", "aux_combine.1.conv.weight", "aux_combine.1.bn.weight", "aux_combine.1.bn.bias", "aux_combine.1.bn.running_mean", "aux_combine.1.bn.ru
nning_var", "aux_combine.2.conv.weight", "aux_combine.2.bn.weight", "aux_combine.2.bn.bias", "aux_combine.2.bn.running_mean", "aux_combine.2.bn.running_var", "aux_combine.3.conv.weight", "aux_combine.3.bn
.weight", "aux_combine.3.bn.bias", "aux_combine.3.bn.running_mean", "aux_combine.3.bn.running_var", "aux_combine.4.weight", "aux_combine.4.bias".

when i set the "finetune" value in the config file, it seems no finetune from the base model but train from scratch. 
what's the difference between the key "finetune" and "resume" ?

**Comment by cfzd** [comment]
@zwyzwy 
In our code, finetune actually only borrows the weight from the backbone network, while the resume will load all weights from previous training states, including the states of the optimizer. 

By the way, I also fixed a bug of resume code. Now resume could load optimizer states correctly.

**Comment by zwyzwy** [comment]
I use your new code to resume the model, the same error occurs.

**Comment by cfzd** [comment]
@zwyzwy 
If you want to finetune your model from the `culane_18.pth`, you should use it in the finetune mode, not the resume mode. 

The resume mode is only suitable for this situation: You have trained some models like `ep01.pth`, ... ,`epxx.pth`. Then you can resume the training from any models in `ep01.pth`, ... ,`epxx.pth`.

The `culane_18.pth` only contains the trained classification weight used for inference. Other weights like auxiliary segmentation weights and optimizer weights are not included. So you can't resume the training from `culane_18.pth`.
