### ISSUE TITLE
About demo.py ?

### ISSUE THREAD

**Issue by china56321** [cfzd/Ultra-Fast-Lane-Detection#30]
I use this command to visualize result : python3 demo.py --test_model model/culane_18.pth --test_work_dir ./tmp
but something wrong happend.

 File "/home/make/Ultra-Fast-Lane-Detection/utils/config.py", line 26
    ex = AttributeError(f"'{self.__class__.__name__}' object has no "                                                                                                 ^
SyntaxError: invalid syntax

 How can i solve this problem ?

**Comment by cfzd** [comment]
@china56321 
Please run demo.py using
```
python demo.py configs/culane.py --test_model model/culane_18.pth 
```

P.S After visualization, remember to clean these videos or these videos will be copied to the work_dir when training.
