### ISSUE TITLE
`pip install sklearn` is deprecated

### ISSUE THREAD

**Issue by kevininderhees** [cfzd/Ultra-Fast-Lane-Detection#324]
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/85eda710482eebe1a48f90316de7cfec7399bbf3/requirements.txt#L5
should be `scikit-learn`

see https://pypi.org/project/sklearn/

**Comment by cfzd** [comment]
@kevininderhees 
thanks for your comment.

**Comment by kevininderhees** [comment]
Thanks for the quick response!
