### ISSUE TITLE
evaluation模块

### ISSUE THREAD

**Issue by xiaobaiheng** [cfzd/Ultra-Fast-Lane-Detection#331]
大佬你好！我想知道为什么culane的evaluation模块实现与Tusimple非常不同，为什么要用c++实现呢

**Comment by cfzd** [comment]
@xiaobaiheng 
因为CULane数据集的作者是这样规定他们的官方评估工具的，所以我们就遵循了这一方式，具体可以参看SCNN这篇文章及其相关的开源库。

**Comment by xiaobaiheng** [comment]
谢谢大佬！
