### ISSUE TITLE
测试集精度很低

### ISSUE THREAD

**Issue by xiaobaiheng** [cfzd/Ultra-Fast-Lane-Detection#332]
你好，我在跑tusimple测试集debug模式中看代码的过程中发现代码在执行到这一步时，发现结果很相近，我的batchsize是1， lane = [int(round((loc + 0.5) * 1280.0 / (griding_num - 1))) if loc != griding_num else -2 for loc in out_i]，输出结果为651, 643, 640, 645, 643, 650, 646, 634, 641, 640, 645, 649, 638, 650, 650, 641, 642, 647, 645, 654, 641, 645, 648, 649, 645, 660, 638, 636, 650, 638, 650, 647, 647, 652, 642, 649, 645, 647, 648, 655, 654, 654, 646, 660, 658, 643, 645, 661, 655, 635, 647, 649, 632, 639, 651, 647]，全部集中在一个很集中的地方，它的loc输出是这个图片
![111111](https://user-images.githubusercontent.com/126633278/229394997-3690e716-0735-44b3-bfcd-15037d9145e9.png)
基本每一次随机读到的图片它的最后网络输出都是如上图同样的值，导致最后测试集跑完我得准确率只有3.7%，不知道到底哪里出现了问题。求大佬解答

**Comment by cfzd** [comment]
@xiaobaiheng 
请问问题解决了吗？

**Comment by xiaobaiheng** [comment]
已经解决了！
