### ISSUE TITLE
Where do you predict category on Culane dataset?

### ISSUE THREAD

**Issue by zillur01** [cfzd/Ultra-Fast-Lane-Detection#336]
I see you can predict on lane location using the following line and some post processing. But in Culane dataset, beside location, you predict on 9 categories too. Where is the network output code for that.?

https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/353df107756b8c03c22c27201e33fc63d84ecfe6/model/model.py#L90

**Comment by cfzd** [comment]
@zillur-av 
We don't predict the category. CULane provides the list files of each category, so we can test on each category.

**Comment by zillur01** [comment]
Ok. So, if I understand correctly, you tack an image, let's say `night` category, and if the model can detect lanes on that image, you say it is detecting `night` category, something like that.

**Comment by cfzd** [comment]
@zillur-av 
Yes. CULane provides a list file containing all the images in the night category. We read all the images in the list, and eval on these images. The evaled results are the result of this category. It is the same for other categories like shadow, dazzle, etc.
