### ISSUE TITLE
how to train in windwos10?

### ISSUE THREAD

**Issue by jianghongsun** [cfzd/Ultra-Fast-Lane-Detection#34]
hi,Thank you for sharing.And how to train in  windows10.  This step  d. Install CULane evaluation tools.
Wait for your recovery in your spare time.

**Comment by cfzd** [comment]
@jianghongsun 
You can refer to [this question](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows).

Also, there is also an alternative, using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or WSL2.

**Comment by cfzd** [comment]
@jianghongsun 
We now support windows make, please see the newly uploaded `INSTALL.md`.

**Comment by jianghongsun** [comment]
ok，Thanks
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 下午5:22
收件人: "cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;; 
抄送: "孙江宏"<1456098533@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [cfzd/Ultra-Fast-Lane-Detection] how to train in windwos10? (#34)





 
@jianghongsun
 We now support windows make, please see the newly uploaded INSTALL.md.
