### ISSUE TITLE
 worse visualization with pretrained model on my own test video

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#37]
![aa](https://user-images.githubusercontent.com/30924021/87271133-e3c37500-c504-11ea-94f7-8f2ce57f8d9e.jpg)
右侧的车道线检测缺失？
![aa2](https://user-images.githubusercontent.com/30924021/87271137-e625cf00-c504-11ea-9820-5cbf1c210630.jpg)
遇到斑马线时，直接检测不到车道了？

**Comment by cfzd** [comment]
@gneworld 
First, the model is not trained on your data, so the performance might be poor on your data. It is a common problem in deep learning, you may refer to [this issue](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/17). This also why we need to study domain adaption and transfer learning.

Second, in the annotation of CULane, all lanes in the image with crossroads ***are not annotated***. So the model ***behaves the same*** as the dataset.
