### ISSUE TITLE
关于在自己数据集上训练

### ISSUE THREAD

**Issue by ylc2580** [cfzd/Ultra-Fast-Lane-Detection#38]
大佬你好，
我现在训练用的数据集是按照culane数据集的格式弄好的。包括
（1）jpg和seg两个文件夹，其中seg中的图片从左到右的车道线标签依次为1,2,3,4。jpg中放的是原图，seg中放的是有标签的二值图。
（2）train.txt中有两列（区别于culane数据集的train_gt.txt的是，官方的后面多了四个值，其含义应该是四个车道线的有无，我看您的代码中未涉及读取这部分，自己的数据集也就未加入，还有就是culane数据集中会有.lines.txt文件，即seg图中的点坐标，这个应该是测试用的，和训练无关）；
以上是数据准备部分，自己训练是在您的culane数据集训练的模型的基础上训练以及完全重新训练两种，训练之后，两种方式的loss都可正常收敛，由于自己的数据集只有2000多，大概30epoch之后，loss会稳定在1左右，top1会在60%左右，问题是，效果感觉是错的，显示的车道线虽然稳定，但感觉预测的车道线的消失点时错的，因为非常靠近图像底端（一般情况下，消失点接近图像的上端）。大佬能否给些建议呢？
另：自己的图像分辨率是1080p，直接输入网络进行训练的。

**Comment by cfzd** [comment]
@ylc2580 
Please refer to [this issue](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/22).

**Comment by Ymec** [comment]
@ylc2580  你好，我按照你的方式生成了自己的culane格式数据集，但是训练的时候出现了问题，不知道你的这句：seg中放的是有标签的二值图是什么意思。我在seg中存放的只有画出车道线的二值图。

**Comment by 1025608032** [comment]
请问我用labelme标注的图片，生成数据集以后怎么样才能拿来训练呢

**Comment by miao02830** [comment]
您好，我想请教一下，您是怎样将自己的数据集转换成culane格式的，是利用作者提供的seg_label_generater这个代码吗？想请教一下您，用这个代码生成的车道线标签图都是黑的，您怎么解决这个问题的？谢谢
