### ISSUE TITLE
CLion 的 CMakeLists.txt 该怎么写？

### ISSUE THREAD

**Issue by chaotianjiao** [cfzd/Ultra-Fast-Lane-Detection#39]
大佬你好~很感谢你的分享，现在有个问题，我是win10系统，但是用的CLion 和MingGW,没有用vs2017,那下面这段代码该怎么改一下呢？
```
mkdir build-vs2017
cd build-vs2017
cmake .. -G "Visual Studio 15 2017 Win64"
cmake --build . --config Release  
# or, open the "xxx.sln" file by Visual Studio and click build button
move culane_evaluator ../evaluate
```
我尝试把cmake .. -G "Visual Studio 15 2017 Win64" 改成  cmake .. -G "MinGW Makefiles" 就报错了：
CMake Error: The source directory "D:/PycharmProjects/Ultra-Fast-Lane-Detection/evaluation/culane" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
我是要自己写个CMakeLists.txt吗？
另外我的win10系统已经用MingGW 和 Cmake编译好了一版OpenCV4.3.0，可以直接配置到这个项目中吗？
（这个项目用Pycham打开的）

**Comment by cfzd** [comment]
@chaotianjiao 
If you have built the OpenCV, I think you could directly compile with the Option 1 via MinGW make.

**Comment by chaotianjiao** [comment]
执行make的时候
```
CXX src/counter.cpp
In file included from include/lane_compare.hpp:4,
                 from include/counter.hpp:4,
                 from src/counter.cpp:8:
include/spline.hpp:6:10: fatal error: opencv2/core.hpp: No such file or directory
 #include <opencv2/core.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: build/src/counter.o] Error 1
```
大佬，我的环境变量里有OpenCV，为什么还是找不到？

**Comment by cfzd** [comment]
@chaotianjiao 
I think it's the problem of include path and lib path. You can either modifie the environment variables of `CPLUS_INCLUDE_PATH` and  `LIBRARY_PATH` to make them contain OpenCV C++ or you can directly assign the path to mingw make via `-I your_opencv_incldue_path` and `-L your_opencv_lib_path`.

**Comment by chaotianjiao** [comment]
大佬，运行 demo.py  configs/culane 说没有权限，
```
Traceback (most recent call last):
  File "D:/PycharmProjects/Ultra-Fast-Lane-Detection/demo.py", line 14, in <module>
    args, cfg = merge_config()
  File "D:\PycharmProjects\Ultra-Fast-Lane-Detection\utils\common.py", line 50, in merge_config
    cfg = Config.fromfile(args.config)
  File "D:\PycharmProjects\Ultra-Fast-Lane-Detection\utils\config.py", line 159, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "D:\PycharmProjects\Ultra-Fast-Lane-Detection\utils\config.py", line 85, in _file2dict
    shutil.copyfile(filename,
  File "D:\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\FENG~1.YUZ\\AppData\\Local\\Temp\\tmpmrlvzi1a\\tmpiyeklgxy.py'
```

**Comment by cfzd** [comment]
@chaotianjiao 
Try to run pycharm as administrator.

**Comment by chaotianjiao** [comment]
试过了，还是不行~

**Comment by cfzd** [comment]
I remembered @wohaiyo have the same problem in #4, can you find anything different?

**Comment by wohaiyo** [comment]
@chaotianjiao I solved this problem by modifying the 'config.py', like this:
       `
        if filename.endswith('.py'):
            # ------------ Use the user defined config module---------------
            temp_module_name = filename.split('\\')[-2] + '.' + filename.split('\\')[-1].replace('.py', '')   # modify to 'config.myculane'
            mod = import_module(temp_module_name)
            cfg_dict = {
                name: value
                for name, value in mod.__dict__.items()
                if not name.startswith('__')
            }
            # ---------------------------
            # with tempfile.TemporaryDirectory() as temp_config_dir:
            #     temp_config_file = tempfile.NamedTemporaryFile(
            #         dir=temp_config_dir, suffix='.py')
            #     temp_config_name = osp.basename(temp_config_file.name)
            #     shutil.copyfile(filename,
            #                     osp.join(temp_config_dir, temp_config_name))
            #     temp_module_name = osp.splitext(temp_config_name)[0]
            #     sys.path.insert(0, temp_config_dir)
            #     mod = import_module(temp_module_name)
            #     sys.path.pop(0)
            #     cfg_dict = {
            #         name: value
            #         for name, value in mod.__dict__.items()
            #         if not name.startswith('__')
            #     }
            #     # delete imported module
            #     del sys.modules[temp_module_name]
            #     # close temp file
            #     temp_config_file.close()
`

**Comment by wohaiyo** [comment]
@chaotianjiao I solved this problem by modifying the 'config.py', like this: 

    def _file2dict(filename):
        filename = osp.abspath(osp.expanduser(filename))
        if filename.endswith('.py'):
            # ------------ Use the user defined config module---------------
            temp_module_name = filename.split('\\')[-2] + '.' + filename.split('\\')[-1].replace('.py', '')   # modify to 'config.myculane'
            mod = import_module(temp_module_name)
            cfg_dict = {
                name: value
                for name, value in mod.__dict__.items()
                if not name.startswith('__')
            }
            # ---------------------------
            # with tempfile.TemporaryDirectory() as temp_config_dir:
            #     temp_config_file = tempfile.NamedTemporaryFile(
            #         dir=temp_config_dir, suffix='.py')
            #     temp_config_name = osp.basename(temp_config_file.name)
            #     shutil.copyfile(filename,
            #                     osp.join(temp_config_dir, temp_config_name))
            #     temp_module_name = osp.splitext(temp_config_name)[0]
            #     sys.path.insert(0, temp_config_dir)
            #     mod = import_module(temp_module_name)
            #     sys.path.pop(0)
            #     cfg_dict = {
            #         name: value
            #         for name, value in mod.__dict__.items()
            #         if not name.startswith('__')
            #     }
            #     # delete imported module
            #     del sys.modules[temp_module_name]
            #     # close temp file
            #     temp_config_file.close()
        elif filename.endswith(('.yml', '.yaml', '.json')):
            import mmcv
            cfg_dict = mmcv.load(filename)
        else:
            raise IOError('Only py/yml/yaml/json type are supported now!')

**Comment by chaotianjiao** [comment]
@wohaiyo  Thanks! It works!
