### ISSUE TITLE
ModuleNotFoundError: No module named 'evaluation.eval_wrapper'; 'evaluation' is not a package

### ISSUE THREAD

**Issue by Vipermdl** [cfzd/Ultra-Fast-Lane-Detection#41]
Hi, bro.

I'm appreciated for your work on lane detection. when I run test.py, I found this error:

(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane$ ls
calTotal.m  CMakeLists.txt  evaluate  include  Makefile  run.sh  src
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane$ mkdir build
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane$ cd build/
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /home/leadmove/anaconda3/envs/pytorch (found version "3.4.2") found components:  core highgui imgproc imgcodecs
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Building with OpenMP
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build$ make
Scanning dependencies of target culane_evaluator
[ 20%] Building CXX object CMakeFiles/culane_evaluator.dir/src/spline.cpp.o
[ 40%] Building CXX object CMakeFiles/culane_evaluator.dir/src/counter.cpp.o
[ 60%] Building CXX object CMakeFiles/culane_evaluator.dir/src/lane_compare.cpp.o
[ 80%] Building CXX object CMakeFiles/culane_evaluator.dir/src/evaluate.cpp.o
[100%] Linking CXX executable culane_evaluator
[100%] Built target culane_evaluator
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  culane_evaluator  Makefile
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build$ mv culane_evaluator ../evaluate
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane/build$ cd ..
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane$ ls
build  calTotal.m  CMakeLists.txt  evaluate  include  Makefile  run.sh  src
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation/culane$ cd ..
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection/evaluation$ cd ..
(pytorch) leadmove@leadmove-PowerEdge-T630:/mnt/SDC/madongliang/Ultra-Fast-Lane-Detection$ python test.py configs/my_culane.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from evaluation.eval_wrapper import eval_lane
ModuleNotFoundError: No module named 'evaluation.eval_wrapper'; 'evaluation' is not a package

Do you know what is the problem?

Thank you

**Comment by cfzd** [comment]
@Vipermdl 
It seems just a python import problem and has no connection with CULane evaluation tool.

Please run following command and see which step goes wrong:
```
# make sure you are in Ultra-Fast-Lane-Detection/

python
# start an interactive session of python

>>> import evaluation
>>> print(evaluation.__path__)
# you should be able to import evaluation package

>>> import evaluation.eval_wrapper
>>> print(dir(evaluation.eval_wrapper))
# you should also be able to import eval_wrapper

>>> from evaluation.eval_wrapper import eval_lane
# you should be able to import lane
```

If any of these steps goes run, please provide the error message.

**Comment by Vipermdl** [comment]
Thanks! I add __init__.py to the evaluation folder, it is working.

**Comment by cyj22835373** [comment]
maybe you have import another module named as evaluation
