### ISSUE TITLE
如何提高CULane训练出来的model F1-score 

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#42]
感谢大佬的开源精神，另有两个问题期待大佬的解惑，Thanks♪(･ω･)ﾉ
![image](https://user-images.githubusercontent.com/30924021/87636186-ecb97e00-c772-11ea-80c9-e35fa6586dd1.png)

1. 为什么 CULane训练出来的model F1-score比 Tusimple低这么多？
2. 如何提升CULane训练出来的model F1-score ？

**Comment by cfzd** [comment]
Different datasets have different metrics and the difficulties are also different.
