### ISSUE TITLE
typeerror:expecting sr, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by xiaozi-ML** [cfzd/Ultra-Fast-Lane-Detection#43]
Hi, bro.

I'm appreciated for your work on lane detection. when I run train.py, I found this error:

on$ **python train.py configs/culane. py**
Traceback (most recent call last):
File "train.py", line 100, in <module>
work_ dir = get work_ dir(cfg)
File”/home/gpu/Documents/test/Ultra- Fast-Lane- Detection/utils/common.py", line 97, in get_ work_ dir
work_ dir = oS. path. join(cfg. log_ path, now + hyper_ param str + cfg. note)
File " /home/gpu/ anaconda3/envs/Lane_ det/1ib/python3. 7/posixpath.py", line 80 , in join a = os.fspath(a)
**TypeError: expected str, bytes or oS . PathLike object, not NoneType**

Do you know what is the problem?

Thank you

**Comment by xiaozi-ML** [comment]
I could successfully run the demo.py and test.py.

**Comment by cfzd** [comment]
@xiaozi-ML 
As the error message says, a `NoneType` object is passed to `os.path.join` function. There two objects passed to the function, which are `cfg.log_path` and `now + hyper_param_str + cfg.note`. You can set up a break point in here and check which one is `NoneType`.

**Comment by xiaozi-ML** [comment]
the problem is log_path=None，  thx
