### ISSUE TITLE
Other trained models

### ISSUE THREAD

**Issue by ZhenpengChenCode** [cfzd/Ultra-Fast-Lane-Detection#46]
Thanks you for your contribution.

Can you shared more trained models?

**Comment by cfzd** [comment]
@ZhenpengChenCode 
Sorry, we are now working on a new project. Extra effort and time will not be put in this project further. If you want to get other models, you can train it by yourself since our code supports the training of other backbones.

**Comment by ZhenpengChenCode** [comment]
@cfzd Got it. Thanks a lot.
