### ISSUE TITLE
caffe model

### ISSUE THREAD

**Issue by Jade999** [cfzd/Ultra-Fast-Lane-Detection#48]
Hi, thanks for your great work! I have convert your model [trained on _CULane_] to **caffe**, and it may be usefull to some others! Please link it to your repo, if you think it is usefull too.
**My repo.**  [https://github.com/Jade999/caffe_lane_detection](https://github.com/Jade999/caffe_lane_detection.)
thank you very much!

**Comment by cfzd** [comment]
@Jade999 
Thanks for your contribution. We will add the link to the `README.md`.
