### ISSUE TITLE
关于训练tusimple、CULane数据集

### ISSUE THREAD

**Issue by lzcchl** [cfzd/Ultra-Fast-Lane-Detection#50]
您好，非常感谢您的工作，都是作为您的代码的使用者，一定也有许多人特别关心如何训练出一个好的模型~

首先，是官方数据集的训练，对于CULane数据集，可以直接使用其list/train_gt.txt文件，但对于tusimple数据集，其数据集提供的是类似于label_data_0531.json的真值文件，但是您的代码中是如下图所示来导入数据的，相信也有人一样不知道tusimple数据集训练时train_gt.txt内容应该是什么，是和CULane数据集的list/train_gt.txt内容类似吗（就是每一行包括原始图+真值图+0 1 1 1）？如果是，那么如何用tusimple数据集去生成这个train_gt.txt呢？如果不是，那么请教一下您这个train_gt.txt内容是什么呢？

![0](https://user-images.githubusercontent.com/34515022/88247865-e2970280-ccd1-11ea-8042-dbc7694a1cd5.png)

**Comment by cfzd** [comment]
@lzcchl 
Please see `INSTALL.md`. In the section of `5. Data preparation`, the generation of `train_gt.txt` is described.
