### ISSUE TITLE
关于自己的数据测试问题

### ISSUE THREAD

**Issue by sglshanghai** [cfzd/Ultra-Fast-Lane-Detection#51]
你好，非常感谢您的贡献，我最近在测试您的模型，在culane数据集上效果挺棒的，但是自己的数据测试效果不太好，使用的是culane_18.pth，测试的图片也已经改成和culane数据集一样的分辨率，请问测试自己的数据的话还要注意哪些细节吗

**Comment by cfzd** [comment]
@sglshanghai 
Please refer to these two issues: #17 and #22.
