### ISSUE TITLE
关于constant.py

### ISSUE THREAD

**Issue by ylc2580** [cfzd/Ultra-Fast-Lane-Detection#54]
你好，
我看您的代码里culane_row_anchor = [121, 131, 141, 150, 160, 170, 180, 189, 199, 209, 219, 228, 238, 248, 258, 267, 277, 287]这个并不是严格的间隔为10，后期利用这个计算车道线坐标时候会不会产生误差？还是咱们这样设置有什么考虑呢？

**Comment by cfzd** [comment]
@ylc2580 
It is basically from [scnn](https://github.com/XingangPan/SCNN/blob/fc09fa5435e6818da4e9ba7c4b4881ab26093c8c/tools/prob2lines/getLane.m#L6).

**Comment by ylc2580** [comment]
好的，谢谢回复



---原始邮件---
发件人: "cfzd"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 凌晨0:17
收件人: "cfzd/Ultra-Fast-Lane-Detection"<Ultra-Fast-Lane-Detection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ylc2580"<403658190@qq.com&gt;;
主题: Re: [cfzd/Ultra-Fast-Lane-Detection] 关于constant.py (#54)




 
@ylc2580
 It is basically from scnn.
