### ISSUE TITLE
problem about C×h×(w+1)

### ISSUE THREAD

**Issue by fenling** [cfzd/Ultra-Fast-Lane-Detection#56]
hi cfzd:
     after read your paper, i don't understand (w+1). "(w+1)-dimensional  classification  instead  of w-dimensional  one  is  that  an  extra dimension is used to indicate the absence of lane".
    w+1 just mean the horizontal direction grid,eg:w=5，
    i*j*(w+1) may be 0.2 0.2 0.1 0.3 0.2 0.1
    how it means the absence of lane, can you give me a example?

**Comment by cfzd** [comment]
@fenling 
We can use an example to show this. Suppose `*` represents the location of the lane, `-` represents the background, and w=7.

For a row like this: `---*---`, the one-hot ground truth is `0001000 0`.
For a row like this: `-------`, the one-hot ground truth is `0000000 1`.

I added a space for better visualization.  The one hot ground truth is (7+1)-dimensional. 

The last dimension is used for classification of "no lane", while the previous dimensions are used for localization of lane.

**Comment by fenling** [comment]
thank you ,i get it.
