### ISSUE TITLE
Why is the .pth file size different when testing?

### ISSUE THREAD

**Issue by skek0624** [cfzd/Ultra-Fast-Lane-Detection#57]
When I trained, I got a learning model of 775.6mb. However, the trained model posted on github is 245mb.(tusimple config-use aux = True).

I wonder how the model was obtained, except for the use_aux part.

I think it was converted to pb file via onnx.

Thank you for your research.

**Comment by cfzd** [comment]
@skek0624 
For the size of the model:
The training model files include weights of backbone, classification branch, auxiliary segmentation branch, and optimizer. The posted models removed the weights of auxiliary segmentation branch and optimizer, so it is smaller.
