### ISSUE TITLE
数据集融合训练

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#58]
感谢大佬的工作，请问下是否可以把tusimple数据集转换成culane数据集的格式，然后把融合后的两个数据集放在一起用culane的配置进行训练，以此来解决单独训练culane数据集无法识别斑马线和曲线车道不稳的问题？期待大佬的回复，谢谢

**Comment by cfzd** [comment]
@gneworld 
Yes, you can merge the two datasets by combining the list file `train_gt.txt` of them. 

But I don't think you can solve the problems. The number of training samples of CULane is 88,880, while the number of Tusimple is only 3,268.  

The number of Tusimple might be too small to affect the final results.

**Comment by gneworld** [comment]
thanks much @cfzd
