### ISSUE TITLE
The 10 means column size of CULane which can be seen in data/constant.py and 4 is the corresponding size of Tusimple. This " column size" should be row size, am I right?

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#59]
The 10 means column size of CULane which can be seen in data/constant.py and 4 is the corresponding size of Tusimple. This " column size" should be row size, am I right?

_Originally posted by @gneworld in https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/22#issuecomment-668444698_

**Comment by fornote** [comment]
yes, it's the distance of two rows.
