### ISSUE TITLE
Can it distinguish different lanes?

### ISSUE THREAD

**Issue by jinfagang** [cfzd/Ultra-Fast-Lane-Detection#61]
Can it predicts which lane is which ?

**Comment by cfzd** [comment]
@jinfagang 
Yes. Our method could distinguish different lanes. The output of our method is `C`-channel, and each channel corresponds to a specific lane, i.e., left-most lane, left lane, right lane, and right-most lane.

**Comment by jinfagang** [comment]
thanks!
