### ISSUE TITLE
About flip operation in post process

### ISSUE THREAD

**Issue by jinfagang** [cfzd/Ultra-Fast-Lane-Detection#62]
There were some codes like:
```
out_j = out_j[:, ::-1, :]
```
Just wonder why flip the output tensor along axis 1?

**Comment by cfzd** [comment]
@jinfagang 
It is just for making the order the same as this line:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/0b17e5d62971540fcf605001d0a33a01f3d5c5f2/demo.py#L89

You can also just leave it and change the order ,i.e. `k`, in the above code.

**Comment by jinfagang** [comment]
@cfzd  Flip or not flip doesn't change the out_j shape, am I right? I think this is the order of w and h is swaped?

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/89749865-27a59c00-dafc-11ea-96a6-380a91867053.png)

what else need to edit if skip this flip operation?

**Comment by gneworld** [comment]
@jinfagang  can you share the idea that how to make lanes tightly? thanks

**Comment by jinfagang** [comment]
@gneworld I forgot... the x cordinates calculate had a little bias.
