### ISSUE TITLE
网络模型

### ISSUE THREAD

**Issue by fayu-ma** [cfzd/Ultra-Fast-Lane-Detection#64]
你好，请问你用的网络是什么啊

**Comment by cfzd** [comment]
@fayu-ma 
It is ResNet.

**Comment by fayu-ma** [comment]
![image](https://user-images.githubusercontent.com/49139617/89783791-1e432080-db4a-11ea-9afb-b57df7f22cd6.png)
你好，请问在pycharm下运行的时候。运行train报错，config文件指的是哪一个啊，

**Comment by fayu-ma** [comment]
你好，能加一下你的微信吗或者邮箱

**Comment by cfzd** [comment]
My email address: zequnqin@gmail.com
