### ISSUE TITLE
How to fine-tune pretrained model

### ISSUE THREAD

**Issue by Metal-joker** [cfzd/Ultra-Fast-Lane-Detection#67]
I have a dataset need to detect the lane, but the resolution of images in this dataset is not the same as Tusimple Dataset, so pretrained model didn't work well. therefore I want to fine-tune the pretrained model with my own dataset, how should I get started? Any help would be appreciated.

**Comment by cfzd** [comment]
@Metal-joker 
I think you have to prepare your dataset first. The fastest way is to convert it to a segmentation dataset like CULane, then you can finetune the model.
