### ISSUE TITLE
The order of lane label

### ISSUE THREAD

**Issue by xmba15** [cfzd/Ultra-Fast-Lane-Detection#70]
Hi. Thank you for the paper and the code.
I am trying to test this method on a new dataset and have a question I would like to consult.
suppose I label lanes for the road, with number of lanes C = 6 for example, and from the left to right side of the image, I have lane1, lane2, lane3, lane4, lane5, lane6.
Can I have random labels for the lane. For example, label lane1 with number 2, lane2 with number 4, lane3 with number 1?
Or I have to keep the order of the label for the lane, i.e starting from the leftmost, lane i with label i.

**Comment by JiayiLy** [comment]
I don't think the order matters cause every lane is independent from each other in the output. We only need to keep all the pixels of a lane's mask in gt has the same and unique value?

**Comment by cfzd** [comment]
@xmba15 
The relative order is not important. But once the order is determined, all the images should follow the same order. For example, if a nearest left lane is lane #1 in a images, then all the nearest left lanes shoule be lane #1. 
**You have to use the same order or protocol for all images.**

**Comment by JiayiLy** [comment]
@cfzd 
Hi, can you please explain the principle behind this contraint? I mean why we need to  use the same order or protocol for all images. I haven't find any cue in your code. Isn't every image used for training independent from each other?

**Comment by xmba15** [comment]
![order](https://user-images.githubusercontent.com/18694765/90316337-77e98780-df5c-11ea-873d-e1886dee8204.png)
I think the determined order is learned with the output tensor of Cxhx(w+1)

**Comment by cfzd** [comment]
@JiayiLy 
For example, in some images, a certain output neural is optimized to learn the location of **left lanes**, while in other images, the certain output neural is optimized for **right lanes**, if the order of lanes is not the same for all images. In this case, the learning target is always changing and the network cannot converge.

**Comment by JiayiLy** [comment]
I got it. The lane index in the output tensor is fixed so we need to use the same order or protocol for all images.

**Comment by xmba15** [comment]
@cfzd Thank you very much for making things clear.
@JiayiLy If you are okie, I will close this issue.
