### ISSUE TITLE
Test.py

### ISSUE THREAD

**Issue by fayu-ma** [cfzd/Ultra-Fast-Lane-Detection#71]
您好，运行test文件后输出的两个txt文件内容是什么啊

**Comment by cfzd** [comment]
@fayu-ma 
which two text files?

**Comment by fayu-ma** [comment]
![image](https://user-images.githubusercontent.com/49139617/90324482-f4528980-dfa1-11ea-9be7-0740cf2cc629.png)

**Comment by cfzd** [comment]
@fayu-ma 
It is the detection results on the Tusimple test set.  It will be passed to the Tusimple eval tool to get the results.
