### ISSUE TITLE
sim Loss and shp Loss

### ISSUE THREAD

**Issue by normandra** [cfzd/Ultra-Fast-Lane-Detection#74]
First of all amazing job with the paper!

In your paper it is mentioned that the loss coefficients for all parameters are set to 1 but in this repo for Culane both sim and shp loss are zero and for tusimple shp loss are zero. Is there an explanation for this that I missed?

**Comment by normandra** [comment]
oops sorry I just saw the Issue about this

**Comment by longzeyilang** [comment]
@cfzd @normandra For culane, how to set sim and shp loss weight?
