### ISSUE TITLE
code logical specification

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#75]
hello,  could you tell me the meaning of this code block which is surrounded by red box like this
![image](https://user-images.githubusercontent.com/30924021/91018699-7d149980-e622-11ea-946d-d6a33d91d056.png)

**Comment by cfzd** [comment]
@gneworld 
This part of code corresponds to the data augmentation section in our paper. In general, the code here is to extend the lane to the image boundary after augmentation. There are three kinds of situations we skip this part:
- There is no lane
- The lane already reaches the boundary of the image
- The lane is too short to extend

```
        for i in range(4):
            if np.all(all_idx_cp[i,:,1] == -1):
                continue    

            # if there is no lane

            valid = all_idx_cp[i,:,1] != -1                   # get all valid lane points' index
            valid_idx = all_idx_cp[i,valid,:]                 # get all valid lane points
            if valid_idx[-1,0] == all_idx_cp[0,-1,0]:    
                # if the last valid lane point's y-coordinate is already the last y-coordinate of all rows
                # this means this lane has reached the bottom boundary of the image
                # so we skip
                continue

            # if the lane already reaches the boundary of the image

            if len(valid_idx) < 6:
                continue

            # if the lane is too short to extend
```

**Comment by gneworld** [comment]
@cfzd thanks very much
