### ISSUE TITLE
A question about the decoding in demo.py

### ISSUE THREAD

**Issue by Happy-Carrot** [cfzd/Ultra-Fast-Lane-Detection#77]
Hi proferssor,

I can't understand a step in the decoding in demo.py, when I was trying to use your model to apply on my dataset. Would you mind to explain for me? 
![image](https://user-images.githubusercontent.com/43030596/91448313-48b40e00-e8ac-11ea-8097-230447b27ded.png)

Why should the prob multiply the idx for the location in X axis? I really can't understand the step below based on this multiplication.

ppp = (int(out_j[k, i] * col_sample_w * img_w / 800) - 1, int(img_h * (row_anchor[cls_num_per_lane-1-k]/288)) - 1 ) 

Hope your reply sincerely!
@cfzd

**Comment by cfzd** [comment]
@Happy-Carrot 
`prob` is a `num_gridding x num_row_anchors x num_lanes` tensor containing the probability of each location. The most intuitive way is to directly use `argmax` and obtain the location like this:
```
loc = np.argmax(prob, axis = 0)
```
Then `loc` would be `num_row_anchors x num_lanes`, and it contains the location for each lane on each row anchor.

But we could have a better solution. Since we have the probability of each location, we can get a more precise location than directly using `argmax`. 

Suppose we have two locations `[39,40]`, and the probability of `[39,40]` is `[0.2,0.8]`. If we use `argmax`, we would get the location of `40` since the probability of `40` is `0.8`. but we can also get a value:`39*0.2 + 40*0.8 = 39.8`, which is more precise than `argmax`.  That's why we use multiplication to get the location.

For the `ppp` part, it's just a simple scale to fit the resolution of the original image.

**Comment by Happy-Carrot** [comment]
Thank you so much! I comprehend it and admire your design really.

By the way, I use your model to train my own dataset, which set the `num_lanes` is 6 and got the top 1 accuracy in 0.91. Then I found some problem as the pic below, when I try a simple test.

This result show the powerful ability of your model, but it still has some flaws in the red circle.
![image](https://user-images.githubusercontent.com/43030596/91518415-c9155600-e922-11ea-9ed1-dd4e765245c8.png)

This result show more flaws as the same.
![image](https://user-images.githubusercontent.com/43030596/91518136-1513cb00-e922-11ea-8d52-f81ff76d848d.png)

In a conclude, the flaw is some point would be far away from the ground truth. And I think it may be optimised if I use the Shape Loss ↓, which weight is 0 in your project.
![image](https://user-images.githubusercontent.com/43030596/91518739-7f793b00-e923-11ea-9e30-bab2b75bcab7.png)
Would you mind to give me some suggestions to train it better? Hope your reply honestly.

**Comment by cfzd** [comment]
@Happy-Carrot 
Sorry for the late response. I think the results are produced by the incorrect number of lanes.

The `num_lanes` is for segmentation, while the third element of `cls_dim` is also the number of lanes for classification. The two variables are duplicated. I have updated a version to solve the duplication. Now you can simply change the `num_lanes` in the config file, you should get the correct results.

Could you also help me test the updated version?

**Comment by Happy-Carrot** [comment]
Thank you for reply. Your amendment is nice, cause I find these variables hard indeed.
I would test the updated version for the following optimization.

**Comment by livvv** [comment]
Recently I am also training on my own data set, and in the process increased the number of lane lines. Your updated version helped me run through my data faster. I also encountered some small bugs in the process, as follows:

1.AttributeError: 'Namespace' object has no attribute 'num_lanes'

you need add " parser.add_argument('--num_lanes', default=None, type=str) " in 'utils/common/ 45'

2. Change the information about the number of lane lines (num_lanes = N, N represents the number of lane lines in your own data set) in 'dataset.py'

class LaneClsDataset(torch.utils.data.Dataset):
    def __init__(self, path, list_path, img_transform = None,target_transform = None,simu_transform = None, griding_num=50, load_name = False, row_anchor = None,use_aux=False,segment_transform=None, num_lanes = N ):

3. Change the information about the number of lane lines ( Metric_mIoU( N+1), N represents the number of lane lines in your own data set ) in 'factory.py':

def get_metric_dict(cfg):
    if cfg.use_aux:
        metric_dict = {
            'name': ['top1', 'top2', 'top3', 'iou'],
            'op': [MultiLabelAcc(), AccTopk(cfg.griding_num, 2), AccTopk(cfg.griding_num, 3), Metric_mIoU(N+1)]


        With the above changes, I can detect a larger number of lane lines. Thank you for your excellent work and positive response.

**Comment by cfzd** [comment]
@livvv 
Great thanks! I'll update the code.
