### ISSUE TITLE
Structual loss for CULane dataset

### ISSUE THREAD

**Issue by dwt189** [cfzd/Ultra-Fast-Lane-Detection#8]
Thank you for your innovative work! I also found [another paper](https://arxiv.org/abs/2005.08630) (E2E-LMD) whose core idea is coincidentally similar to yours, which was published just one month after your paper.

My question is regarding the effectiveness of structural loss (similarity and shape) on CULane dataset. I was able to exactly reproduce the results using ResNet-18 with your suggested settings. When observing the loss curves, however, I found both similarity and shape losses increased a lot while the classification loss continued to decrease after 25 epochs (50 in total). I know they were not optimized because their weights are 0 but there seems to be a certain conflict between them.

I guess that's why you turn off the structural loss in config/culane.py, otherwise the total loss would be hurt. In your paper, the ablation study was performed on the TuSimple dataset and the structural loss did help.

I wonder why it would not work on CULane. Could you share your insights?

**Comment by cfzd** [comment]
@dwt189 
Hi, thanks for your insightful question. The reason behind this is a little tricky. 

+ Similarity loss

    The number of row anchors is different for the two datasets, as you may see [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/data/dataloader.py#L67). The number of row anchors on Tusimple is much larger than the one of CULane (56 v.s. 18). If there are more row anchors, the differences between rows would be less. If the differences between rows are small, optimizing similarity loss could smooth the feature and hence benefit the learning. However, If the differences between rows are too large to handle (i.e. the CULane case), optimizing the loss may lead to inferior performance instead.

+ Shape loss

    For the shape loss, it could work ideally. But there exists the "no lane" case in our pipeline to identify the invalid lanes. In this way, in our pipeline, there are two kinds of classification outputs. It could be the location of the lane, and it could also be the "no lane" case. In general, the classification problem is (n+1)-dimensional, in which the first n dimensions are used for localization and the last one is used for the "no lane" case.

    This kind of design unifies the classification of "no lane" case and lane localization, but it could harm the learning of the shape loss. For the "no lane" case, there is no definition of shape. This is the reason why shape loss would increase in some situations.

In fact, the structural loss works well in some cases, but not in all cases. For simplicity and generality, we turned off the losses. But you could try some tuning with these losses on, you may get something better  : )
