### ISSUE TITLE
Training Time estimate for bigger dataset

### ISSUE THREAD

**Issue by Pei-Yu-Bosch** [cfzd/Ultra-Fast-Lane-Detection#83]
你好,

想问用1080Ti单GPU训练tusimple 的3400张图片用了多久？
我尝试训练用的十万张同尺寸图片，跑了1个小时刚跑完一个epoch。

我是不是要用10个gpu跑10个小时？没这么多资源咋办？

训练好的pth文件是存在log里面吗

多谢！

**Comment by cfzd** [comment]
@Pei-Yu-Bosch 
If you have a very big dataset, I don't think you should use such a big number of epochs. 10 epochs should be fine.
If the results are not satisfying, you can try to increase the number of epochs.

**Comment by Pei-Yu-Bosch** [comment]
好的，我训练了10个epoch，loss=0.3，假如这个loss都是classification的部分，那意味着F1-measure 差不多在70%吗，怎么来解读

**Comment by cfzd** [comment]
@Pei-Yu-Bosch 
I don't know the relationship between F1-measure and loss, especially on your datasets. But I think loss=0.3 is a good sign of convergence. By the way, the `pth` files are trained models.

**Comment by Pei-Yu-Bosch** [comment]
thanks much!
