### ISSUE TITLE
culane的数据集处理

### ISSUE THREAD

**Issue by longzeyilang** [cfzd/Ultra-Fast-Lane-Detection#85]
1、因图片数据需要，把culane数据集裁剪出中间部分，图像大小为1280*590，那个row_anchor保持相同18个；
2、使用默认超参数culane.py，那个shm和shp的损失权重设置为0，进行训练，那个relation_loss和relation_dis损失一直上升，训练25epoch后，检测效果不好
3、有些人提到shm和shp的损失权重分别设置为0.8，0.5，进行训练，那个relation_dis损失下降，relation_loss一直上升，同样检测效果不好

考虑culane的场景比较丰富，加上自己场景组成混合数据集，进行训练，不知道能否达到目的？

**Comment by cfzd** [comment]
@longzeyilang 
For simplicity, you can first try without shape and similarity loss. They can be used to get finer results, but they are not the most important part of our method. 

Can you report the top1, top2, and top3 accuracy in your experiments?

**Comment by longzeyilang** [comment]
top1、top2、top3精度大概是0.67左右，您的权重都是设置0，检测效果很差。你是说使用Rest-18基模型训练还是使用提供culane_18模型进行迁移学习？

**Comment by longzeyilang** [comment]
@cfzd 看过恨过issues，对 shape and similarity loss 的权重都是不确定？论文说都是1，测试后效果都不行，那如何设置该权重数据？

**Comment by cfzd** [comment]
@longzeyilang 
The classification accuracy is low. Can you try with the original CULane dataset and report the top1, top2, and top3 accuracy? As mentioned above, the shape and similarity loss is not that important, you can get good results without them.

**Comment by longzeyilang** [comment]
@cfzd 
图像裁剪后，使用culane_18.pth模型进行迁移学习，结果不理想。现在直接使用ResNet-18进行训练，再看下结果吧

**Comment by longzeyilang** [comment]
@cfzd
使用ResNet18进行训练裁剪后culane（1280*590），loss和top的曲线

**Comment by cfzd** [comment]
@longzeyilang 
The top1 accuracy is nearly 74%, and the top3 accuracy is 92%, which is high. So this means the training is fine, it might be other problems. 
Did you use the same data preprocessing when training and testing?  The basic data preprocessing like resize, crop, and normalize should be the same.

Did your visualization meet the cropped resolution? 

Did the row_anchor is defined according to your input size?

**Comment by longzeyilang** [comment]
是的，那个 row_anchor是没有改变，分辨率进行了修改

**Comment by cfzd** [comment]
那你训练时输入网络的图片大小还是`288x800`吗？如果不是`288x800`，那你就需要修改row_anchor.   row_anchor用来指示在哪些行上检测车道线，因为我们都是用`288x800`进行训练，所以我们的row_anchor是定义在288高度分辨率下的。

**Comment by longzeyilang** [comment]
嗯，可以进行正常检测了

**Comment by DaniloXiao** [comment]
> 嗯，可以进行正常检测了
您好！我训练了很久精度都提不上去，出现了和您刚开始一样的训练错误，我看您训练的结果不错，请问您能分享下训练参数吗？就是sim和shp的损失权重设置为多少，好人一生平安，感激不尽。
