### ISSUE TITLE
用CULane数据集进行测试时,运行test.py脚本之后,出现如下问题:

### ISSUE THREAD

**Issue by luocmin** [cfzd/Ultra-Fast-Lane-Detection#86]
FileNotFoundError: [Errno 2] No such file or directory: '/data1/lcm/ultra_resnet/tmp/txt/out0_normal.txt'
![sendpix1](https://user-images.githubusercontent.com/57932842/92680301-1d75f800-f35d-11ea-8505-cb6091860c67.jpg)

**Comment by cfzd** [comment]
@luocmin 
As the log says: `sh : 1: ./evaluation/culane/evaluate not found`. The `evaluate` is the evaluation tool for CULane. 

You need to compile the tool as step 5 in `INSTALL.md`.
