### ISSUE TITLE
能否共享一下culane_34.pth及tusimple_34.pth

### ISSUE THREAD

**Issue by zhangjy2008327** [cfzd/Ultra-Fast-Lane-Detection#87]
你好，请问是否可以共享一下以上2个权重，以方便对该文章的引用与对比，谢谢。

**Comment by cfzd** [comment]
@zhangjy2008327 
Sorry for the late response. As responses to other issues, we are moving to a project and only do some general maintenance of this repository. You can either directly cite the results from our paper or you can use the results obtained by yourself.
