### ISSUE TITLE
关于论文的一些疑惑

### ISSUE THREAD

**Issue by meanmee** [cfzd/Ultra-Fast-Lane-Detection#88]
为什么构造的二阶差分方程可以限制车道线的形状？

**Comment by cfzd** [comment]
@meanmee 
The general formulation of a line is `Ax + By + C =0`. The first-order difference is `(y1-y2)/(x1-x2) = -B/A`, if `A != 0`. Then the second-order difference of a line is `0`. In this way, if we minimize the second-order difference of the prediction, the results would be more straight. If you can minimize this value to zero, then you get a straight line.

**Comment by meanmee** [comment]
Thanks, If I don't want the constraint,  I should just set beta t zero? I mean  I am encountering a different scene problem, which is the surveillance of the highway, in this case, some lanes are curved.

**Comment by cfzd** [comment]
Yeah, you can directly set the weight to zero.

**Comment by Laulian** [comment]
@meanmee  how about the curved lines?  did they work well？
