### ISSUE TITLE
改变输入分辨率

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#89]
大佬您好，我想把输入分辨率改成400*144，那么 culane_row_anchor = [121, 131, 141, 150, 160, 170, 180, 189, 199, 209, 219, 228, 238, 248, 258, 267, 277, 287] 这些值该如何相应更改，多谢~~

**Comment by cfzd** [comment]
@gneworld 
The original culane_row_anchor is defined under the vertical resolution of `288`. If you change your vertical resolution to `144`, the simple way of doing this is to half these values.
