### ISSUE TITLE
generate_tusimple_lines是如何计算出来的

### ISSUE THREAD

**Issue by zhangjy2008327** [cfzd/Ultra-Fast-Lane-Detection#9]
作者你好，正在学习你的代码，根据我的理解，这里有些问题(以tusimple数据集为例)：
(1)generate_tusimple_lines函数应该是对生成的一幅图中的4条线进行取点吧？
(2)就是想知道generate_tusimple_lines函数实现的原理或者公式是什么？griding_num,=100， localization_type=rel和out的大小有关系吗？比如out=144x400时，griding_num还是100吗？localization_type值也不会变动吗？
如果有时间且方便的时候还请回复一下，谢谢

**Comment by cfzd** [comment]
@zhangjy2008327 
你好，`generate_tusimple_lines`函数的核心就是[这行代码](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/evaluation/eval_wrapper.py#L80). 假设图像宽为w，那么将`[0, griding_num]`这个区间映射到`[0, w]`就可以了。 因为Tusimple数据集是在原图大小上做评估的，所以不论你输入大小是多少，最后统一在宽1280情况下输出。 可以说这段代码和你做完数据增强后的图像大小无关。

`localization_type`是论文中用到的定位方式，通过求位置分布的期望得到最终位置。

**Comment by zhangjy2008327** [comment]
非常感谢你的回复，受益匪浅，继续学习一下，如有问题到时再向你请教啊。
