### ISSUE TITLE
Error occured on WIndows when launching train.py

### ISSUE THREAD

**Issue by fchyan** [cfzd/Ultra-Fast-Lane-Detection#90]
Hi professor!
After seen the results on demos I think it is really a great job for lane detection. However, when I'm trying to run train.py this error occured:

RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss2d_forward

![image](https://user-images.githubusercontent.com/66468206/92934483-1e507c00-f47a-11ea-858c-065adb1bde47.png)

It leads me to 'loss_cur = loss_dict['op'][i](*datas)' in line46 train.py
It seems that loss_cur should be a 'long' format but now it's an 'int'. But according to my searching, in python 3.x 'long' format is deleted. Then I have no idea how to continue. Please show me a way out. Thank you very much!

By the way, if using Windows another error may easily occur in line90 common.py:
os.system('cp %s %s'%(f,os.path.join(to_path,'code',f[2:])))
Cuz there is no 'cp' command in Windows and it can't be directly changed to 'copy' due to different function usage. I solved it by  downloading a Windows' version 'cp' command. Hope it can help.

**Comment by cfzd** [comment]
@fchyan 
Sorry for the late response.  For the `cp` problem, I'll look at it.

But the mentioned data type problem is really weird. Could you please insert some debug code and report the results? Please change the L44-L46 of train.py like this:
```
        datas = [results[src] for src in data_src]

        print('loss type: ', loss_dict['name'][i], '   |   ', 'data types: ', [data.dtype for data in datas])

        loss_cur = loss_dict['op'][i](*datas)
```

**Comment by fchyan** [comment]
Hi professor!
I've added the codes as you suggested and the results look like this:
![image](https://user-images.githubusercontent.com/66468206/93064770-838ab400-f6aa-11ea-89c6-8e838d87cc2f.png)
Is there anything suspicious?

**Comment by cfzd** [comment]
@fchyan 
It's weird that the PyTorch data loader didn't convert the label to the `long` type. For a quick fix, you can change the L20 and L25 of `train.py`:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/train.py#L20 and 
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/train.py#L25

to 
```
img, cls_label, seg_label = img.cuda(), cls_label.long().cuda(), seg_label.long().cuda()
```
and
```
img, cls_label = img.cuda(), cls_label.long().cuda()
```

This should fix the problem.
