### ISSUE TITLE
support different number of lanes submit has bugs

### ISSUE THREAD

**Issue by gneworld** [cfzd/Ultra-Fast-Lane-Detection#93]
您好，看了下 https://github.com/cfzd/Ultra-Fast-Lane-Detection/commit/7666b176ac61427d9c3c6570b0f7dffd945f168a  这个submit有bug， culane数据集里部分图片虽然有三条车道线mask，灰度值范围却不是1，2，3，而是2，3，4，所以下面的code当
 self.num_lanes=3时，对于部分数据只能取到两条车道，请大佬审查一下，谢谢
    -        for lane_idx in range(1, 5):
   +       for lane_idx in range(1, self.num_lanes + 1):

**Comment by cfzd** [comment]
@gneworld 
这个其实比较难解决。因为 [1, num_lanes+1) 这个区间在culane数据集上的定义是从左到右数的，(2，3，4)这种情况4那条车道线是最右边的，其实是会被丢弃掉的。

**Comment by gneworld** [comment]
@cfzd  我改了下code，只训练 2,3 这两条车道，丢弃1,4两条车道数据，意图解决变道时车道线扭曲的问题，然而经测试发现问题依旧存在，按理说现在模型只推理两条车道，即使发生变道，例如往左变道，那么当前车辆正压着的车道线就应该是2，没有歧义发生才对，可实际情况是仍然存在扭曲跳动的问题，请问是什么原因？

**Comment by cfzd** [comment]
@gneworld 这个其实我在知乎上也讨论过，我看id好像就是和你。变道主要是因为类别转换导致的，对于同一条车道线，变道时它的类别会发生变化，所以检测不好。我觉得训练两条线并不会解决类别转换问题。

**Comment by gneworld** [comment]
@cfzd 看来变道这个问题是无解了吗  ┭┮﹏┭┮
