### ISSUE TITLE
Threshold for predicted points

### ISSUE THREAD

**Issue by aralhekimoglu** [cfzd/Ultra-Fast-Lane-Detection#96]
After training using my own dataset, I am facing the problem where there are lanes predicted even though there are no lanes. Compared to other Lane Detection methods, I realized that this method tends to produce more false positives. I know that there is a "No Lane class" in coming out of the network but that alone does not solve the problem. I also tried to filter out probabilities after calling softmax to network predictions 

https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/demo.py#L75

But still the results are not satisfying. Do you have any suggestions for cases like this ?

**Comment by cfzd** [comment]
@aralhekimoglu 
I think there might be two ways to solve the problem. 
1. Use rules to filter out false positives.
A lane is represented by many row anchors. And for each row anchor, we can get a probability of "no lane". In this way, if many row anchors of a lane are "no lane", we can directly filter this lane out by adjusting the threshold number of "no lane". For example, a lane is composed of `10` row anchors. If there are `5` row anchors are "no lane", just discard it.
2. Use a lane-level classification branch
Our method is in fact a method with row anchor-level classification of "no lane". You can also add a lane-level classification of "no lane". For each lane, you can directly predict the absence of this lane as a whole. This is also a common way as SCNN, SAD, and other segmentation methods. The implementation of this is also simple. For example, on Culane, you can add four binary classification outputs and each output corresponds to the absence of each lane.

**Comment by jinfagang** [comment]
@aralhekimoglu  How do u get every single points prob in every single lane?
