### ISSUE TITLE
Error while evaluating on CULANE

### ISSUE THREAD

**Issue by tcazw** [cfzd/Ultra-Fast-Lane-Detection#98]
Hi, thanks for sharing. I face some issue during evaluation.
I have 'make' the files as instructed in the 'install' session.
Then I face these errors while evaluating the CULANE:

(lane-det) ai@fyp-1:~/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection$ python test.py configs/culane.py --test_model /home/ai/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/logpath/20200928_220411_lr_1e-01_b_32/ep049.pth --test_work_dir /home/ai/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/tmp
merge  test_model  config
merge  test_work_dir  config
start testing...
100%|████████████████████████████████████| 4335/4335 [03:47<00:00, 19.07it/s]
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
./evaluation/culane/evaluate: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    eval_lane(net, cfg.dataset, cfg.data_root, cfg.test_work_dir, cfg.griding_num, False, distributed)
  File "/home/ai/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/evaluation/eval_wrapper.py", line 138, in eval_lane
    res = call_culane_eval(data_root, 'culane_eval_tmp', work_dir)
  File "/home/ai/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/evaluation/eval_wrapper.py", line 229, in call_culane_eval
    res_all['res_normal'] = read_helper(out0)
  File "/home/ai/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/evaluation/eval_wrapper.py", line 167, in read_helper
    lines = open(path, 'r').readlines()[1:]
FileNotFoundError: [Errno 2] No such file or directory: '/home/ai/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/tmp/txt/out0_normal.txt'

**Comment by know-one-1** [comment]
hey @tcazw  i also faced the same issue you can go in, Ultra-Fast-Lane-Detection/evaluation/culane and then execute "make " command to compile all c files and then again execute test.py, it will work.

**Comment by tcazw** [comment]
> hey @tcazw i also faced the same issue you can go in, Ultra-Fast-Lane-Detection/evaluation/culane and then execute "make " command to compile all c files and then again execute test.py, it will work.

hi, thanks for replying. Actually I already execute the make command inside the evaluation/culane, and the following are the outcomes:

(lane-det) ai@fyp-1:~/Ultra_fast_lane_detection/Ultra-Fast-Lane-Detection/evaluation/culane$ make
CXX src/counter.cpp
CXX src/lane_compare.cpp
CXX src/evaluate.cpp
CXX src/spline.cpp
CXX/LD evaluate

**Comment by know-one-1** [comment]
@tcazw if you got the "evaluate" excecutable then your code should work as i faced the exact same problem and my workaround was, steps that i mentioned.

**Comment by tcazw** [comment]
@know-one-1  Just now I make the files again and execute again, but this error still shows up. Anyway, thanks for the help!

**Comment by cfzd** [comment]
@tcazw 
You can try to run this:
```
sudo ldconfig -v
```

**Comment by tcazw** [comment]
@cfzd  thank you! problem solved!
